// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeActivity = `-- name: CompleteActivity :one
UPDATE activities.activities
SET status = 'completed', completed_at = now(), version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $3
  AND deleted_at IS NULL AND status = 'open'
  AND (created_by = $4 OR assignee_user_id = $4
       OR security.activity_responsible_allows(workspace_id, id, $4)
       OR $5::text IN ('owner', 'admin'))
RETURNING id, activity_type, title, body, related_type, related_id,
          assignee_user_id, status, priority, due_at, occurred_at,
          recurrence_rule, visibility_scope, scope_department_id, scope_user_id,
          completed_at, created_by, version, created_at, updated_at
`

type CompleteActivityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorRole   string      `json:"actor_role"`
}

type CompleteActivityRow struct {
	ID                pgtype.UUID        `json:"id"`
	ActivityType      string             `json:"activity_type"`
	Title             string             `json:"title"`
	Body              *string            `json:"body"`
	RelatedType       *string            `json:"related_type"`
	RelatedID         pgtype.UUID        `json:"related_id"`
	AssigneeUserID    pgtype.UUID        `json:"assignee_user_id"`
	Status            string             `json:"status"`
	Priority          string             `json:"priority"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	RecurrenceRule    *string            `json:"recurrence_rule"`
	VisibilityScope   string             `json:"visibility_scope"`
	ScopeDepartmentID pgtype.UUID        `json:"scope_department_id"`
	ScopeUserID       pgtype.UUID        `json:"scope_user_id"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CompleteActivity(ctx context.Context, arg CompleteActivityParams) (CompleteActivityRow, error) {
	row := q.db.QueryRow(ctx, completeActivity,
		arg.WorkspaceID,
		arg.ID,
		arg.Version,
		arg.ActorUserID,
		arg.ActorRole,
	)
	var i CompleteActivityRow
	err := row.Scan(
		&i.ID,
		&i.ActivityType,
		&i.Title,
		&i.Body,
		&i.RelatedType,
		&i.RelatedID,
		&i.AssigneeUserID,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.OccurredAt,
		&i.RecurrenceRule,
		&i.VisibilityScope,
		&i.ScopeDepartmentID,
		&i.ScopeUserID,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createActivity = `-- name: CreateActivity :one
INSERT INTO activities.activities (
  workspace_id, id, activity_type, title, body, related_type, related_id,
  assignee_user_id, priority, due_at, occurred_at, ends_at, location,
  recurrence_rule, visibility_scope, scope_department_id, scope_user_id, created_by
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $9,
  $10, $11, $12,
  $13, $14, $15,
  $16, $17, $18
)
RETURNING id, activity_type, title, body, related_type, related_id,
          assignee_user_id, status, priority, due_at, occurred_at,
          ends_at, location, recurrence_rule, visibility_scope,
          scope_department_id, scope_user_id, completed_at, created_by,
          version, created_at, updated_at
`

type CreateActivityParams struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ID                pgtype.UUID        `json:"id"`
	ActivityType      string             `json:"activity_type"`
	Title             string             `json:"title"`
	Body              *string            `json:"body"`
	RelatedType       *string            `json:"related_type"`
	RelatedID         pgtype.UUID        `json:"related_id"`
	AssigneeUserID    pgtype.UUID        `json:"assignee_user_id"`
	Priority          string             `json:"priority"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	Location          *string            `json:"location"`
	RecurrenceRule    *string            `json:"recurrence_rule"`
	VisibilityScope   string             `json:"visibility_scope"`
	ScopeDepartmentID pgtype.UUID        `json:"scope_department_id"`
	ScopeUserID       pgtype.UUID        `json:"scope_user_id"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
}

type CreateActivityRow struct {
	ID                pgtype.UUID        `json:"id"`
	ActivityType      string             `json:"activity_type"`
	Title             string             `json:"title"`
	Body              *string            `json:"body"`
	RelatedType       *string            `json:"related_type"`
	RelatedID         pgtype.UUID        `json:"related_id"`
	AssigneeUserID    pgtype.UUID        `json:"assignee_user_id"`
	Status            string             `json:"status"`
	Priority          string             `json:"priority"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	Location          *string            `json:"location"`
	RecurrenceRule    *string            `json:"recurrence_rule"`
	VisibilityScope   string             `json:"visibility_scope"`
	ScopeDepartmentID pgtype.UUID        `json:"scope_department_id"`
	ScopeUserID       pgtype.UUID        `json:"scope_user_id"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (CreateActivityRow, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.WorkspaceID,
		arg.ID,
		arg.ActivityType,
		arg.Title,
		arg.Body,
		arg.RelatedType,
		arg.RelatedID,
		arg.AssigneeUserID,
		arg.Priority,
		arg.DueAt,
		arg.OccurredAt,
		arg.EndsAt,
		arg.Location,
		arg.RecurrenceRule,
		arg.VisibilityScope,
		arg.ScopeDepartmentID,
		arg.ScopeUserID,
		arg.CreatedBy,
	)
	var i CreateActivityRow
	err := row.Scan(
		&i.ID,
		&i.ActivityType,
		&i.Title,
		&i.Body,
		&i.RelatedType,
		&i.RelatedID,
		&i.AssigneeUserID,
		&i.Status,
		&i.Priority,
		&i.DueAt,
		&i.OccurredAt,
		&i.EndsAt,
		&i.Location,
		&i.RecurrenceRule,
		&i.VisibilityScope,
		&i.ScopeDepartmentID,
		&i.ScopeUserID,
		&i.CompletedAt,
		&i.CreatedBy,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActivities = `-- name: ListActivities :many
SELECT id, activity_type, title, body, related_type, related_id, assignee_user_id,
       status, priority, due_at, occurred_at, recurrence_rule, completed_at,
       visibility_scope, scope_department_id, scope_user_id,
       created_by, version, created_at, updated_at
FROM activities.activities
WHERE activities.activities.workspace_id = $1
  AND deleted_at IS NULL
  AND (
    visibility_scope = 'workspace'
    OR created_by = $2
    OR assignee_user_id = $2
    OR security.activity_assignment_allows(workspace_id, id, $2)
    OR (visibility_scope = 'user' AND scope_user_id = $2)
    OR $3::text IN ('owner', 'admin')
    OR (visibility_scope = 'department' AND EXISTS (
      SELECT 1 FROM tenancy.team_memberships department_member
      WHERE department_member.workspace_id = activities.workspace_id
        AND department_member.team_id = activities.scope_department_id
        AND department_member.membership_id = $4
    ))
  )
  AND ($5::text = '' OR related_type = $5)
  AND ($6::uuid IS NULL OR related_id = $6)
ORDER BY occurred_at DESC, id DESC
LIMIT $7
`

type ListActivitiesParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ActorUserID       pgtype.UUID `json:"actor_user_id"`
	ActorRole         string      `json:"actor_role"`
	ActorMembershipID pgtype.UUID `json:"actor_membership_id"`
	EntityType        string      `json:"entity_type"`
	EntityID          pgtype.UUID `json:"entity_id"`
	PageLimit         int32       `json:"page_limit"`
}

type ListActivitiesRow struct {
	ID                pgtype.UUID        `json:"id"`
	ActivityType      string             `json:"activity_type"`
	Title             string             `json:"title"`
	Body              *string            `json:"body"`
	RelatedType       *string            `json:"related_type"`
	RelatedID         pgtype.UUID        `json:"related_id"`
	AssigneeUserID    pgtype.UUID        `json:"assignee_user_id"`
	Status            string             `json:"status"`
	Priority          string             `json:"priority"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	RecurrenceRule    *string            `json:"recurrence_rule"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	VisibilityScope   string             `json:"visibility_scope"`
	ScopeDepartmentID pgtype.UUID        `json:"scope_department_id"`
	ScopeUserID       pgtype.UUID        `json:"scope_user_id"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listActivities,
		arg.WorkspaceID,
		arg.ActorUserID,
		arg.ActorRole,
		arg.ActorMembershipID,
		arg.EntityType,
		arg.EntityID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivitiesRow{}
	for rows.Next() {
		var i ListActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityType,
			&i.Title,
			&i.Body,
			&i.RelatedType,
			&i.RelatedID,
			&i.AssigneeUserID,
			&i.Status,
			&i.Priority,
			&i.DueAt,
			&i.OccurredAt,
			&i.RecurrenceRule,
			&i.CompletedAt,
			&i.VisibilityScope,
			&i.ScopeDepartmentID,
			&i.ScopeUserID,
			&i.CreatedBy,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
