// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelRateLimitedAutomationExecution = `-- name: CancelRateLimitedAutomationExecution :execrows
DELETE FROM automation.executions
WHERE workspace_id = $1 AND id = $2 AND state = 'queued'
`

type CancelRateLimitedAutomationExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) CancelRateLimitedAutomationExecution(ctx context.Context, arg CancelRateLimitedAutomationExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelRateLimitedAutomationExecution, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeAutomationAction = `-- name: CompleteAutomationAction :execrows
UPDATE automation.action_executions
SET state = 'completed', result = $4, completed_at = now(), updated_at = now(),
    last_error_code = NULL
WHERE workspace_id = $1 AND execution_id = $2 AND action_index = $3
  AND state = 'running'
`

type CompleteAutomationActionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ExecutionID pgtype.UUID `json:"execution_id"`
	ActionIndex int32       `json:"action_index"`
	Result      []byte      `json:"result"`
}

func (q *Queries) CompleteAutomationAction(ctx context.Context, arg CompleteAutomationActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAutomationAction,
		arg.WorkspaceID,
		arg.ExecutionID,
		arg.ActionIndex,
		arg.Result,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const completeAutomationExecution = `-- name: CompleteAutomationExecution :execrows
UPDATE automation.executions
SET state = 'completed', result = $3, completed_at = now(), updated_at = now(),
    last_error_code = NULL
WHERE workspace_id = $1 AND id = $2 AND state = 'running'
`

type CompleteAutomationExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Result      []byte      `json:"result"`
}

func (q *Queries) CompleteAutomationExecution(ctx context.Context, arg CompleteAutomationExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeAutomationExecution, arg.WorkspaceID, arg.ID, arg.Result)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createAutomationRule = `-- name: CreateAutomationRule :one
INSERT INTO automation.rules (
  workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
  rate_limit_per_hour, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
          rate_limit_per_hour, version, created_by, created_at, updated_at
`

type CreateAutomationRuleParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	TriggerType      string      `json:"trigger_type"`
	EntityType       string      `json:"entity_type"`
	Conditions       []byte      `json:"conditions"`
	Actions          []byte      `json:"actions"`
	Enabled          bool        `json:"enabled"`
	RateLimitPerHour int32       `json:"rate_limit_per_hour"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

type CreateAutomationRuleRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateAutomationRule(ctx context.Context, arg CreateAutomationRuleParams) (CreateAutomationRuleRow, error) {
	row := q.db.QueryRow(ctx, createAutomationRule,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.TriggerType,
		arg.EntityType,
		arg.Conditions,
		arg.Actions,
		arg.Enabled,
		arg.RateLimitPerHour,
		arg.CreatedBy,
	)
	var i CreateAutomationRuleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.EntityType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.RateLimitPerHour,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const enqueueAutomationExecution = `-- name: EnqueueAutomationExecution :exec
INSERT INTO platform.jobs (
  workspace_id, id, kind, schema_version, idempotency_key, payload,
  state, attempts, max_attempts, available_at
) VALUES ($1, $2, 'automation.execute', 1, $3, $4, 'ready', 0, $5, now())
ON CONFLICT (workspace_id, kind, idempotency_key) DO NOTHING
`

type EnqueueAutomationExecutionParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ID             pgtype.UUID `json:"id"`
	IdempotencyKey string      `json:"idempotency_key"`
	Payload        []byte      `json:"payload"`
	MaxAttempts    int32       `json:"max_attempts"`
}

func (q *Queries) EnqueueAutomationExecution(ctx context.Context, arg EnqueueAutomationExecutionParams) error {
	_, err := q.db.Exec(ctx, enqueueAutomationExecution,
		arg.WorkspaceID,
		arg.ID,
		arg.IdempotencyKey,
		arg.Payload,
		arg.MaxAttempts,
	)
	return err
}

const failAutomationAction = `-- name: FailAutomationAction :execrows
UPDATE automation.action_executions
SET state = 'failed', last_error_code = $4, updated_at = now()
WHERE workspace_id = $1 AND execution_id = $2 AND action_index = $3
  AND state = 'running'
`

type FailAutomationActionParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ExecutionID   pgtype.UUID `json:"execution_id"`
	ActionIndex   int32       `json:"action_index"`
	LastErrorCode *string     `json:"last_error_code"`
}

func (q *Queries) FailAutomationAction(ctx context.Context, arg FailAutomationActionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAutomationAction,
		arg.WorkspaceID,
		arg.ExecutionID,
		arg.ActionIndex,
		arg.LastErrorCode,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const failAutomationExecution = `-- name: FailAutomationExecution :execrows
UPDATE automation.executions
SET state = CASE WHEN $1::boolean THEN 'dead' ELSE 'failed' END,
    result = $2,
    completed_at = CASE WHEN $1::boolean THEN now() ELSE NULL END,
    updated_at = now(), last_error_code = $3
WHERE workspace_id = $4
  AND id = $5
  AND state = 'running'
`

type FailAutomationExecutionParams struct {
	Dead        bool        `json:"dead"`
	Result      []byte      `json:"result"`
	ErrorCode   *string     `json:"error_code"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) FailAutomationExecution(ctx context.Context, arg FailAutomationExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, failAutomationExecution,
		arg.Dead,
		arg.Result,
		arg.ErrorCode,
		arg.WorkspaceID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getActivityAutomationSnapshot = `-- name: GetActivityAutomationSnapshot :one
SELECT jsonb_build_object(
  'activity_type', activity_type, 'title', title, 'related_type', related_type,
  'related_id', related_id, 'assignee_user_id', assignee_user_id,
  'due_at', due_at, 'priority', priority, 'status', status,
  'recurrence_rule', recurrence_rule, 'completed_at', completed_at,
  'occurred_at', occurred_at
) AS snapshot
FROM activities.activities
WHERE workspace_id = $1 AND id = $2
`

type GetActivityAutomationSnapshotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetActivityAutomationSnapshot(ctx context.Context, arg GetActivityAutomationSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getActivityAutomationSnapshot, arg.WorkspaceID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const getAutomationAction = `-- name: GetAutomationAction :one
SELECT state, result, idempotency_key
FROM automation.action_executions
WHERE workspace_id = $1 AND execution_id = $2 AND action_index = $3
`

type GetAutomationActionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ExecutionID pgtype.UUID `json:"execution_id"`
	ActionIndex int32       `json:"action_index"`
}

type GetAutomationActionRow struct {
	State          string `json:"state"`
	Result         []byte `json:"result"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) GetAutomationAction(ctx context.Context, arg GetAutomationActionParams) (GetAutomationActionRow, error) {
	row := q.db.QueryRow(ctx, getAutomationAction, arg.WorkspaceID, arg.ExecutionID, arg.ActionIndex)
	var i GetAutomationActionRow
	err := row.Scan(&i.State, &i.Result, &i.IdempotencyKey)
	return i, err
}

const getAutomationExecution = `-- name: GetAutomationExecution :one
SELECT workspace_id, id, rule_id, event_id, correlation_id, depth, state,
       attempts, result, trigger_type, event_payload, started_at,
       completed_at, updated_at, last_error_code, created_at
FROM automation.executions
WHERE workspace_id = $1 AND id = $2
`

type GetAutomationExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetAutomationExecutionRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Depth         int32              `json:"depth"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	Result        []byte             `json:"result"`
	TriggerType   string             `json:"trigger_type"`
	EventPayload  []byte             `json:"event_payload"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastErrorCode *string            `json:"last_error_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetAutomationExecution(ctx context.Context, arg GetAutomationExecutionParams) (GetAutomationExecutionRow, error) {
	row := q.db.QueryRow(ctx, getAutomationExecution, arg.WorkspaceID, arg.ID)
	var i GetAutomationExecutionRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.RuleID,
		&i.EventID,
		&i.CorrelationID,
		&i.Depth,
		&i.State,
		&i.Attempts,
		&i.Result,
		&i.TriggerType,
		&i.EventPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const getAutomationOutboxEvent = `-- name: GetAutomationOutboxEvent :one
SELECT id, event_type, aggregate_type, aggregate_id, correlation_id, payload
FROM platform.outbox_events
WHERE workspace_id = $1 AND id = $2
`

type GetAutomationOutboxEventParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetAutomationOutboxEventRow struct {
	ID            pgtype.UUID `json:"id"`
	EventType     string      `json:"event_type"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	CorrelationID pgtype.UUID `json:"correlation_id"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) GetAutomationOutboxEvent(ctx context.Context, arg GetAutomationOutboxEventParams) (GetAutomationOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, getAutomationOutboxEvent, arg.WorkspaceID, arg.ID)
	var i GetAutomationOutboxEventRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.CorrelationID,
		&i.Payload,
	)
	return i, err
}

const getAutomationRule = `-- name: GetAutomationRule :one
SELECT workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
       rate_limit_per_hour, version, created_by, created_at, updated_at
FROM automation.rules
WHERE workspace_id = $1 AND id = $2
`

type GetAutomationRuleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetAutomationRuleRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetAutomationRule(ctx context.Context, arg GetAutomationRuleParams) (GetAutomationRuleRow, error) {
	row := q.db.QueryRow(ctx, getAutomationRule, arg.WorkspaceID, arg.ID)
	var i GetAutomationRuleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.EntityType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.RateLimitPerHour,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompanyAutomationSnapshot = `-- name: GetCompanyAutomationSnapshot :one
SELECT jsonb_build_object(
  'name', name, 'domain', domain, 'industry', industry,
  'owner_user_id', owner_user_id, 'team_id', team_id,
  'status', status, 'address', address, 'custom_fields', custom_fields
) AS snapshot
FROM customers.companies
WHERE workspace_id = $1 AND id = $2
`

type GetCompanyAutomationSnapshotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetCompanyAutomationSnapshot(ctx context.Context, arg GetCompanyAutomationSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getCompanyAutomationSnapshot, arg.WorkspaceID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const getContactAutomationSnapshot = `-- name: GetContactAutomationSnapshot :one
SELECT jsonb_build_object(
  'first_name', first_name, 'last_name', last_name, 'display_name', display_name,
  'email', email, 'phone', phone, 'job_title', job_title, 'company_id', company_id,
  'owner_user_id', owner_user_id, 'team_id', team_id, 'status', status,
  'source', source, 'last_contacted_at', last_contacted_at,
  'next_activity_at', next_activity_at, 'custom_fields', custom_fields,
  'tags', COALESCE((
    SELECT jsonb_agg(relation.tag_id ORDER BY relation.tag_id)
    FROM customers.contact_tags relation
    WHERE relation.workspace_id = contacts.workspace_id AND relation.contact_id = contacts.id
  ), '[]'::jsonb)
) AS snapshot
FROM customers.contacts contacts
WHERE contacts.workspace_id = $1 AND contacts.id = $2
`

type GetContactAutomationSnapshotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetContactAutomationSnapshot(ctx context.Context, arg GetContactAutomationSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getContactAutomationSnapshot, arg.WorkspaceID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const getDealAutomationSnapshot = `-- name: GetDealAutomationSnapshot :one
SELECT jsonb_build_object(
  'name', name, 'pipeline_id', pipeline_id, 'stage_id', stage_id,
  'contact_id', contact_id, 'company_id', company_id,
  'owner_user_id', owner_user_id,
  'amount_minor', amount_minor, 'currency', currency,
  'expected_close_date', expected_close_date, 'status', status,
  'lost_reason', lost_reason,
  'custom_fields', custom_fields
) AS snapshot
FROM sales.deals
WHERE workspace_id = $1 AND id = $2
`

type GetDealAutomationSnapshotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetDealAutomationSnapshot(ctx context.Context, arg GetDealAutomationSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getDealAutomationSnapshot, arg.WorkspaceID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const getLeadAutomationSnapshot = `-- name: GetLeadAutomationSnapshot :one
SELECT jsonb_build_object(
  'name', name, 'email', email, 'company_name', company_name,
  'status', status, 'source', source, 'owner_user_id', owner_user_id,
  'converted_contact_id', converted_contact_id,
  'converted_company_id', converted_company_id, 'converted_deal_id', converted_deal_id,
  'custom_fields', custom_fields
) AS snapshot
FROM sales.leads
WHERE workspace_id = $1 AND id = $2
`

type GetLeadAutomationSnapshotParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetLeadAutomationSnapshot(ctx context.Context, arg GetLeadAutomationSnapshotParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getLeadAutomationSnapshot, arg.WorkspaceID, arg.ID)
	var snapshot []byte
	err := row.Scan(&snapshot)
	return snapshot, err
}

const listAutomationRules = `-- name: ListAutomationRules :many
SELECT workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
       rate_limit_per_hour, version, created_by, created_at, updated_at
FROM automation.rules
WHERE workspace_id = $1
ORDER BY updated_at DESC, id DESC
LIMIT $2
`

type ListAutomationRulesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

type ListAutomationRulesRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListAutomationRules(ctx context.Context, arg ListAutomationRulesParams) ([]ListAutomationRulesRow, error) {
	rows, err := q.db.Query(ctx, listAutomationRules, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAutomationRulesRow{}
	for rows.Next() {
		var i ListAutomationRulesRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.EntityType,
			&i.Conditions,
			&i.Actions,
			&i.Enabled,
			&i.RateLimitPerHour,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEnabledAutomationRulesForTrigger = `-- name: ListEnabledAutomationRulesForTrigger :many
SELECT workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
       rate_limit_per_hour, version, created_by, created_at, updated_at
FROM automation.rules
WHERE workspace_id = $1 AND trigger_type = $2 AND entity_type = $3 AND enabled
ORDER BY updated_at, id
LIMIT 500
`

type ListEnabledAutomationRulesForTriggerParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	TriggerType string      `json:"trigger_type"`
	EntityType  string      `json:"entity_type"`
}

type ListEnabledAutomationRulesForTriggerRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListEnabledAutomationRulesForTrigger(ctx context.Context, arg ListEnabledAutomationRulesForTriggerParams) ([]ListEnabledAutomationRulesForTriggerRow, error) {
	rows, err := q.db.Query(ctx, listEnabledAutomationRulesForTrigger, arg.WorkspaceID, arg.TriggerType, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListEnabledAutomationRulesForTriggerRow{}
	for rows.Next() {
		var i ListEnabledAutomationRulesForTriggerRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Name,
			&i.TriggerType,
			&i.EntityType,
			&i.Conditions,
			&i.Actions,
			&i.Enabled,
			&i.RateLimitPerHour,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneAutomationHourlyUsage = `-- name: PruneAutomationHourlyUsage :execrows
DELETE FROM automation.hourly_usage
WHERE bucket_start < now() - interval '48 hours'
`

func (q *Queries) PruneAutomationHourlyUsage(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, pruneAutomationHourlyUsage)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveAutomationExecution = `-- name: ReserveAutomationExecution :one
INSERT INTO automation.executions (
  workspace_id, id, rule_id, event_id, correlation_id, depth, state,
  trigger_type, event_payload
) VALUES ($1, $2, $3, $4, $5, $6, 'queued', $7, $8)
ON CONFLICT (workspace_id, rule_id, event_id) DO NOTHING
RETURNING workspace_id, id, rule_id, event_id, correlation_id, depth, state,
          attempts, result, trigger_type, event_payload, started_at,
          completed_at, updated_at, last_error_code, created_at
`

type ReserveAutomationExecutionParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ID            pgtype.UUID `json:"id"`
	RuleID        pgtype.UUID `json:"rule_id"`
	EventID       pgtype.UUID `json:"event_id"`
	CorrelationID pgtype.UUID `json:"correlation_id"`
	Depth         int32       `json:"depth"`
	TriggerType   string      `json:"trigger_type"`
	EventPayload  []byte      `json:"event_payload"`
}

type ReserveAutomationExecutionRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Depth         int32              `json:"depth"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	Result        []byte             `json:"result"`
	TriggerType   string             `json:"trigger_type"`
	EventPayload  []byte             `json:"event_payload"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastErrorCode *string            `json:"last_error_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ReserveAutomationExecution(ctx context.Context, arg ReserveAutomationExecutionParams) (ReserveAutomationExecutionRow, error) {
	row := q.db.QueryRow(ctx, reserveAutomationExecution,
		arg.WorkspaceID,
		arg.ID,
		arg.RuleID,
		arg.EventID,
		arg.CorrelationID,
		arg.Depth,
		arg.TriggerType,
		arg.EventPayload,
	)
	var i ReserveAutomationExecutionRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.RuleID,
		&i.EventID,
		&i.CorrelationID,
		&i.Depth,
		&i.State,
		&i.Attempts,
		&i.Result,
		&i.TriggerType,
		&i.EventPayload,
		&i.StartedAt,
		&i.CompletedAt,
		&i.UpdatedAt,
		&i.LastErrorCode,
		&i.CreatedAt,
	)
	return i, err
}

const setAutomationRuleEnabled = `-- name: SetAutomationRuleEnabled :one
UPDATE automation.rules
SET enabled = $3, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $4
RETURNING workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
          rate_limit_per_hour, version, created_by, created_at, updated_at
`

type SetAutomationRuleEnabledParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Enabled     bool        `json:"enabled"`
	Version     int64       `json:"version"`
}

type SetAutomationRuleEnabledRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SetAutomationRuleEnabled(ctx context.Context, arg SetAutomationRuleEnabledParams) (SetAutomationRuleEnabledRow, error) {
	row := q.db.QueryRow(ctx, setAutomationRuleEnabled,
		arg.WorkspaceID,
		arg.ID,
		arg.Enabled,
		arg.Version,
	)
	var i SetAutomationRuleEnabledRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.EntityType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.RateLimitPerHour,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const startAutomationAction = `-- name: StartAutomationAction :one
INSERT INTO automation.action_executions (
  workspace_id, execution_id, action_index, action_type, idempotency_key, state
) VALUES ($1, $2, $3, $4, $5, 'running')
ON CONFLICT (workspace_id, execution_id, action_index) DO UPDATE
SET state = 'running', action_type = EXCLUDED.action_type,
    idempotency_key = EXCLUDED.idempotency_key,
    started_at = now(), updated_at = now(), last_error_code = NULL
WHERE automation.action_executions.state = 'failed'
   OR (automation.action_executions.state = 'running'
       AND automation.action_executions.updated_at < now() - interval '2 minutes')
RETURNING state, result, idempotency_key
`

type StartAutomationActionParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ExecutionID    pgtype.UUID `json:"execution_id"`
	ActionIndex    int32       `json:"action_index"`
	ActionType     string      `json:"action_type"`
	IdempotencyKey string      `json:"idempotency_key"`
}

type StartAutomationActionRow struct {
	State          string `json:"state"`
	Result         []byte `json:"result"`
	IdempotencyKey string `json:"idempotency_key"`
}

func (q *Queries) StartAutomationAction(ctx context.Context, arg StartAutomationActionParams) (StartAutomationActionRow, error) {
	row := q.db.QueryRow(ctx, startAutomationAction,
		arg.WorkspaceID,
		arg.ExecutionID,
		arg.ActionIndex,
		arg.ActionType,
		arg.IdempotencyKey,
	)
	var i StartAutomationActionRow
	err := row.Scan(&i.State, &i.Result, &i.IdempotencyKey)
	return i, err
}

const startAutomationExecution = `-- name: StartAutomationExecution :execrows
UPDATE automation.executions
SET state = 'running', attempts = attempts + 1,
    started_at = COALESCE(started_at, now()), updated_at = now(),
    last_error_code = NULL
WHERE workspace_id = $1 AND id = $2
  AND (
    state IN ('queued', 'failed')
    OR (state = 'running' AND updated_at < now() - interval '2 minutes')
  )
`

type StartAutomationExecutionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) StartAutomationExecution(ctx context.Context, arg StartAutomationExecutionParams) (int64, error) {
	result, err := q.db.Exec(ctx, startAutomationExecution, arg.WorkspaceID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tryConsumeAutomationRateLimit = `-- name: TryConsumeAutomationRateLimit :one
INSERT INTO automation.hourly_usage (
  workspace_id, rule_id, bucket_start, used
) VALUES ($1, $2, date_trunc('hour', now()), 1)
ON CONFLICT (workspace_id, rule_id, bucket_start) DO UPDATE
SET used = automation.hourly_usage.used + 1,
    updated_at = now()
WHERE automation.hourly_usage.used < $3
RETURNING used
`

type TryConsumeAutomationRateLimitParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	RuleID           pgtype.UUID `json:"rule_id"`
	RateLimitPerHour int32       `json:"rate_limit_per_hour"`
}

func (q *Queries) TryConsumeAutomationRateLimit(ctx context.Context, arg TryConsumeAutomationRateLimitParams) (int32, error) {
	row := q.db.QueryRow(ctx, tryConsumeAutomationRateLimit, arg.WorkspaceID, arg.RuleID, arg.RateLimitPerHour)
	var used int32
	err := row.Scan(&used)
	return used, err
}

const updateAutomationRule = `-- name: UpdateAutomationRule :one
UPDATE automation.rules
SET name = $3,
    trigger_type = $4,
    entity_type = $5,
    conditions = $6,
    actions = $7,
    rate_limit_per_hour = $8,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $9
RETURNING workspace_id, id, name, trigger_type, entity_type, conditions, actions, enabled,
          rate_limit_per_hour, version, created_by, created_at, updated_at
`

type UpdateAutomationRuleParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	TriggerType      string      `json:"trigger_type"`
	EntityType       string      `json:"entity_type"`
	Conditions       []byte      `json:"conditions"`
	Actions          []byte      `json:"actions"`
	RateLimitPerHour int32       `json:"rate_limit_per_hour"`
	Version          int64       `json:"version"`
}

type UpdateAutomationRuleRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	EntityType       string             `json:"entity_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateAutomationRule(ctx context.Context, arg UpdateAutomationRuleParams) (UpdateAutomationRuleRow, error) {
	row := q.db.QueryRow(ctx, updateAutomationRule,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.TriggerType,
		arg.EntityType,
		arg.Conditions,
		arg.Actions,
		arg.RateLimitPerHour,
		arg.Version,
	)
	var i UpdateAutomationRuleRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.TriggerType,
		&i.EntityType,
		&i.Conditions,
		&i.Actions,
		&i.Enabled,
		&i.RateLimitPerHour,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
