// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: automation_email.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const resolveAutomationEmailRecipient = `-- name: ResolveAutomationEmailRecipient :one
WITH target AS (
  SELECT contact.email AS direct_email, contact.owner_user_id AS user_id
  FROM customers.contacts AS contact
  WHERE $3::text = 'contact'
    AND contact.workspace_id = $2
    AND contact.id = $4
    AND contact.deleted_at IS NULL
  UNION ALL
  SELECT NULL::text, company.owner_user_id
  FROM customers.companies AS company
  WHERE $3::text = 'company'
    AND company.workspace_id = $2
    AND company.id = $4
    AND company.deleted_at IS NULL
  UNION ALL
  SELECT lead.email, lead.owner_user_id
  FROM sales.leads AS lead
  WHERE $3::text = 'lead'
    AND lead.workspace_id = $2
    AND lead.id = $4
    AND lead.deleted_at IS NULL
  UNION ALL
  SELECT contact.email, deal.owner_user_id
  FROM sales.deals AS deal
  LEFT JOIN customers.contacts AS contact
    ON contact.workspace_id = deal.workspace_id
   AND contact.id = deal.contact_id
   AND contact.deleted_at IS NULL
  WHERE $3::text = 'deal'
    AND deal.workspace_id = $2
    AND deal.id = $4
    AND deal.deleted_at IS NULL
  UNION ALL
  SELECT NULL::text, activity.assignee_user_id
  FROM activities.activities AS activity
  WHERE $3::text = 'activity'
    AND activity.workspace_id = $2
    AND activity.id = $4
    AND activity.deleted_at IS NULL
)
SELECT CASE
         WHEN $1::text = 'email' THEN target.direct_email
         WHEN $1::text = 'owner_email' THEN recipient.email
       END::text AS recipient,
       CASE
         WHEN $1::text = 'owner_email'
           THEN COALESCE(membership.locale_override, recipient.preferred_locale, workspace.default_locale)
         ELSE workspace.default_locale
       END::text AS recipient_locale,
       workspace.default_locale, workspace.name AS workspace_name
FROM target
JOIN tenancy.workspaces AS workspace
  ON workspace.id = $2
LEFT JOIN tenancy.memberships AS membership
  ON membership.workspace_id = workspace.id
 AND membership.user_id = target.user_id
 AND membership.status = 'active'
LEFT JOIN identity.users AS recipient
  ON recipient.id = membership.user_id
 AND recipient.status = 'active'
WHERE ($1::text = 'email' AND target.direct_email IS NOT NULL)
   OR ($1::text = 'owner_email' AND recipient.email IS NOT NULL)
LIMIT 1
`

type ResolveAutomationEmailRecipientParams struct {
	RecipientField string      `json:"recipient_field"`
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	TargetType     string      `json:"target_type"`
	TargetID       pgtype.UUID `json:"target_id"`
}

type ResolveAutomationEmailRecipientRow struct {
	Recipient       string `json:"recipient"`
	RecipientLocale string `json:"recipient_locale"`
	DefaultLocale   string `json:"default_locale"`
	WorkspaceName   string `json:"workspace_name"`
}

func (q *Queries) ResolveAutomationEmailRecipient(ctx context.Context, arg ResolveAutomationEmailRecipientParams) (ResolveAutomationEmailRecipientRow, error) {
	row := q.db.QueryRow(ctx, resolveAutomationEmailRecipient,
		arg.RecipientField,
		arg.WorkspaceID,
		arg.TargetType,
		arg.TargetID,
	)
	var i ResolveAutomationEmailRecipientRow
	err := row.Scan(
		&i.Recipient,
		&i.RecipientLocale,
		&i.DefaultLocale,
		&i.WorkspaceName,
	)
	return i, err
}
