// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: companies.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveCompanies = `-- name: CountActiveCompanies :one
SELECT count(*) FROM customers.companies
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveCompanies(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveCompanies, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCompany = `-- name: CreateCompany :one
INSERT INTO customers.companies (
  workspace_id, id, name, domain, domain_normalized, industry, owner_user_id,
  team_id, status, address, custom_fields
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, name, domain, industry, status, owner_user_id, team_id, address,
          custom_fields, version, created_at, updated_at
`

type CreateCompanyParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Domain           *string     `json:"domain"`
	DomainNormalized *string     `json:"domain_normalized"`
	Industry         *string     `json:"industry"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	TeamID           pgtype.UUID `json:"team_id"`
	Status           string      `json:"status"`
	Address          []byte      `json:"address"`
	CustomFields     []byte      `json:"custom_fields"`
}

type CreateCompanyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       *string            `json:"domain"`
	Industry     *string            `json:"industry"`
	Status       string             `json:"status"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Address      []byte             `json:"address"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error) {
	row := q.db.QueryRow(ctx, createCompany,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Domain,
		arg.DomainNormalized,
		arg.Industry,
		arg.OwnerUserID,
		arg.TeamID,
		arg.Status,
		arg.Address,
		arg.CustomFields,
	)
	var i CreateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Status,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Address,
		&i.CustomFields,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCompany = `-- name: GetCompany :one
SELECT id, name, domain, industry, status, owner_user_id, team_id, address, custom_fields,
       version, created_at, updated_at
FROM customers.companies
WHERE workspace_id = $1 AND id = $2 AND deleted_at IS NULL
`

type GetCompanyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetCompanyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       *string            `json:"domain"`
	Industry     *string            `json:"industry"`
	Status       string             `json:"status"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Address      []byte             `json:"address"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCompany(ctx context.Context, arg GetCompanyParams) (GetCompanyRow, error) {
	row := q.db.QueryRow(ctx, getCompany, arg.WorkspaceID, arg.ID)
	var i GetCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Status,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Address,
		&i.CustomFields,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCompanies = `-- name: ListCompanies :many
SELECT id, name, domain, industry, status, owner_user_id, version, created_at, updated_at
FROM customers.companies
WHERE workspace_id = $1 AND deleted_at IS NULL
ORDER BY updated_at DESC, id DESC
LIMIT $2
`

type ListCompaniesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

type ListCompaniesRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Domain      *string            `json:"domain"`
	Industry    *string            `json:"industry"`
	Status      string             `json:"status"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listCompanies, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesRow{}
	for rows.Next() {
		var i ListCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.Status,
			&i.OwnerUserID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCompaniesPage = `-- name: ListCompaniesPage :many
SELECT id, name, domain, industry, status, owner_user_id, team_id, address,
       custom_fields, version, created_at, updated_at
FROM customers.companies
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND ($2::text = '' OR name ILIKE '%' || $2 || '%'
       OR domain_normalized LIKE '%' || lower($2) || '%')
  AND ($3::text = '' OR status = $3)
  AND (updated_at, id) < ($4::timestamptz, $5::uuid)
ORDER BY updated_at DESC, id DESC
LIMIT $6
`

type ListCompaniesPageParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	SearchQuery     string             `json:"search_query"`
	StatusFilter    string             `json:"status_filter"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListCompaniesPageRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       *string            `json:"domain"`
	Industry     *string            `json:"industry"`
	Status       string             `json:"status"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Address      []byte             `json:"address"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCompaniesPage(ctx context.Context, arg ListCompaniesPageParams) ([]ListCompaniesPageRow, error) {
	rows, err := q.db.Query(ctx, listCompaniesPage,
		arg.WorkspaceID,
		arg.SearchQuery,
		arg.StatusFilter,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompaniesPageRow{}
	for rows.Next() {
		var i ListCompaniesPageRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.Status,
			&i.OwnerUserID,
			&i.TeamID,
			&i.Address,
			&i.CustomFields,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedCompanies = `-- name: ListDeletedCompanies :many
SELECT id, name, domain, industry, status, owner_user_id, team_id, version,
       deleted_at, deleted_by, created_at, updated_at
FROM customers.companies
WHERE workspace_id = $1
  AND deleted_at IS NOT NULL
  AND (deleted_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY deleted_at DESC, id DESC
LIMIT $4
`

type ListDeletedCompaniesParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CursorDeletedAt pgtype.Timestamptz `json:"cursor_deleted_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListDeletedCompaniesRow struct {
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Domain      *string            `json:"domain"`
	Industry    *string            `json:"industry"`
	Status      string             `json:"status"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	TeamID      pgtype.UUID        `json:"team_id"`
	Version     int64              `json:"version"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDeletedCompanies(ctx context.Context, arg ListDeletedCompaniesParams) ([]ListDeletedCompaniesRow, error) {
	rows, err := q.db.Query(ctx, listDeletedCompanies,
		arg.WorkspaceID,
		arg.CursorDeletedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedCompaniesRow{}
	for rows.Next() {
		var i ListDeletedCompaniesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Domain,
			&i.Industry,
			&i.Status,
			&i.OwnerUserID,
			&i.TeamID,
			&i.Version,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreCompany = `-- name: RestoreCompany :one
UPDATE customers.companies
SET deleted_at = NULL, deleted_by = NULL, version = version + 1, updated_at = now()
WHERE workspace_id = $1
  AND id = $2
  AND version = $3
  AND deleted_at IS NOT NULL
RETURNING id, name, domain, industry, status, owner_user_id, team_id, address,
          custom_fields, version, created_at, updated_at
`

type RestoreCompanyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

type RestoreCompanyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       *string            `json:"domain"`
	Industry     *string            `json:"industry"`
	Status       string             `json:"status"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Address      []byte             `json:"address"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) RestoreCompany(ctx context.Context, arg RestoreCompanyParams) (RestoreCompanyRow, error) {
	row := q.db.QueryRow(ctx, restoreCompany, arg.WorkspaceID, arg.ID, arg.Version)
	var i RestoreCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Status,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Address,
		&i.CustomFields,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const softDeleteCompany = `-- name: SoftDeleteCompany :one
UPDATE customers.companies
SET deleted_at = now(), deleted_by = $1, version = version + 1, updated_at = now()
WHERE workspace_id = $2
  AND id = $3
  AND version = $4
  AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteCompanyParams struct {
	DeletedBy   pgtype.UUID `json:"deleted_by"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) SoftDeleteCompany(ctx context.Context, arg SoftDeleteCompanyParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteCompany,
		arg.DeletedBy,
		arg.WorkspaceID,
		arg.ID,
		arg.Version,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateCompany = `-- name: UpdateCompany :one
UPDATE customers.companies
SET name = $1,
    domain = $2,
    domain_normalized = $3,
    industry = $4,
    status = $5,
    owner_user_id = $6,
    team_id = $7,
    address = $8,
    custom_fields = $9,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $10
  AND id = $11
  AND version = $12
  AND deleted_at IS NULL
RETURNING id, name, domain, industry, status, owner_user_id, team_id, address,
          custom_fields, version, created_at, updated_at
`

type UpdateCompanyParams struct {
	Name             string      `json:"name"`
	Domain           *string     `json:"domain"`
	DomainNormalized *string     `json:"domain_normalized"`
	Industry         *string     `json:"industry"`
	Status           string      `json:"status"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	TeamID           pgtype.UUID `json:"team_id"`
	Address          []byte      `json:"address"`
	CustomFields     []byte      `json:"custom_fields"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Version          int64       `json:"version"`
}

type UpdateCompanyRow struct {
	ID           pgtype.UUID        `json:"id"`
	Name         string             `json:"name"`
	Domain       *string            `json:"domain"`
	Industry     *string            `json:"industry"`
	Status       string             `json:"status"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	Address      []byte             `json:"address"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error) {
	row := q.db.QueryRow(ctx, updateCompany,
		arg.Name,
		arg.Domain,
		arg.DomainNormalized,
		arg.Industry,
		arg.Status,
		arg.OwnerUserID,
		arg.TeamID,
		arg.Address,
		arg.CustomFields,
		arg.WorkspaceID,
		arg.ID,
		arg.Version,
	)
	var i UpdateCompanyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Domain,
		&i.Industry,
		&i.Status,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Address,
		&i.CustomFields,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
