// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contacts.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveContacts = `-- name: CountActiveContacts :one
SELECT count(*) FROM customers.contacts
WHERE workspace_id = $1 AND deleted_at IS NULL
`

func (q *Queries) CountActiveContacts(ctx context.Context, workspaceID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveContacts, workspaceID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createContact = `-- name: CreateContact :one
INSERT INTO customers.contacts (
  workspace_id, id, first_name, last_name, display_name, email, email_normalized,
  phone, phone_normalized, job_title, company_id, owner_user_id, team_id, status, source,
  address, custom_fields
) VALUES (
  $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17
)
RETURNING id, first_name, last_name, display_name, email, phone, job_title,
          company_id, owner_user_id, team_id, status, source, address, custom_fields,
          last_contacted_at, next_activity_at, version, created_at, updated_at
`

type CreateContactParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ID              pgtype.UUID `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	DisplayName     string      `json:"display_name"`
	Email           *string     `json:"email"`
	EmailNormalized *string     `json:"email_normalized"`
	Phone           *string     `json:"phone"`
	PhoneNormalized *string     `json:"phone_normalized"`
	JobTitle        *string     `json:"job_title"`
	CompanyID       pgtype.UUID `json:"company_id"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	TeamID          pgtype.UUID `json:"team_id"`
	Status          string      `json:"status"`
	Source          *string     `json:"source"`
	Address         []byte      `json:"address"`
	CustomFields    []byte      `json:"custom_fields"`
}

type CreateContactRow struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DisplayName     string             `json:"display_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	JobTitle        *string            `json:"job_title"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	Status          string             `json:"status"`
	Source          *string            `json:"source"`
	Address         []byte             `json:"address"`
	CustomFields    []byte             `json:"custom_fields"`
	LastContactedAt pgtype.Timestamptz `json:"last_contacted_at"`
	NextActivityAt  pgtype.Timestamptz `json:"next_activity_at"`
	Version         int64              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateContact(ctx context.Context, arg CreateContactParams) (CreateContactRow, error) {
	row := q.db.QueryRow(ctx, createContact,
		arg.WorkspaceID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.Phone,
		arg.PhoneNormalized,
		arg.JobTitle,
		arg.CompanyID,
		arg.OwnerUserID,
		arg.TeamID,
		arg.Status,
		arg.Source,
		arg.Address,
		arg.CustomFields,
	)
	var i CreateContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.JobTitle,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Status,
		&i.Source,
		&i.Address,
		&i.CustomFields,
		&i.LastContactedAt,
		&i.NextActivityAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getContact = `-- name: GetContact :one
SELECT c.id, c.first_name, c.last_name, c.display_name, c.email, c.phone,
       c.job_title, c.company_id, co.name AS company_name, c.owner_user_id,
       c.status, c.source, c.address, c.custom_fields, c.last_contacted_at,
       c.next_activity_at, c.version, c.created_at, c.updated_at
FROM customers.contacts c
LEFT JOIN customers.companies co
  ON co.workspace_id = c.workspace_id AND co.id = c.company_id AND co.deleted_at IS NULL
WHERE c.workspace_id = $1 AND c.id = $2 AND c.deleted_at IS NULL
`

type GetContactParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetContactRow struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DisplayName     string             `json:"display_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	JobTitle        *string            `json:"job_title"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	CompanyName     *string            `json:"company_name"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	Status          string             `json:"status"`
	Source          *string            `json:"source"`
	Address         []byte             `json:"address"`
	CustomFields    []byte             `json:"custom_fields"`
	LastContactedAt pgtype.Timestamptz `json:"last_contacted_at"`
	NextActivityAt  pgtype.Timestamptz `json:"next_activity_at"`
	Version         int64              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetContact(ctx context.Context, arg GetContactParams) (GetContactRow, error) {
	row := q.db.QueryRow(ctx, getContact, arg.WorkspaceID, arg.ID)
	var i GetContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.JobTitle,
		&i.CompanyID,
		&i.CompanyName,
		&i.OwnerUserID,
		&i.Status,
		&i.Source,
		&i.Address,
		&i.CustomFields,
		&i.LastContactedAt,
		&i.NextActivityAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeletedContact = `-- name: GetDeletedContact :one
SELECT id, first_name, last_name, display_name, email, phone, job_title,
       company_id, owner_user_id, team_id, status, source, address, custom_fields,
       last_contacted_at, next_activity_at, version, deleted_at, deleted_by,
       created_at, updated_at
FROM customers.contacts
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NOT NULL
`

type GetDeletedContactParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetDeletedContactRow struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DisplayName     string             `json:"display_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	JobTitle        *string            `json:"job_title"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	Status          string             `json:"status"`
	Source          *string            `json:"source"`
	Address         []byte             `json:"address"`
	CustomFields    []byte             `json:"custom_fields"`
	LastContactedAt pgtype.Timestamptz `json:"last_contacted_at"`
	NextActivityAt  pgtype.Timestamptz `json:"next_activity_at"`
	Version         int64              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy       pgtype.UUID        `json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDeletedContact(ctx context.Context, arg GetDeletedContactParams) (GetDeletedContactRow, error) {
	row := q.db.QueryRow(ctx, getDeletedContact, arg.WorkspaceID, arg.ID)
	var i GetDeletedContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.JobTitle,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Status,
		&i.Source,
		&i.Address,
		&i.CustomFields,
		&i.LastContactedAt,
		&i.NextActivityAt,
		&i.Version,
		&i.DeletedAt,
		&i.DeletedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listContactTags = `-- name: ListContactTags :many
SELECT t.id, t.name, t.color
FROM customers.contact_tags ct
JOIN customers.tags t ON t.workspace_id = ct.workspace_id AND t.id = ct.tag_id
WHERE ct.workspace_id = $1 AND ct.contact_id = $2
ORDER BY t.name, t.id
`

type ListContactTagsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ContactID   pgtype.UUID `json:"contact_id"`
}

type ListContactTagsRow struct {
	ID    pgtype.UUID `json:"id"`
	Name  string      `json:"name"`
	Color string      `json:"color"`
}

func (q *Queries) ListContactTags(ctx context.Context, arg ListContactTagsParams) ([]ListContactTagsRow, error) {
	rows, err := q.db.Query(ctx, listContactTags, arg.WorkspaceID, arg.ContactID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactTagsRow{}
	for rows.Next() {
		var i ListContactTagsRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Color); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContacts = `-- name: ListContacts :many
SELECT c.id, c.first_name, c.last_name, c.display_name, c.email, c.phone,
       c.company_id, co.name AS company_name, c.owner_user_id, c.status, c.source,
       c.custom_fields, c.version, c.created_at, c.updated_at
FROM customers.contacts c
LEFT JOIN customers.companies co
  ON co.workspace_id = c.workspace_id AND co.id = c.company_id AND co.deleted_at IS NULL
WHERE c.workspace_id = $1
  AND c.deleted_at IS NULL
  AND ($2::text = '' OR c.display_name ILIKE '%' || $2 || '%'
       OR c.email_normalized LIKE '%' || lower($2) || '%')
  AND ($3::text = '' OR c.status = $3)
  AND (c.updated_at, c.id) < ($4::timestamptz, $5::uuid)
ORDER BY c.updated_at DESC, c.id DESC
LIMIT $6
`

type ListContactsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	SearchQuery     string             `json:"search_query"`
	StatusFilter    string             `json:"status_filter"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListContactsRow struct {
	ID           pgtype.UUID        `json:"id"`
	FirstName    string             `json:"first_name"`
	LastName     string             `json:"last_name"`
	DisplayName  string             `json:"display_name"`
	Email        *string            `json:"email"`
	Phone        *string            `json:"phone"`
	CompanyID    pgtype.UUID        `json:"company_id"`
	CompanyName  *string            `json:"company_name"`
	OwnerUserID  pgtype.UUID        `json:"owner_user_id"`
	Status       string             `json:"status"`
	Source       *string            `json:"source"`
	CustomFields []byte             `json:"custom_fields"`
	Version      int64              `json:"version"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error) {
	rows, err := q.db.Query(ctx, listContacts,
		arg.WorkspaceID,
		arg.SearchQuery,
		arg.StatusFilter,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContactsRow{}
	for rows.Next() {
		var i ListContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.CompanyID,
			&i.CompanyName,
			&i.OwnerUserID,
			&i.Status,
			&i.Source,
			&i.CustomFields,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeletedContacts = `-- name: ListDeletedContacts :many
SELECT id, first_name, last_name, display_name, email, phone, company_id,
       owner_user_id, status, source, version, deleted_at, deleted_by, created_at, updated_at
FROM customers.contacts
WHERE workspace_id = $1
  AND deleted_at IS NOT NULL
  AND (deleted_at, id) < ($2::timestamptz, $3::uuid)
ORDER BY deleted_at DESC, id DESC
LIMIT $4
`

type ListDeletedContactsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	CursorDeletedAt pgtype.Timestamptz `json:"cursor_deleted_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListDeletedContactsRow struct {
	ID          pgtype.UUID        `json:"id"`
	FirstName   string             `json:"first_name"`
	LastName    string             `json:"last_name"`
	DisplayName string             `json:"display_name"`
	Email       *string            `json:"email"`
	Phone       *string            `json:"phone"`
	CompanyID   pgtype.UUID        `json:"company_id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	Status      string             `json:"status"`
	Source      *string            `json:"source"`
	Version     int64              `json:"version"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy   pgtype.UUID        `json:"deleted_by"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDeletedContacts(ctx context.Context, arg ListDeletedContactsParams) ([]ListDeletedContactsRow, error) {
	rows, err := q.db.Query(ctx, listDeletedContacts,
		arg.WorkspaceID,
		arg.CursorDeletedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeletedContactsRow{}
	for rows.Next() {
		var i ListDeletedContactsRow
		if err := rows.Scan(
			&i.ID,
			&i.FirstName,
			&i.LastName,
			&i.DisplayName,
			&i.Email,
			&i.Phone,
			&i.CompanyID,
			&i.OwnerUserID,
			&i.Status,
			&i.Source,
			&i.Version,
			&i.DeletedAt,
			&i.DeletedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreContact = `-- name: RestoreContact :one
UPDATE customers.contacts
SET deleted_at = NULL, deleted_by = NULL, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $3 AND deleted_at IS NOT NULL
RETURNING version
`

type RestoreContactParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) RestoreContact(ctx context.Context, arg RestoreContactParams) (int64, error) {
	row := q.db.QueryRow(ctx, restoreContact, arg.WorkspaceID, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const softDeleteContact = `-- name: SoftDeleteContact :one
UPDATE customers.contacts
SET deleted_at = now(), deleted_by = $3, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $4 AND deleted_at IS NULL
RETURNING version
`

type SoftDeleteContactParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	DeletedBy   pgtype.UUID `json:"deleted_by"`
	Version     int64       `json:"version"`
}

func (q *Queries) SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) (int64, error) {
	row := q.db.QueryRow(ctx, softDeleteContact,
		arg.WorkspaceID,
		arg.ID,
		arg.DeletedBy,
		arg.Version,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const updateContact = `-- name: UpdateContact :one
UPDATE customers.contacts
SET first_name = $3,
    last_name = $4,
    display_name = $5,
    email = $6,
    email_normalized = $7,
    phone = $8,
    phone_normalized = $9,
    job_title = $10,
    company_id = $11,
    owner_user_id = $12,
    team_id = $13,
    status = $14,
    source = $15,
    address = $16,
    custom_fields = $17,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $18 AND deleted_at IS NULL
RETURNING id, first_name, last_name, display_name, email, phone, job_title,
          company_id, owner_user_id, team_id, status, source, address, custom_fields,
          last_contacted_at, next_activity_at, version, created_at, updated_at
`

type UpdateContactParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ID              pgtype.UUID `json:"id"`
	FirstName       string      `json:"first_name"`
	LastName        string      `json:"last_name"`
	DisplayName     string      `json:"display_name"`
	Email           *string     `json:"email"`
	EmailNormalized *string     `json:"email_normalized"`
	Phone           *string     `json:"phone"`
	PhoneNormalized *string     `json:"phone_normalized"`
	JobTitle        *string     `json:"job_title"`
	CompanyID       pgtype.UUID `json:"company_id"`
	OwnerUserID     pgtype.UUID `json:"owner_user_id"`
	TeamID          pgtype.UUID `json:"team_id"`
	Status          string      `json:"status"`
	Source          *string     `json:"source"`
	Address         []byte      `json:"address"`
	CustomFields    []byte      `json:"custom_fields"`
	Version         int64       `json:"version"`
}

type UpdateContactRow struct {
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DisplayName     string             `json:"display_name"`
	Email           *string            `json:"email"`
	Phone           *string            `json:"phone"`
	JobTitle        *string            `json:"job_title"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	Status          string             `json:"status"`
	Source          *string            `json:"source"`
	Address         []byte             `json:"address"`
	CustomFields    []byte             `json:"custom_fields"`
	LastContactedAt pgtype.Timestamptz `json:"last_contacted_at"`
	NextActivityAt  pgtype.Timestamptz `json:"next_activity_at"`
	Version         int64              `json:"version"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateContact(ctx context.Context, arg UpdateContactParams) (UpdateContactRow, error) {
	row := q.db.QueryRow(ctx, updateContact,
		arg.WorkspaceID,
		arg.ID,
		arg.FirstName,
		arg.LastName,
		arg.DisplayName,
		arg.Email,
		arg.EmailNormalized,
		arg.Phone,
		arg.PhoneNormalized,
		arg.JobTitle,
		arg.CompanyID,
		arg.OwnerUserID,
		arg.TeamID,
		arg.Status,
		arg.Source,
		arg.Address,
		arg.CustomFields,
		arg.Version,
	)
	var i UpdateContactRow
	err := row.Scan(
		&i.ID,
		&i.FirstName,
		&i.LastName,
		&i.DisplayName,
		&i.Email,
		&i.Phone,
		&i.JobTitle,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.TeamID,
		&i.Status,
		&i.Source,
		&i.Address,
		&i.CustomFields,
		&i.LastContactedAt,
		&i.NextActivityAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
