// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: customers_advanced.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomerTag = `-- name: CreateCustomerTag :one
INSERT INTO customers.tags (workspace_id, id, name, color)
VALUES ($1, $2, $3, $4)
RETURNING id, name, color, version, created_at, updated_at
`

type CreateCustomerTagParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	Color       string      `json:"color"`
}

type CreateCustomerTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateCustomerTag(ctx context.Context, arg CreateCustomerTagParams) (CreateCustomerTagRow, error) {
	row := q.db.QueryRow(ctx, createCustomerTag,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Color,
	)
	var i CreateCustomerTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomerTag = `-- name: DeleteCustomerTag :one
DELETE FROM customers.tags
WHERE workspace_id = $1
  AND id = $2
  AND version = $3
RETURNING id
`

type DeleteCustomerTagParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) DeleteCustomerTag(ctx context.Context, arg DeleteCustomerTagParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, deleteCustomerTag, arg.WorkspaceID, arg.ID, arg.Version)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getImportSession = `-- name: GetImportSession :one
SELECT id, actor_user_id, entity_type, status, mapping, source_headers,
       total_rows, processed_rows, created_rows, error_rows,
       created_at, updated_at, started_at, completed_at
FROM customers.import_sessions
WHERE workspace_id = $1 AND id = $2
`

type GetImportSessionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetImportSessionRow struct {
	ID            pgtype.UUID        `json:"id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	EntityType    string             `json:"entity_type"`
	Status        string             `json:"status"`
	Mapping       []byte             `json:"mapping"`
	SourceHeaders []byte             `json:"source_headers"`
	TotalRows     int32              `json:"total_rows"`
	ProcessedRows int32              `json:"processed_rows"`
	CreatedRows   int32              `json:"created_rows"`
	ErrorRows     int32              `json:"error_rows"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
}

func (q *Queries) GetImportSession(ctx context.Context, arg GetImportSessionParams) (GetImportSessionRow, error) {
	row := q.db.QueryRow(ctx, getImportSession, arg.WorkspaceID, arg.ID)
	var i GetImportSessionRow
	err := row.Scan(
		&i.ID,
		&i.ActorUserID,
		&i.EntityType,
		&i.Status,
		&i.Mapping,
		&i.SourceHeaders,
		&i.TotalRows,
		&i.ProcessedRows,
		&i.CreatedRows,
		&i.ErrorRows,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listCustomFieldDefinitions = `-- name: ListCustomFieldDefinitions :many
SELECT id, entity_type, field_key, label, value_type, validation, options,
       schema_version, version, created_at, updated_at
FROM customers.custom_field_definitions
WHERE workspace_id = $1
  AND ($2::text = '' OR entity_type = $2)
ORDER BY entity_type, field_key, id
`

type ListCustomFieldDefinitionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityType  string      `json:"entity_type"`
}

type ListCustomFieldDefinitionsRow struct {
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	FieldKey      string             `json:"field_key"`
	Label         string             `json:"label"`
	ValueType     string             `json:"value_type"`
	Validation    []byte             `json:"validation"`
	Options       []byte             `json:"options"`
	SchemaVersion int32              `json:"schema_version"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListCustomFieldDefinitions(ctx context.Context, arg ListCustomFieldDefinitionsParams) ([]ListCustomFieldDefinitionsRow, error) {
	rows, err := q.db.Query(ctx, listCustomFieldDefinitions, arg.WorkspaceID, arg.EntityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomFieldDefinitionsRow{}
	for rows.Next() {
		var i ListCustomFieldDefinitionsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.FieldKey,
			&i.Label,
			&i.ValueType,
			&i.Validation,
			&i.Options,
			&i.SchemaVersion,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomerTags = `-- name: ListCustomerTags :many

SELECT id, name, color, version, created_at, updated_at
FROM customers.tags
WHERE workspace_id = $1
ORDER BY lower(name), id
`

type ListCustomerTagsRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Advanced customer-domain SQL lives here even where package-local typed row
// scanners are used for JSON-heavy payloads. Keeping the statements centralized
// makes tenant predicates and query plans reviewable.
func (q *Queries) ListCustomerTags(ctx context.Context, workspaceID pgtype.UUID) ([]ListCustomerTagsRow, error) {
	rows, err := q.db.Query(ctx, listCustomerTags, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCustomerTagsRow{}
	for rows.Next() {
		var i ListCustomerTagsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Color,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSavedViews = `-- name: ListSavedViews :many
SELECT id, owner_user_id, entity_type, name, definition, is_shared, version,
       created_at, updated_at
FROM customers.saved_views
WHERE workspace_id = $1
  AND entity_type = $2
  AND (owner_user_id = $3 OR is_shared)
ORDER BY is_shared DESC, lower(name), id
`

type ListSavedViewsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityType  string      `json:"entity_type"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
}

type ListSavedViewsRow struct {
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	EntityType  string             `json:"entity_type"`
	Name        string             `json:"name"`
	Definition  []byte             `json:"definition"`
	IsShared    bool               `json:"is_shared"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListSavedViews(ctx context.Context, arg ListSavedViewsParams) ([]ListSavedViewsRow, error) {
	rows, err := q.db.Query(ctx, listSavedViews, arg.WorkspaceID, arg.EntityType, arg.ActorUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSavedViewsRow{}
	for rows.Next() {
		var i ListSavedViewsRow
		if err := rows.Scan(
			&i.ID,
			&i.OwnerUserID,
			&i.EntityType,
			&i.Name,
			&i.Definition,
			&i.IsShared,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomerTag = `-- name: UpdateCustomerTag :one
UPDATE customers.tags
SET name = $1, color = $2, version = version + 1, updated_at = now()
WHERE workspace_id = $3
  AND id = $4
  AND version = $5
RETURNING id, name, color, version, created_at, updated_at
`

type UpdateCustomerTagParams struct {
	Name        string      `json:"name"`
	Color       string      `json:"color"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

type UpdateCustomerTagRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateCustomerTag(ctx context.Context, arg UpdateCustomerTagParams) (UpdateCustomerTagRow, error) {
	row := q.db.QueryRow(ctx, updateCustomerTag,
		arg.Name,
		arg.Color,
		arg.WorkspaceID,
		arg.ID,
		arg.Version,
	)
	var i UpdateCustomerTagRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Color,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
