// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearLoginFailures = `-- name: ClearLoginFailures :exec
UPDATE identity.users
SET failed_login_count = 0, locked_until = NULL, updated_at = now()
WHERE id = $1 AND (failed_login_count <> 0 OR locked_until IS NOT NULL)
`

func (q *Queries) ClearLoginFailures(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, clearLoginFailures, id)
	return err
}

const createSession = `-- name: CreateSession :exec
INSERT INTO identity.sessions (
  id, user_id, token_hash, csrf_hash, session_version, user_agent, ip_address, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSessionParams struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TokenHash      []byte             `json:"token_hash"`
	CsrfHash       []byte             `json:"csrf_hash"`
	SessionVersion int64              `json:"session_version"`
	UserAgent      string             `json:"user_agent"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateSession(ctx context.Context, arg CreateSessionParams) error {
	_, err := q.db.Exec(ctx, createSession,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.CsrfHash,
		arg.SessionVersion,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createUser = `-- name: CreateUser :one
INSERT INTO identity.users (
  id, email, email_normalized, display_name, password_hash, preferred_locale
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, email, email_normalized, display_name, password_hash, preferred_locale,
          status, session_version, failed_login_count, locked_until, password_changed_at,
          created_at, updated_at
`

type CreateUserParams struct {
	ID              pgtype.UUID `json:"id"`
	Email           string      `json:"email"`
	EmailNormalized string      `json:"email_normalized"`
	DisplayName     string      `json:"display_name"`
	PasswordHash    string      `json:"password_hash"`
	PreferredLocale string      `json:"preferred_locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.EmailNormalized,
		arg.DisplayName,
		arg.PasswordHash,
		arg.PreferredLocale,
	)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PreferredLocale,
		&i.Status,
		&i.SessionVersion,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSessionPrincipal = `-- name: GetSessionPrincipal :one
SELECT s.id AS session_id, s.user_id, s.csrf_hash, s.expires_at, s.last_seen_at,
       u.email, u.display_name, u.preferred_locale, u.status, u.session_version
FROM identity.sessions s
JOIN identity.users u ON u.id = s.user_id
WHERE s.token_hash = $1
  AND s.revoked_at IS NULL
  AND s.expires_at > now()
  AND s.session_version = u.session_version
`

type GetSessionPrincipalRow struct {
	SessionID       pgtype.UUID        `json:"session_id"`
	UserID          pgtype.UUID        `json:"user_id"`
	CsrfHash        []byte             `json:"csrf_hash"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt      pgtype.Timestamptz `json:"last_seen_at"`
	Email           string             `json:"email"`
	DisplayName     string             `json:"display_name"`
	PreferredLocale string             `json:"preferred_locale"`
	Status          string             `json:"status"`
	SessionVersion  int64              `json:"session_version"`
}

func (q *Queries) GetSessionPrincipal(ctx context.Context, tokenHash []byte) (GetSessionPrincipalRow, error) {
	row := q.db.QueryRow(ctx, getSessionPrincipal, tokenHash)
	var i GetSessionPrincipalRow
	err := row.Scan(
		&i.SessionID,
		&i.UserID,
		&i.CsrfHash,
		&i.ExpiresAt,
		&i.LastSeenAt,
		&i.Email,
		&i.DisplayName,
		&i.PreferredLocale,
		&i.Status,
		&i.SessionVersion,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, email_normalized, display_name, password_hash, preferred_locale,
       status, session_version, failed_login_count, locked_until, password_changed_at,
       created_at, updated_at
FROM identity.users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id pgtype.UUID) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PreferredLocale,
		&i.Status,
		&i.SessionVersion,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByNormalizedEmail = `-- name: GetUserByNormalizedEmail :one
SELECT id, email, email_normalized, display_name, password_hash, preferred_locale,
       status, session_version, failed_login_count, locked_until, password_changed_at,
       created_at, updated_at
FROM identity.users
WHERE email_normalized = $1
`

func (q *Queries) GetUserByNormalizedEmail(ctx context.Context, emailNormalized string) (IdentityUser, error) {
	row := q.db.QueryRow(ctx, getUserByNormalizedEmail, emailNormalized)
	var i IdentityUser
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.EmailNormalized,
		&i.DisplayName,
		&i.PasswordHash,
		&i.PreferredLocale,
		&i.Status,
		&i.SessionVersion,
		&i.FailedLoginCount,
		&i.LockedUntil,
		&i.PasswordChangedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const recordLoginFailure = `-- name: RecordLoginFailure :exec
UPDATE identity.users
SET failed_login_count = failed_login_count + 1,
    locked_until = CASE
      WHEN failed_login_count + 1 >= 10 THEN now() + interval '15 minutes'
      WHEN failed_login_count + 1 >= 5 THEN now() + interval '1 minute'
      ELSE locked_until
    END,
    updated_at = now()
WHERE id = $1
`

func (q *Queries) RecordLoginFailure(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordLoginFailure, id)
	return err
}

const revokeAllUserSessions = `-- name: RevokeAllUserSessions :exec
WITH bumped AS (
  UPDATE identity.users
  SET session_version = session_version + 1, updated_at = now()
  WHERE id = $1
  RETURNING id
)
UPDATE identity.sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE user_id = $1 AND revoked_at IS NULL AND EXISTS (SELECT 1 FROM bumped)
`

func (q *Queries) RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllUserSessions, userID)
	return err
}

const revokeSessionByToken = `-- name: RevokeSessionByToken :exec
UPDATE identity.sessions SET revoked_at = COALESCE(revoked_at, now())
WHERE token_hash = $1
`

func (q *Queries) RevokeSessionByToken(ctx context.Context, tokenHash []byte) error {
	_, err := q.db.Exec(ctx, revokeSessionByToken, tokenHash)
	return err
}

const touchSession = `-- name: TouchSession :exec
UPDATE identity.sessions
SET last_seen_at = now()
WHERE id = $1 AND last_seen_at < now() - interval '5 minutes'
`

func (q *Queries) TouchSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, touchSession, id)
	return err
}

const updateUserLocale = `-- name: UpdateUserLocale :one
UPDATE identity.users
SET preferred_locale = $2, updated_at = now()
WHERE id = $1
RETURNING id, email, display_name, preferred_locale
`

type UpdateUserLocaleParams struct {
	ID              pgtype.UUID `json:"id"`
	PreferredLocale string      `json:"preferred_locale"`
}

type UpdateUserLocaleRow struct {
	ID              pgtype.UUID `json:"id"`
	Email           string      `json:"email"`
	DisplayName     string      `json:"display_name"`
	PreferredLocale string      `json:"preferred_locale"`
}

func (q *Queries) UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) (UpdateUserLocaleRow, error) {
	row := q.db.QueryRow(ctx, updateUserLocale, arg.ID, arg.PreferredLocale)
	var i UpdateUserLocaleRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.PreferredLocale,
	)
	return i, err
}
