// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: identity_advanced.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const advanceMFATimeStep = `-- name: AdvanceMFATimeStep :execrows
UPDATE identity.mfa_configurations
SET last_accepted_step = $2
WHERE user_id = $1
  AND enabled_at IS NOT NULL
  AND (last_accepted_step IS NULL OR last_accepted_step < $2)
`

type AdvanceMFATimeStepParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	LastAcceptedStep *int64      `json:"last_accepted_step"`
}

func (q *Queries) AdvanceMFATimeStep(ctx context.Context, arg AdvanceMFATimeStepParams) (int64, error) {
	result, err := q.db.Exec(ctx, advanceMFATimeStep, arg.UserID, arg.LastAcceptedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeMFAChallenge = `-- name: ConsumeMFAChallenge :execrows
UPDATE identity.mfa_login_challenges
SET consumed_at = now()
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) ConsumeMFAChallenge(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeMFAChallenge, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumePasswordResetToken = `-- name: ConsumePasswordResetToken :execrows
UPDATE identity.password_reset_tokens
SET used_at = now()
WHERE id = $1 AND used_at IS NULL
`

func (q *Queries) ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumePasswordResetToken, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeRecoveryCode = `-- name: ConsumeRecoveryCode :execrows
UPDATE identity.recovery_codes
SET used_at = now()
WHERE user_id = $1 AND code_hash = $2 AND used_at IS NULL
`

type ConsumeRecoveryCodeParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
}

func (q *Queries) ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error) {
	result, err := q.db.Exec(ctx, consumeRecoveryCode, arg.UserID, arg.CodeHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createMFAChallenge = `-- name: CreateMFAChallenge :exec
INSERT INTO identity.mfa_login_challenges (
  id, user_id, token_hash, user_agent, ip_address, expires_at
) VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateMFAChallengeParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	UserAgent string             `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) error {
	_, err := q.db.Exec(ctx, createMFAChallenge,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.UserAgent,
		arg.IpAddress,
		arg.ExpiresAt,
	)
	return err
}

const createPasswordResetToken = `-- name: CreatePasswordResetToken :exec
INSERT INTO identity.password_reset_tokens (id, user_id, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreatePasswordResetTokenParams struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error {
	_, err := q.db.Exec(ctx, createPasswordResetToken,
		arg.ID,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
	)
	return err
}

const createRecoveryCode = `-- name: CreateRecoveryCode :exec
INSERT INTO identity.recovery_codes (id, user_id, code_hash)
VALUES ($1, $2, $3)
`

type CreateRecoveryCodeParams struct {
	ID       pgtype.UUID `json:"id"`
	UserID   pgtype.UUID `json:"user_id"`
	CodeHash []byte      `json:"code_hash"`
}

func (q *Queries) CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error {
	_, err := q.db.Exec(ctx, createRecoveryCode, arg.ID, arg.UserID, arg.CodeHash)
	return err
}

const deleteActivePasswordResetTokens = `-- name: DeleteActivePasswordResetTokens :exec
DELETE FROM identity.password_reset_tokens
WHERE user_id = $1 AND used_at IS NULL
`

func (q *Queries) DeleteActivePasswordResetTokens(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteActivePasswordResetTokens, userID)
	return err
}

const deleteExpiredMFAChallenges = `-- name: DeleteExpiredMFAChallenges :exec
DELETE FROM identity.mfa_login_challenges
WHERE expires_at < now() - interval '1 day' OR consumed_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredMFAChallenges(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredMFAChallenges)
	return err
}

const deleteExpiredPasswordResetTokens = `-- name: DeleteExpiredPasswordResetTokens :exec
DELETE FROM identity.password_reset_tokens
WHERE expires_at < now() - interval '1 day' OR used_at < now() - interval '1 day'
`

func (q *Queries) DeleteExpiredPasswordResetTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPasswordResetTokens)
	return err
}

const deleteExpiredSessions = `-- name: DeleteExpiredSessions :exec
DELETE FROM identity.sessions
WHERE expires_at < now() - interval '1 day' OR revoked_at < now() - interval '30 days'
`

func (q *Queries) DeleteExpiredSessions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredSessions)
	return err
}

const deletePasswordResetToken = `-- name: DeletePasswordResetToken :exec
DELETE FROM identity.password_reset_tokens WHERE id = $1
`

func (q *Queries) DeletePasswordResetToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePasswordResetToken, id)
	return err
}

const deleteRecoveryCodes = `-- name: DeleteRecoveryCodes :exec
DELETE FROM identity.recovery_codes WHERE user_id = $1
`

func (q *Queries) DeleteRecoveryCodes(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRecoveryCodes, userID)
	return err
}

const disableMFAConfiguration = `-- name: DisableMFAConfiguration :exec
DELETE FROM identity.mfa_configurations WHERE user_id = $1
`

func (q *Queries) DisableMFAConfiguration(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, disableMFAConfiguration, userID)
	return err
}

const enableMFAConfiguration = `-- name: EnableMFAConfiguration :execrows
UPDATE identity.mfa_configurations
SET secret_ciphertext = pending_secret_ciphertext,
    secret_nonce = pending_secret_nonce,
    key_id = pending_key_id,
    pending_secret_ciphertext = NULL,
    pending_secret_nonce = NULL,
    pending_key_id = NULL,
    pending_created_at = NULL,
    enabled_at = now(),
    last_accepted_step = $2
WHERE user_id = $1 AND pending_secret_ciphertext IS NOT NULL
`

type EnableMFAConfigurationParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	LastAcceptedStep *int64      `json:"last_accepted_step"`
}

func (q *Queries) EnableMFAConfiguration(ctx context.Context, arg EnableMFAConfigurationParams) (int64, error) {
	result, err := q.db.Exec(ctx, enableMFAConfiguration, arg.UserID, arg.LastAcceptedStep)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByIDForPasswordChange = `-- name: GetUserByIDForPasswordChange :one
SELECT id, password_hash, status, session_version
FROM identity.users
WHERE id = $1
FOR UPDATE
`

type GetUserByIDForPasswordChangeRow struct {
	ID             pgtype.UUID `json:"id"`
	PasswordHash   string      `json:"password_hash"`
	Status         string      `json:"status"`
	SessionVersion int64       `json:"session_version"`
}

func (q *Queries) GetUserByIDForPasswordChange(ctx context.Context, id pgtype.UUID) (GetUserByIDForPasswordChangeRow, error) {
	row := q.db.QueryRow(ctx, getUserByIDForPasswordChange, id)
	var i GetUserByIDForPasswordChangeRow
	err := row.Scan(
		&i.ID,
		&i.PasswordHash,
		&i.Status,
		&i.SessionVersion,
	)
	return i, err
}

const isMFAEnabled = `-- name: IsMFAEnabled :one
SELECT EXISTS (
  SELECT 1 FROM identity.mfa_configurations
  WHERE user_id = $1 AND enabled_at IS NOT NULL
)
`

func (q *Queries) IsMFAEnabled(ctx context.Context, userID pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, isMFAEnabled, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const lockMFAChallenge = `-- name: LockMFAChallenge :one
SELECT id, user_id, user_agent, ip_address, expires_at, attempts
FROM identity.mfa_login_challenges
WHERE token_hash = $1
  AND consumed_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

type LockMFAChallengeRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	UserAgent string             `json:"user_agent"`
	IpAddress *netip.Addr        `json:"ip_address"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	Attempts  int32              `json:"attempts"`
}

func (q *Queries) LockMFAChallenge(ctx context.Context, tokenHash []byte) (LockMFAChallengeRow, error) {
	row := q.db.QueryRow(ctx, lockMFAChallenge, tokenHash)
	var i LockMFAChallengeRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.UserAgent,
		&i.IpAddress,
		&i.ExpiresAt,
		&i.Attempts,
	)
	return i, err
}

const lockMFAConfiguration = `-- name: LockMFAConfiguration :one
SELECT user_id, secret_ciphertext, secret_nonce, key_id, enabled_at,
       last_accepted_step, created_at, pending_secret_ciphertext,
       pending_secret_nonce, pending_key_id, pending_created_at
FROM identity.mfa_configurations
WHERE user_id = $1
FOR UPDATE
`

func (q *Queries) LockMFAConfiguration(ctx context.Context, userID pgtype.UUID) (IdentityMfaConfiguration, error) {
	row := q.db.QueryRow(ctx, lockMFAConfiguration, userID)
	var i IdentityMfaConfiguration
	err := row.Scan(
		&i.UserID,
		&i.SecretCiphertext,
		&i.SecretNonce,
		&i.KeyID,
		&i.EnabledAt,
		&i.LastAcceptedStep,
		&i.CreatedAt,
		&i.PendingSecretCiphertext,
		&i.PendingSecretNonce,
		&i.PendingKeyID,
		&i.PendingCreatedAt,
	)
	return i, err
}

const lockPasswordResetToken = `-- name: LockPasswordResetToken :one
SELECT id, user_id, expires_at
FROM identity.password_reset_tokens
WHERE token_hash = $1
  AND used_at IS NULL
  AND expires_at > now()
FOR UPDATE
`

type LockPasswordResetTokenRow struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) LockPasswordResetToken(ctx context.Context, tokenHash []byte) (LockPasswordResetTokenRow, error) {
	row := q.db.QueryRow(ctx, lockPasswordResetToken, tokenHash)
	var i LockPasswordResetTokenRow
	err := row.Scan(&i.ID, &i.UserID, &i.ExpiresAt)
	return i, err
}

const recordMFAChallengeFailure = `-- name: RecordMFAChallengeFailure :exec
UPDATE identity.mfa_login_challenges
SET attempts = attempts + 1,
    consumed_at = CASE WHEN attempts + 1 >= 8 THEN now() ELSE consumed_at END
WHERE id = $1 AND consumed_at IS NULL
`

func (q *Queries) RecordMFAChallengeFailure(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, recordMFAChallengeFailure, id)
	return err
}

const replacePasswordAndRevokeSessions = `-- name: ReplacePasswordAndRevokeSessions :one
WITH updated AS (
  UPDATE identity.users
  SET password_hash = $1,
      password_changed_at = now(),
      session_version = session_version + 1,
      failed_login_count = 0,
      locked_until = NULL,
      updated_at = now()
  WHERE identity.users.id = $2
  RETURNING session_version
), revoked AS (
  UPDATE identity.sessions
  SET revoked_at = COALESCE(revoked_at, now())
  WHERE identity.sessions.user_id = $2 AND revoked_at IS NULL
  RETURNING id
)
SELECT session_version FROM updated
`

type ReplacePasswordAndRevokeSessionsParams struct {
	PasswordHash string      `json:"password_hash"`
	TargetUserID pgtype.UUID `json:"target_user_id"`
}

func (q *Queries) ReplacePasswordAndRevokeSessions(ctx context.Context, arg ReplacePasswordAndRevokeSessionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, replacePasswordAndRevokeSessions, arg.PasswordHash, arg.TargetUserID)
	var session_version int64
	err := row.Scan(&session_version)
	return session_version, err
}

const upsertPendingMFAConfiguration = `-- name: UpsertPendingMFAConfiguration :exec
INSERT INTO identity.mfa_configurations (
  user_id, secret_ciphertext, secret_nonce, key_id, enabled_at, last_accepted_step,
  pending_secret_ciphertext, pending_secret_nonce, pending_key_id, pending_created_at
) VALUES ($1, $2, $3, $4, NULL, NULL, $2, $3, $4, now())
ON CONFLICT (user_id) DO UPDATE
SET pending_secret_ciphertext = EXCLUDED.pending_secret_ciphertext,
    pending_secret_nonce = EXCLUDED.pending_secret_nonce,
    pending_key_id = EXCLUDED.pending_key_id,
    pending_created_at = now()
`

type UpsertPendingMFAConfigurationParams struct {
	UserID           pgtype.UUID `json:"user_id"`
	SecretCiphertext []byte      `json:"secret_ciphertext"`
	SecretNonce      []byte      `json:"secret_nonce"`
	KeyID            string      `json:"key_id"`
}

func (q *Queries) UpsertPendingMFAConfiguration(ctx context.Context, arg UpsertPendingMFAConfigurationParams) error {
	_, err := q.db.Exec(ctx, upsertPendingMFAConfiguration,
		arg.UserID,
		arg.SecretCiphertext,
		arg.SecretNonce,
		arg.KeyID,
	)
	return err
}
