// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: localization.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const contentTranslationCoverage = `-- name: ContentTranslationCoverage :many
SELECT r.namespace,
       count(*)::bigint AS total,
       count(t.resource_key) FILTER (WHERE t.status = 'published')::bigint AS published,
       count(t.resource_key) FILTER (WHERE t.status = 'draft')::bigint AS draft,
       (count(*) - count(t.resource_key))::bigint AS missing
FROM localization.content_resources r
LEFT JOIN localization.content_translations t
  ON t.workspace_id = r.workspace_id
 AND t.namespace = r.namespace
 AND t.resource_key = r.resource_key
 AND t.locale = $1
WHERE r.workspace_id = $2
GROUP BY r.namespace
ORDER BY r.namespace
`

type ContentTranslationCoverageParams struct {
	Locale      string      `json:"locale"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type ContentTranslationCoverageRow struct {
	Namespace string `json:"namespace"`
	Total     int64  `json:"total"`
	Published int64  `json:"published"`
	Draft     int64  `json:"draft"`
	Missing   int64  `json:"missing"`
}

func (q *Queries) ContentTranslationCoverage(ctx context.Context, arg ContentTranslationCoverageParams) ([]ContentTranslationCoverageRow, error) {
	rows, err := q.db.Query(ctx, contentTranslationCoverage, arg.Locale, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ContentTranslationCoverageRow{}
	for rows.Next() {
		var i ContentTranslationCoverageRow
		if err := rows.Scan(
			&i.Namespace,
			&i.Total,
			&i.Published,
			&i.Draft,
			&i.Missing,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createContentResource = `-- name: CreateContentResource :one
INSERT INTO localization.content_resources (
  workspace_id, namespace, resource_key, source_locale, source_text,
  description, placeholders, created_by, updated_by
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7, $8, $8
)
ON CONFLICT (workspace_id, namespace, resource_key) DO NOTHING
RETURNING workspace_id, namespace, resource_key, source_locale, source_text,
          description, placeholders, version, created_by, updated_by,
          created_at, updated_at
`

type CreateContentResourceParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Namespace    string      `json:"namespace"`
	ResourceKey  string      `json:"resource_key"`
	SourceLocale string      `json:"source_locale"`
	SourceText   string      `json:"source_text"`
	Description  string      `json:"description"`
	Placeholders []string    `json:"placeholders"`
	ActorID      pgtype.UUID `json:"actor_id"`
}

func (q *Queries) CreateContentResource(ctx context.Context, arg CreateContentResourceParams) (LocalizationContentResource, error) {
	row := q.db.QueryRow(ctx, createContentResource,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
		arg.SourceLocale,
		arg.SourceText,
		arg.Description,
		arg.Placeholders,
		arg.ActorID,
	)
	var i LocalizationContentResource
	err := row.Scan(
		&i.WorkspaceID,
		&i.Namespace,
		&i.ResourceKey,
		&i.SourceLocale,
		&i.SourceText,
		&i.Description,
		&i.Placeholders,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createContentTranslation = `-- name: CreateContentTranslation :one
INSERT INTO localization.content_translations (
  workspace_id, namespace, resource_key, locale, translated_text, status,
  updated_by
) VALUES (
  $1, $2, $3,
  $4, $5, $6,
  $7
)
ON CONFLICT (workspace_id, namespace, resource_key, locale) DO NOTHING
RETURNING workspace_id, namespace, resource_key, locale, translated_text,
          status, version, updated_by, created_at, updated_at
`

type CreateContentTranslationParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Namespace      string      `json:"namespace"`
	ResourceKey    string      `json:"resource_key"`
	Locale         string      `json:"locale"`
	TranslatedText string      `json:"translated_text"`
	Status         string      `json:"status"`
	ActorID        pgtype.UUID `json:"actor_id"`
}

func (q *Queries) CreateContentTranslation(ctx context.Context, arg CreateContentTranslationParams) (LocalizationContentTranslation, error) {
	row := q.db.QueryRow(ctx, createContentTranslation,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
		arg.Locale,
		arg.TranslatedText,
		arg.Status,
		arg.ActorID,
	)
	var i LocalizationContentTranslation
	err := row.Scan(
		&i.WorkspaceID,
		&i.Namespace,
		&i.ResourceKey,
		&i.Locale,
		&i.TranslatedText,
		&i.Status,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteContentResources = `-- name: DeleteContentResources :exec
DELETE FROM localization.content_resources
WHERE workspace_id = $1
  AND namespace = $2
  AND resource_key = ANY($3::text[])
`

type DeleteContentResourcesParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Namespace    string      `json:"namespace"`
	ResourceKeys []string    `json:"resource_keys"`
}

func (q *Queries) DeleteContentResources(ctx context.Context, arg DeleteContentResourcesParams) error {
	_, err := q.db.Exec(ctx, deleteContentResources, arg.WorkspaceID, arg.Namespace, arg.ResourceKeys)
	return err
}

const getContentResource = `-- name: GetContentResource :one
SELECT workspace_id, namespace, resource_key, source_locale, source_text,
       description, placeholders, version, created_by, updated_by,
       created_at, updated_at
FROM localization.content_resources
WHERE workspace_id = $1
  AND namespace = $2
  AND resource_key = $3
`

type GetContentResourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Namespace   string      `json:"namespace"`
	ResourceKey string      `json:"resource_key"`
}

func (q *Queries) GetContentResource(ctx context.Context, arg GetContentResourceParams) (LocalizationContentResource, error) {
	row := q.db.QueryRow(ctx, getContentResource, arg.WorkspaceID, arg.Namespace, arg.ResourceKey)
	var i LocalizationContentResource
	err := row.Scan(
		&i.WorkspaceID,
		&i.Namespace,
		&i.ResourceKey,
		&i.SourceLocale,
		&i.SourceText,
		&i.Description,
		&i.Placeholders,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceLocalizationSettings = `-- name: GetWorkspaceLocalizationSettings :one
SELECT default_locale, supported_locales, version, updated_at
FROM tenancy.workspaces
WHERE id = $1
`

type GetWorkspaceLocalizationSettingsRow struct {
	DefaultLocale    string             `json:"default_locale"`
	SupportedLocales []string           `json:"supported_locales"`
	Version          int64              `json:"version"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceLocalizationSettings(ctx context.Context, workspaceID pgtype.UUID) (GetWorkspaceLocalizationSettingsRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceLocalizationSettings, workspaceID)
	var i GetWorkspaceLocalizationSettingsRow
	err := row.Scan(
		&i.DefaultLocale,
		&i.SupportedLocales,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const listContentTranslations = `-- name: ListContentTranslations :many
SELECT r.namespace, r.resource_key, r.source_locale, r.source_text,
       r.description, r.placeholders, r.version AS resource_version,
       t.locale, t.translated_text, t.status, t.version AS translation_version,
       COALESCE(t.updated_at, r.updated_at) AS updated_at
FROM localization.content_resources r
LEFT JOIN localization.content_translations t
  ON t.workspace_id = r.workspace_id
 AND t.namespace = r.namespace
 AND t.resource_key = r.resource_key
 AND t.locale = $1
WHERE r.workspace_id = $2
  AND ($3::text = '' OR r.namespace = $3)
  AND (
    $4::text = ''
    OR r.resource_key ILIKE '%' || $4 || '%'
    OR r.source_text ILIKE '%' || $4 || '%'
    OR COALESCE(t.translated_text, '') ILIKE '%' || $4 || '%'
  )
  AND (
    $5::text = ''
    OR ($5 = 'missing' AND t.locale IS NULL)
    OR ($5 IN ('draft', 'published') AND t.status = $5)
  )
  AND (r.namespace, r.resource_key) >
      ($6::text, $7::text)
ORDER BY r.namespace, r.resource_key
LIMIT $8
`

type ListContentTranslationsParams struct {
	Locale            string      `json:"locale"`
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	NamespaceFilter   string      `json:"namespace_filter"`
	SearchQuery       string      `json:"search_query"`
	StatusFilter      string      `json:"status_filter"`
	CursorNamespace   string      `json:"cursor_namespace"`
	CursorResourceKey string      `json:"cursor_resource_key"`
	PageLimit         int32       `json:"page_limit"`
}

type ListContentTranslationsRow struct {
	Namespace          string             `json:"namespace"`
	ResourceKey        string             `json:"resource_key"`
	SourceLocale       string             `json:"source_locale"`
	SourceText         string             `json:"source_text"`
	Description        string             `json:"description"`
	Placeholders       []string           `json:"placeholders"`
	ResourceVersion    int64              `json:"resource_version"`
	Locale             *string            `json:"locale"`
	TranslatedText     *string            `json:"translated_text"`
	Status             *string            `json:"status"`
	TranslationVersion *int64             `json:"translation_version"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListContentTranslations(ctx context.Context, arg ListContentTranslationsParams) ([]ListContentTranslationsRow, error) {
	rows, err := q.db.Query(ctx, listContentTranslations,
		arg.Locale,
		arg.WorkspaceID,
		arg.NamespaceFilter,
		arg.SearchQuery,
		arg.StatusFilter,
		arg.CursorNamespace,
		arg.CursorResourceKey,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListContentTranslationsRow{}
	for rows.Next() {
		var i ListContentTranslationsRow
		if err := rows.Scan(
			&i.Namespace,
			&i.ResourceKey,
			&i.SourceLocale,
			&i.SourceText,
			&i.Description,
			&i.Placeholders,
			&i.ResourceVersion,
			&i.Locale,
			&i.TranslatedText,
			&i.Status,
			&i.TranslationVersion,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markContentTranslationsDraft = `-- name: MarkContentTranslationsDraft :exec
UPDATE localization.content_translations
SET status = 'draft',
    updated_by = $1,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $2
  AND namespace = $3
  AND resource_key = $4
  AND status <> 'draft'
`

type MarkContentTranslationsDraftParams struct {
	ActorID     pgtype.UUID `json:"actor_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Namespace   string      `json:"namespace"`
	ResourceKey string      `json:"resource_key"`
}

func (q *Queries) MarkContentTranslationsDraft(ctx context.Context, arg MarkContentTranslationsDraftParams) error {
	_, err := q.db.Exec(ctx, markContentTranslationsDraft,
		arg.ActorID,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
	)
	return err
}

const resolvePublishedContent = `-- name: ResolvePublishedContent :one
SELECT r.source_text,
       COALESCE(requested.translated_text, fallback.translated_text, r.source_text) AS resolved_text,
       (CASE
         WHEN requested.translated_text IS NOT NULL THEN $1::text
         WHEN fallback.translated_text IS NOT NULL THEN $2::text
         ELSE r.source_locale
       END)::text AS resolved_locale
FROM localization.content_resources r
LEFT JOIN localization.content_translations requested
  ON requested.workspace_id = r.workspace_id
 AND requested.namespace = r.namespace
 AND requested.resource_key = r.resource_key
 AND requested.locale = $1
 AND requested.status = 'published'
LEFT JOIN localization.content_translations fallback
  ON fallback.workspace_id = r.workspace_id
 AND fallback.namespace = r.namespace
 AND fallback.resource_key = r.resource_key
 AND fallback.locale = $2
 AND fallback.status = 'published'
WHERE r.workspace_id = $3
  AND r.namespace = $4
  AND r.resource_key = $5
`

type ResolvePublishedContentParams struct {
	RequestedLocale string      `json:"requested_locale"`
	FallbackLocale  string      `json:"fallback_locale"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Namespace       string      `json:"namespace"`
	ResourceKey     string      `json:"resource_key"`
}

type ResolvePublishedContentRow struct {
	SourceText     string `json:"source_text"`
	ResolvedText   string `json:"resolved_text"`
	ResolvedLocale string `json:"resolved_locale"`
}

func (q *Queries) ResolvePublishedContent(ctx context.Context, arg ResolvePublishedContentParams) (ResolvePublishedContentRow, error) {
	row := q.db.QueryRow(ctx, resolvePublishedContent,
		arg.RequestedLocale,
		arg.FallbackLocale,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
	)
	var i ResolvePublishedContentRow
	err := row.Scan(&i.SourceText, &i.ResolvedText, &i.ResolvedLocale)
	return i, err
}

const resolvePublishedContents = `-- name: ResolvePublishedContents :many
SELECT r.resource_key,
       COALESCE(requested.translated_text, fallback.translated_text, r.source_text) AS resolved_text,
       (CASE
         WHEN requested.translated_text IS NOT NULL THEN $1::text
         WHEN fallback.translated_text IS NOT NULL THEN $2::text
         ELSE r.source_locale
       END)::text AS resolved_locale
FROM localization.content_resources r
LEFT JOIN localization.content_translations requested
  ON requested.workspace_id = r.workspace_id
 AND requested.namespace = r.namespace
 AND requested.resource_key = r.resource_key
 AND requested.locale = $1
 AND requested.status = 'published'
LEFT JOIN localization.content_translations fallback
  ON fallback.workspace_id = r.workspace_id
 AND fallback.namespace = r.namespace
 AND fallback.resource_key = r.resource_key
 AND fallback.locale = $2
 AND fallback.status = 'published'
WHERE r.workspace_id = $3
  AND r.namespace = $4
  AND r.resource_key = ANY($5::text[])
ORDER BY r.resource_key
`

type ResolvePublishedContentsParams struct {
	RequestedLocale string      `json:"requested_locale"`
	FallbackLocale  string      `json:"fallback_locale"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Namespace       string      `json:"namespace"`
	ResourceKeys    []string    `json:"resource_keys"`
}

type ResolvePublishedContentsRow struct {
	ResourceKey    string `json:"resource_key"`
	ResolvedText   string `json:"resolved_text"`
	ResolvedLocale string `json:"resolved_locale"`
}

func (q *Queries) ResolvePublishedContents(ctx context.Context, arg ResolvePublishedContentsParams) ([]ResolvePublishedContentsRow, error) {
	rows, err := q.db.Query(ctx, resolvePublishedContents,
		arg.RequestedLocale,
		arg.FallbackLocale,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ResolvePublishedContentsRow{}
	for rows.Next() {
		var i ResolvePublishedContentsRow
		if err := rows.Scan(&i.ResourceKey, &i.ResolvedText, &i.ResolvedLocale); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateContentResourceSource = `-- name: UpdateContentResourceSource :one
UPDATE localization.content_resources
SET source_locale = $1,
    source_text = $2,
    description = $3,
    placeholders = $4,
    updated_by = $5,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $6
  AND namespace = $7
  AND resource_key = $8
RETURNING workspace_id, namespace, resource_key, source_locale, source_text,
          description, placeholders, version, created_by, updated_by,
          created_at, updated_at
`

type UpdateContentResourceSourceParams struct {
	SourceLocale string      `json:"source_locale"`
	SourceText   string      `json:"source_text"`
	Description  string      `json:"description"`
	Placeholders []string    `json:"placeholders"`
	ActorID      pgtype.UUID `json:"actor_id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	Namespace    string      `json:"namespace"`
	ResourceKey  string      `json:"resource_key"`
}

func (q *Queries) UpdateContentResourceSource(ctx context.Context, arg UpdateContentResourceSourceParams) (LocalizationContentResource, error) {
	row := q.db.QueryRow(ctx, updateContentResourceSource,
		arg.SourceLocale,
		arg.SourceText,
		arg.Description,
		arg.Placeholders,
		arg.ActorID,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
	)
	var i LocalizationContentResource
	err := row.Scan(
		&i.WorkspaceID,
		&i.Namespace,
		&i.ResourceKey,
		&i.SourceLocale,
		&i.SourceText,
		&i.Description,
		&i.Placeholders,
		&i.Version,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateContentTranslation = `-- name: UpdateContentTranslation :one
UPDATE localization.content_translations
SET translated_text = $1,
    status = $2,
    updated_by = $3,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $4
  AND namespace = $5
  AND resource_key = $6
  AND locale = $7
  AND version = $8
RETURNING workspace_id, namespace, resource_key, locale, translated_text,
          status, version, updated_by, created_at, updated_at
`

type UpdateContentTranslationParams struct {
	TranslatedText  string      `json:"translated_text"`
	Status          string      `json:"status"`
	ActorID         pgtype.UUID `json:"actor_id"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	Namespace       string      `json:"namespace"`
	ResourceKey     string      `json:"resource_key"`
	Locale          string      `json:"locale"`
	ExpectedVersion int64       `json:"expected_version"`
}

func (q *Queries) UpdateContentTranslation(ctx context.Context, arg UpdateContentTranslationParams) (LocalizationContentTranslation, error) {
	row := q.db.QueryRow(ctx, updateContentTranslation,
		arg.TranslatedText,
		arg.Status,
		arg.ActorID,
		arg.WorkspaceID,
		arg.Namespace,
		arg.ResourceKey,
		arg.Locale,
		arg.ExpectedVersion,
	)
	var i LocalizationContentTranslation
	err := row.Scan(
		&i.WorkspaceID,
		&i.Namespace,
		&i.ResourceKey,
		&i.Locale,
		&i.TranslatedText,
		&i.Status,
		&i.Version,
		&i.UpdatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWorkspaceLocales = `-- name: UpdateWorkspaceLocales :one
UPDATE tenancy.workspaces
SET default_locale = $1,
    supported_locales = $2,
    version = version + 1,
    updated_at = now()
WHERE id = $3
  AND version = $4
RETURNING default_locale, supported_locales, version, updated_at
`

type UpdateWorkspaceLocalesParams struct {
	DefaultLocale    string      `json:"default_locale"`
	SupportedLocales []string    `json:"supported_locales"`
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ExpectedVersion  int64       `json:"expected_version"`
}

type UpdateWorkspaceLocalesRow struct {
	DefaultLocale    string             `json:"default_locale"`
	SupportedLocales []string           `json:"supported_locales"`
	Version          int64              `json:"version"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWorkspaceLocales(ctx context.Context, arg UpdateWorkspaceLocalesParams) (UpdateWorkspaceLocalesRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceLocales,
		arg.DefaultLocale,
		arg.SupportedLocales,
		arg.WorkspaceID,
		arg.ExpectedVersion,
	)
	var i UpdateWorkspaceLocalesRow
	err := row.Scan(
		&i.DefaultLocale,
		&i.SupportedLocales,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
