// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mailbox.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimMailboxOutgoingDelivery = `-- name: ClaimMailboxOutgoingDelivery :one
UPDATE mailbox.outgoing_messages
SET state = 'sending', attempts = attempts + 1, last_error_code = NULL,
    version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3 AND state IN ('queued', 'failed') AND attempts < 5
RETURNING workspace_id, user_id, account_id, id, internet_message_id, recipients,
          subject, plain_text, state, attempts, last_error_code, sent_at,
          version, created_at, updated_at
`

type ClaimMailboxOutgoingDeliveryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) ClaimMailboxOutgoingDelivery(ctx context.Context, arg ClaimMailboxOutgoingDeliveryParams) (MailboxOutgoingMessage, error) {
	row := q.db.QueryRow(ctx, claimMailboxOutgoingDelivery, arg.WorkspaceID, arg.UserID, arg.ID)
	var i MailboxOutgoingMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.ID,
		&i.InternetMessageID,
		&i.Recipients,
		&i.Subject,
		&i.PlainText,
		&i.State,
		&i.Attempts,
		&i.LastErrorCode,
		&i.SentAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMailboxAccount = `-- name: CreateMailboxAccount :one
INSERT INTO mailbox.accounts (
  workspace_id, id, user_id, display_name, email, username,
  imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
  credential_ciphertext, credential_nonce, key_id, sync_enabled, next_sync_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11,
  $12, $13, $14,
  $15, $16, now()
)
RETURNING workspace_id, id, user_id, display_name, email, username,
          imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
          sync_enabled, sync_state, last_sync_at, next_sync_at, last_error_code,
          version, created_at, updated_at
`

type CreateMailboxAccountParams struct {
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	ID                   pgtype.UUID `json:"id"`
	UserID               pgtype.UUID `json:"user_id"`
	DisplayName          string      `json:"display_name"`
	Email                string      `json:"email"`
	Username             string      `json:"username"`
	ImapHost             string      `json:"imap_host"`
	ImapPort             int32       `json:"imap_port"`
	ImapSecurity         string      `json:"imap_security"`
	SmtpHost             string      `json:"smtp_host"`
	SmtpPort             int32       `json:"smtp_port"`
	SmtpSecurity         string      `json:"smtp_security"`
	CredentialCiphertext []byte      `json:"credential_ciphertext"`
	CredentialNonce      []byte      `json:"credential_nonce"`
	KeyID                string      `json:"key_id"`
	SyncEnabled          bool        `json:"sync_enabled"`
}

type CreateMailboxAccountRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	ImapHost      string             `json:"imap_host"`
	ImapPort      int32              `json:"imap_port"`
	ImapSecurity  string             `json:"imap_security"`
	SmtpHost      string             `json:"smtp_host"`
	SmtpPort      int32              `json:"smtp_port"`
	SmtpSecurity  string             `json:"smtp_security"`
	SyncEnabled   bool               `json:"sync_enabled"`
	SyncState     string             `json:"sync_state"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt    pgtype.Timestamptz `json:"next_sync_at"`
	LastErrorCode *string            `json:"last_error_code"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateMailboxAccount(ctx context.Context, arg CreateMailboxAccountParams) (CreateMailboxAccountRow, error) {
	row := q.db.QueryRow(ctx, createMailboxAccount,
		arg.WorkspaceID,
		arg.ID,
		arg.UserID,
		arg.DisplayName,
		arg.Email,
		arg.Username,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapSecurity,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpSecurity,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyID,
		arg.SyncEnabled,
	)
	var i CreateMailboxAccountRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Username,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SyncEnabled,
		&i.SyncState,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.LastErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createMailboxOutgoing = `-- name: CreateMailboxOutgoing :one
INSERT INTO mailbox.outgoing_messages (
  workspace_id, user_id, account_id, id, internet_message_id, recipients, subject, plain_text
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8
)
RETURNING workspace_id, user_id, account_id, id, internet_message_id, recipients,
          subject, plain_text, state, attempts, last_error_code, sent_at,
          version, created_at, updated_at
`

type CreateMailboxOutgoingParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	UserID            pgtype.UUID `json:"user_id"`
	AccountID         pgtype.UUID `json:"account_id"`
	ID                pgtype.UUID `json:"id"`
	InternetMessageID string      `json:"internet_message_id"`
	Recipients        []byte      `json:"recipients"`
	Subject           string      `json:"subject"`
	PlainText         string      `json:"plain_text"`
}

func (q *Queries) CreateMailboxOutgoing(ctx context.Context, arg CreateMailboxOutgoingParams) (MailboxOutgoingMessage, error) {
	row := q.db.QueryRow(ctx, createMailboxOutgoing,
		arg.WorkspaceID,
		arg.UserID,
		arg.AccountID,
		arg.ID,
		arg.InternetMessageID,
		arg.Recipients,
		arg.Subject,
		arg.PlainText,
	)
	var i MailboxOutgoingMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.ID,
		&i.InternetMessageID,
		&i.Recipients,
		&i.Subject,
		&i.PlainText,
		&i.State,
		&i.Attempts,
		&i.LastErrorCode,
		&i.SentAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteMailboxAccount = `-- name: DeleteMailboxAccount :execrows
DELETE FROM mailbox.accounts
WHERE workspace_id = $1
  AND user_id = $2
  AND id = $3
  AND version = $4
`

type DeleteMailboxAccountParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	UserID          pgtype.UUID `json:"user_id"`
	ID              pgtype.UUID `json:"id"`
	ExpectedVersion int64       `json:"expected_version"`
}

func (q *Queries) DeleteMailboxAccount(ctx context.Context, arg DeleteMailboxAccountParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteMailboxAccount,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueMailboxOutgoingDelivery = `-- name: EnqueueMailboxOutgoingDelivery :exec
INSERT INTO platform.jobs (
  workspace_id, id, kind, schema_version, idempotency_key, payload,
  state, attempts, max_attempts, available_at
) VALUES (
  $1, $2, 'mailbox.outgoing.deliver', 1,
  $3::text,
  jsonb_build_object(
    'outgoingId', $3::text,
    'actorUserId', $4::text
  ),
  'ready', 0, 5, now()
)
ON CONFLICT (workspace_id, kind, idempotency_key) DO NOTHING
`

type EnqueueMailboxOutgoingDeliveryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	JobID       pgtype.UUID `json:"job_id"`
	OutgoingID  string      `json:"outgoing_id"`
	UserID      string      `json:"user_id"`
}

func (q *Queries) EnqueueMailboxOutgoingDelivery(ctx context.Context, arg EnqueueMailboxOutgoingDeliveryParams) error {
	_, err := q.db.Exec(ctx, enqueueMailboxOutgoingDelivery,
		arg.WorkspaceID,
		arg.JobID,
		arg.OutgoingID,
		arg.UserID,
	)
	return err
}

const getMailboxAccount = `-- name: GetMailboxAccount :one
SELECT workspace_id, id, user_id, display_name, email, username,
       imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
       sync_enabled, sync_state, last_sync_at, next_sync_at, last_error_code,
       version, created_at, updated_at
FROM mailbox.accounts
WHERE workspace_id = $1
  AND user_id = $2
  AND id = $3
`

type GetMailboxAccountParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetMailboxAccountRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	ImapHost      string             `json:"imap_host"`
	ImapPort      int32              `json:"imap_port"`
	ImapSecurity  string             `json:"imap_security"`
	SmtpHost      string             `json:"smtp_host"`
	SmtpPort      int32              `json:"smtp_port"`
	SmtpSecurity  string             `json:"smtp_security"`
	SyncEnabled   bool               `json:"sync_enabled"`
	SyncState     string             `json:"sync_state"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt    pgtype.Timestamptz `json:"next_sync_at"`
	LastErrorCode *string            `json:"last_error_code"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetMailboxAccount(ctx context.Context, arg GetMailboxAccountParams) (GetMailboxAccountRow, error) {
	row := q.db.QueryRow(ctx, getMailboxAccount, arg.WorkspaceID, arg.UserID, arg.ID)
	var i GetMailboxAccountRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Username,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SyncEnabled,
		&i.SyncState,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.LastErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailboxAccountSecret = `-- name: GetMailboxAccountSecret :one
SELECT workspace_id, id, user_id, display_name, email, username,
       imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
       credential_ciphertext, credential_nonce, key_id, sync_enabled, sync_state,
       last_sync_at, next_sync_at, last_error_code, version, created_at, updated_at
FROM mailbox.accounts
WHERE workspace_id = $1
  AND user_id = $2
  AND id = $3
`

type GetMailboxAccountSecretParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetMailboxAccountSecret(ctx context.Context, arg GetMailboxAccountSecretParams) (MailboxAccount, error) {
	row := q.db.QueryRow(ctx, getMailboxAccountSecret, arg.WorkspaceID, arg.UserID, arg.ID)
	var i MailboxAccount
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Username,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.CredentialCiphertext,
		&i.CredentialNonce,
		&i.KeyID,
		&i.SyncEnabled,
		&i.SyncState,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.LastErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailboxFolder = `-- name: GetMailboxFolder :one
SELECT workspace_id, user_id, account_id, id, remote_name, display_name,
       delimiter, special_use, sync_enabled, uid_validity, uid_next, highest_uid,
       total_count, unread_count, last_sync_at, created_at, updated_at
FROM mailbox.folders
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3
`

type GetMailboxFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetMailboxFolder(ctx context.Context, arg GetMailboxFolderParams) (MailboxFolder, error) {
	row := q.db.QueryRow(ctx, getMailboxFolder, arg.WorkspaceID, arg.UserID, arg.ID)
	var i MailboxFolder
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.ID,
		&i.RemoteName,
		&i.DisplayName,
		&i.Delimiter,
		&i.SpecialUse,
		&i.SyncEnabled,
		&i.UidValidity,
		&i.UidNext,
		&i.HighestUid,
		&i.TotalCount,
		&i.UnreadCount,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailboxMessage = `-- name: GetMailboxMessage :one
SELECT workspace_id, user_id, account_id, folder_id, id, uid_validity,
       remote_uid, internet_message_id, subject, sender_name, sender_address,
       recipients, sent_at, received_at, flags, size_bytes, snippet,
       has_attachments, body_state, created_at, updated_at
FROM mailbox.messages
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3
`

type GetMailboxMessageParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetMailboxMessage(ctx context.Context, arg GetMailboxMessageParams) (MailboxMessage, error) {
	row := q.db.QueryRow(ctx, getMailboxMessage, arg.WorkspaceID, arg.UserID, arg.ID)
	var i MailboxMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.FolderID,
		&i.ID,
		&i.UidValidity,
		&i.RemoteUid,
		&i.InternetMessageID,
		&i.Subject,
		&i.SenderName,
		&i.SenderAddress,
		&i.Recipients,
		&i.SentAt,
		&i.ReceivedAt,
		&i.Flags,
		&i.SizeBytes,
		&i.Snippet,
		&i.HasAttachments,
		&i.BodyState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMailboxMessageBody = `-- name: GetMailboxMessageBody :one
SELECT plain_text, fetched_at
FROM mailbox.message_bodies
WHERE workspace_id = $1 AND user_id = $2
  AND message_id = $3
`

type GetMailboxMessageBodyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	MessageID   pgtype.UUID `json:"message_id"`
}

type GetMailboxMessageBodyRow struct {
	PlainText string             `json:"plain_text"`
	FetchedAt pgtype.Timestamptz `json:"fetched_at"`
}

func (q *Queries) GetMailboxMessageBody(ctx context.Context, arg GetMailboxMessageBodyParams) (GetMailboxMessageBodyRow, error) {
	row := q.db.QueryRow(ctx, getMailboxMessageBody, arg.WorkspaceID, arg.UserID, arg.MessageID)
	var i GetMailboxMessageBodyRow
	err := row.Scan(&i.PlainText, &i.FetchedAt)
	return i, err
}

const getMailboxOutgoing = `-- name: GetMailboxOutgoing :one
SELECT workspace_id, user_id, account_id, id, internet_message_id, recipients,
       subject, plain_text, state, attempts, last_error_code, sent_at,
       version, created_at, updated_at
FROM mailbox.outgoing_messages
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3
`

type GetMailboxOutgoingParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetMailboxOutgoing(ctx context.Context, arg GetMailboxOutgoingParams) (MailboxOutgoingMessage, error) {
	row := q.db.QueryRow(ctx, getMailboxOutgoing, arg.WorkspaceID, arg.UserID, arg.ID)
	var i MailboxOutgoingMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.ID,
		&i.InternetMessageID,
		&i.Recipients,
		&i.Subject,
		&i.PlainText,
		&i.State,
		&i.Attempts,
		&i.LastErrorCode,
		&i.SentAt,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listMailboxAccounts = `-- name: ListMailboxAccounts :many
SELECT workspace_id, id, user_id, display_name, email, username,
       imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
       sync_enabled, sync_state, last_sync_at, next_sync_at, last_error_code,
       version, created_at, updated_at
FROM mailbox.accounts
WHERE workspace_id = $1
  AND user_id = $2
ORDER BY updated_at DESC, id DESC
LIMIT $3
`

type ListMailboxAccountsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	PageLimit   int32       `json:"page_limit"`
}

type ListMailboxAccountsRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	ImapHost      string             `json:"imap_host"`
	ImapPort      int32              `json:"imap_port"`
	ImapSecurity  string             `json:"imap_security"`
	SmtpHost      string             `json:"smtp_host"`
	SmtpPort      int32              `json:"smtp_port"`
	SmtpSecurity  string             `json:"smtp_security"`
	SyncEnabled   bool               `json:"sync_enabled"`
	SyncState     string             `json:"sync_state"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt    pgtype.Timestamptz `json:"next_sync_at"`
	LastErrorCode *string            `json:"last_error_code"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListMailboxAccounts(ctx context.Context, arg ListMailboxAccountsParams) ([]ListMailboxAccountsRow, error) {
	rows, err := q.db.Query(ctx, listMailboxAccounts, arg.WorkspaceID, arg.UserID, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMailboxAccountsRow{}
	for rows.Next() {
		var i ListMailboxAccountsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.UserID,
			&i.DisplayName,
			&i.Email,
			&i.Username,
			&i.ImapHost,
			&i.ImapPort,
			&i.ImapSecurity,
			&i.SmtpHost,
			&i.SmtpPort,
			&i.SmtpSecurity,
			&i.SyncEnabled,
			&i.SyncState,
			&i.LastSyncAt,
			&i.NextSyncAt,
			&i.LastErrorCode,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxFolders = `-- name: ListMailboxFolders :many
SELECT workspace_id, user_id, account_id, id, remote_name, display_name,
       delimiter, special_use, sync_enabled, uid_validity, uid_next, highest_uid,
       total_count, unread_count, last_sync_at, created_at, updated_at
FROM mailbox.folders
WHERE workspace_id = $1 AND user_id = $2
  AND account_id = $3
ORDER BY CASE special_use WHEN 'inbox' THEN 0 WHEN 'sent' THEN 1 WHEN 'drafts' THEN 2
  WHEN 'archive' THEN 3 WHEN 'trash' THEN 4 WHEN 'junk' THEN 5 ELSE 6 END,
  display_name, id
`

type ListMailboxFoldersParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
}

func (q *Queries) ListMailboxFolders(ctx context.Context, arg ListMailboxFoldersParams) ([]MailboxFolder, error) {
	rows, err := q.db.Query(ctx, listMailboxFolders, arg.WorkspaceID, arg.UserID, arg.AccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailboxFolder{}
	for rows.Next() {
		var i MailboxFolder
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.AccountID,
			&i.ID,
			&i.RemoteName,
			&i.DisplayName,
			&i.Delimiter,
			&i.SpecialUse,
			&i.SyncEnabled,
			&i.UidValidity,
			&i.UidNext,
			&i.HighestUid,
			&i.TotalCount,
			&i.UnreadCount,
			&i.LastSyncAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMailboxMessages = `-- name: ListMailboxMessages :many
SELECT workspace_id, user_id, account_id, folder_id, id, uid_validity,
       remote_uid, internet_message_id, subject, sender_name, sender_address,
       recipients, sent_at, received_at, flags, size_bytes, snippet,
       has_attachments, body_state, created_at, updated_at
FROM mailbox.messages
WHERE workspace_id = $1 AND user_id = $2
  AND folder_id = $3
  AND ($4::timestamptz IS NULL
       OR (received_at, id) < ($4::timestamptz, $5::uuid))
ORDER BY received_at DESC, id DESC
LIMIT $6
`

type ListMailboxMessagesParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	FolderID    pgtype.UUID        `json:"folder_id"`
	CursorTime  pgtype.Timestamptz `json:"cursor_time"`
	CursorID    pgtype.UUID        `json:"cursor_id"`
	PageLimit   int32              `json:"page_limit"`
}

func (q *Queries) ListMailboxMessages(ctx context.Context, arg ListMailboxMessagesParams) ([]MailboxMessage, error) {
	rows, err := q.db.Query(ctx, listMailboxMessages,
		arg.WorkspaceID,
		arg.UserID,
		arg.FolderID,
		arg.CursorTime,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MailboxMessage{}
	for rows.Next() {
		var i MailboxMessage
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.UserID,
			&i.AccountID,
			&i.FolderID,
			&i.ID,
			&i.UidValidity,
			&i.RemoteUid,
			&i.InternetMessageID,
			&i.Subject,
			&i.SenderName,
			&i.SenderAddress,
			&i.Recipients,
			&i.SentAt,
			&i.ReceivedAt,
			&i.Flags,
			&i.SizeBytes,
			&i.Snippet,
			&i.HasAttachments,
			&i.BodyState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markMailboxOutgoingFailed = `-- name: MarkMailboxOutgoingFailed :execrows
UPDATE mailbox.outgoing_messages
SET state = CASE WHEN $1::boolean THEN 'dead' ELSE 'failed' END,
    last_error_code = $2,
    version = version + 1, updated_at = now()
WHERE workspace_id = $3 AND user_id = $4
  AND id = $5 AND state = 'sending'
`

type MarkMailboxOutgoingFailedParams struct {
	Terminal    bool        `json:"terminal"`
	ErrorCode   *string     `json:"error_code"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkMailboxOutgoingFailed(ctx context.Context, arg MarkMailboxOutgoingFailedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMailboxOutgoingFailed,
		arg.Terminal,
		arg.ErrorCode,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMailboxOutgoingSent = `-- name: MarkMailboxOutgoingSent :execrows
UPDATE mailbox.outgoing_messages
SET state = 'sent', sent_at = now(), last_error_code = NULL,
    version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3 AND state = 'sending'
`

type MarkMailboxOutgoingSentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkMailboxOutgoingSent(ctx context.Context, arg MarkMailboxOutgoingSentParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMailboxOutgoingSent, arg.WorkspaceID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markMailboxSyncFailed = `-- name: MarkMailboxSyncFailed :exec
UPDATE mailbox.accounts
SET sync_state = 'error', next_sync_at = now() + interval '5 minutes',
    last_error_code = $1, updated_at = now()
WHERE workspace_id = $2 AND user_id = $3 AND id = $4
`

type MarkMailboxSyncFailedParams struct {
	ErrorCode   *string     `json:"error_code"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkMailboxSyncFailed(ctx context.Context, arg MarkMailboxSyncFailedParams) error {
	_, err := q.db.Exec(ctx, markMailboxSyncFailed,
		arg.ErrorCode,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
	)
	return err
}

const markMailboxSyncFinished = `-- name: MarkMailboxSyncFinished :exec
UPDATE mailbox.accounts
SET sync_state = 'ready', last_sync_at = now(), next_sync_at = now() + interval '2 minutes',
    last_error_code = NULL, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2 AND id = $3
`

type MarkMailboxSyncFinishedParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkMailboxSyncFinished(ctx context.Context, arg MarkMailboxSyncFinishedParams) error {
	_, err := q.db.Exec(ctx, markMailboxSyncFinished, arg.WorkspaceID, arg.UserID, arg.ID)
	return err
}

const markMailboxSyncStarted = `-- name: MarkMailboxSyncStarted :execrows
UPDATE mailbox.accounts
SET sync_state = 'syncing', last_error_code = NULL, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
  AND id = $3 AND sync_enabled
  AND (sync_state <> 'syncing' OR updated_at < now() - interval '2 minutes')
`

type MarkMailboxSyncStartedParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkMailboxSyncStarted(ctx context.Context, arg MarkMailboxSyncStartedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markMailboxSyncStarted, arg.WorkspaceID, arg.UserID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const replaceMailboxCredential = `-- name: ReplaceMailboxCredential :execrows
UPDATE mailbox.accounts
SET credential_ciphertext = $1,
    credential_nonce = $2,
    key_id = $3,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $4
  AND user_id = $5
  AND id = $6
  AND version = $7
`

type ReplaceMailboxCredentialParams struct {
	CredentialCiphertext []byte      `json:"credential_ciphertext"`
	CredentialNonce      []byte      `json:"credential_nonce"`
	KeyID                string      `json:"key_id"`
	WorkspaceID          pgtype.UUID `json:"workspace_id"`
	UserID               pgtype.UUID `json:"user_id"`
	ID                   pgtype.UUID `json:"id"`
	ExpectedVersion      int64       `json:"expected_version"`
}

func (q *Queries) ReplaceMailboxCredential(ctx context.Context, arg ReplaceMailboxCredentialParams) (int64, error) {
	result, err := q.db.Exec(ctx, replaceMailboxCredential,
		arg.CredentialCiphertext,
		arg.CredentialNonce,
		arg.KeyID,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
		arg.ExpectedVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const resetMailboxFolderForUIDValidity = `-- name: ResetMailboxFolderForUIDValidity :exec
DELETE FROM mailbox.messages
WHERE workspace_id = $1 AND user_id = $2
  AND account_id = $3 AND folder_id = $4
  AND uid_validity <> $5
`

type ResetMailboxFolderForUIDValidityParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	FolderID    pgtype.UUID `json:"folder_id"`
	UidValidity int64       `json:"uid_validity"`
}

func (q *Queries) ResetMailboxFolderForUIDValidity(ctx context.Context, arg ResetMailboxFolderForUIDValidityParams) error {
	_, err := q.db.Exec(ctx, resetMailboxFolderForUIDValidity,
		arg.WorkspaceID,
		arg.UserID,
		arg.AccountID,
		arg.FolderID,
		arg.UidValidity,
	)
	return err
}

const storeMailboxMessageBody = `-- name: StoreMailboxMessageBody :exec
WITH stored AS (
  INSERT INTO mailbox.message_bodies (workspace_id, user_id, account_id, message_id, plain_text)
  VALUES ($1, $2, $4, $3, $5)
  ON CONFLICT (workspace_id, message_id) DO UPDATE
    SET plain_text = EXCLUDED.plain_text, fetched_at = now()
)
UPDATE mailbox.messages AS message SET body_state = 'ready', updated_at = now()
WHERE message.workspace_id = $1 AND message.user_id = $2
  AND message.id = $3
`

type StoreMailboxMessageBodyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	MessageID   pgtype.UUID `json:"message_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	PlainText   string      `json:"plain_text"`
}

func (q *Queries) StoreMailboxMessageBody(ctx context.Context, arg StoreMailboxMessageBodyParams) error {
	_, err := q.db.Exec(ctx, storeMailboxMessageBody,
		arg.WorkspaceID,
		arg.UserID,
		arg.MessageID,
		arg.AccountID,
		arg.PlainText,
	)
	return err
}

const updateMailboxAccount = `-- name: UpdateMailboxAccount :one
UPDATE mailbox.accounts
SET display_name = $1,
    email = $2,
    username = $3,
    imap_host = $4,
    imap_port = $5,
    imap_security = $6,
    smtp_host = $7,
    smtp_port = $8,
    smtp_security = $9,
    sync_enabled = $10,
    sync_state = CASE WHEN $10::boolean THEN 'pending' ELSE 'disabled' END,
    next_sync_at = CASE WHEN $10::boolean THEN now() ELSE NULL END,
    last_error_code = NULL,
    version = version + 1,
    updated_at = now()
WHERE workspace_id = $11
  AND user_id = $12
  AND id = $13
  AND version = $14
RETURNING workspace_id, id, user_id, display_name, email, username,
          imap_host, imap_port, imap_security, smtp_host, smtp_port, smtp_security,
          sync_enabled, sync_state, last_sync_at, next_sync_at, last_error_code,
          version, created_at, updated_at
`

type UpdateMailboxAccountParams struct {
	DisplayName     string      `json:"display_name"`
	Email           string      `json:"email"`
	Username        string      `json:"username"`
	ImapHost        string      `json:"imap_host"`
	ImapPort        int32       `json:"imap_port"`
	ImapSecurity    string      `json:"imap_security"`
	SmtpHost        string      `json:"smtp_host"`
	SmtpPort        int32       `json:"smtp_port"`
	SmtpSecurity    string      `json:"smtp_security"`
	SyncEnabled     bool        `json:"sync_enabled"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	UserID          pgtype.UUID `json:"user_id"`
	ID              pgtype.UUID `json:"id"`
	ExpectedVersion int64       `json:"expected_version"`
}

type UpdateMailboxAccountRow struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	UserID        pgtype.UUID        `json:"user_id"`
	DisplayName   string             `json:"display_name"`
	Email         string             `json:"email"`
	Username      string             `json:"username"`
	ImapHost      string             `json:"imap_host"`
	ImapPort      int32              `json:"imap_port"`
	ImapSecurity  string             `json:"imap_security"`
	SmtpHost      string             `json:"smtp_host"`
	SmtpPort      int32              `json:"smtp_port"`
	SmtpSecurity  string             `json:"smtp_security"`
	SyncEnabled   bool               `json:"sync_enabled"`
	SyncState     string             `json:"sync_state"`
	LastSyncAt    pgtype.Timestamptz `json:"last_sync_at"`
	NextSyncAt    pgtype.Timestamptz `json:"next_sync_at"`
	LastErrorCode *string            `json:"last_error_code"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateMailboxAccount(ctx context.Context, arg UpdateMailboxAccountParams) (UpdateMailboxAccountRow, error) {
	row := q.db.QueryRow(ctx, updateMailboxAccount,
		arg.DisplayName,
		arg.Email,
		arg.Username,
		arg.ImapHost,
		arg.ImapPort,
		arg.ImapSecurity,
		arg.SmtpHost,
		arg.SmtpPort,
		arg.SmtpSecurity,
		arg.SyncEnabled,
		arg.WorkspaceID,
		arg.UserID,
		arg.ID,
		arg.ExpectedVersion,
	)
	var i UpdateMailboxAccountRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.DisplayName,
		&i.Email,
		&i.Username,
		&i.ImapHost,
		&i.ImapPort,
		&i.ImapSecurity,
		&i.SmtpHost,
		&i.SmtpPort,
		&i.SmtpSecurity,
		&i.SyncEnabled,
		&i.SyncState,
		&i.LastSyncAt,
		&i.NextSyncAt,
		&i.LastErrorCode,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateMailboxFolderHighWater = `-- name: UpdateMailboxFolderHighWater :exec
UPDATE mailbox.folders
SET highest_uid = GREATEST(highest_uid, $1),
    uid_validity = $2, uid_next = $3,
    last_sync_at = now(), updated_at = now()
WHERE workspace_id = $4 AND user_id = $5
  AND account_id = $6 AND id = $7
`

type UpdateMailboxFolderHighWaterParams struct {
	HighestUid  int64       `json:"highest_uid"`
	UidValidity *int64      `json:"uid_validity"`
	UidNext     *int64      `json:"uid_next"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateMailboxFolderHighWater(ctx context.Context, arg UpdateMailboxFolderHighWaterParams) error {
	_, err := q.db.Exec(ctx, updateMailboxFolderHighWater,
		arg.HighestUid,
		arg.UidValidity,
		arg.UidNext,
		arg.WorkspaceID,
		arg.UserID,
		arg.AccountID,
		arg.ID,
	)
	return err
}

const upsertMailboxFolder = `-- name: UpsertMailboxFolder :one
INSERT INTO mailbox.folders (
  workspace_id, user_id, account_id, id, remote_name, display_name, delimiter,
  special_use, uid_validity, uid_next, total_count, unread_count, last_sync_at
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, now()
)
ON CONFLICT (workspace_id, user_id, account_id, remote_name) DO UPDATE
SET display_name = EXCLUDED.display_name, delimiter = EXCLUDED.delimiter,
    special_use = EXCLUDED.special_use, uid_validity = EXCLUDED.uid_validity,
    uid_next = EXCLUDED.uid_next, total_count = EXCLUDED.total_count,
    unread_count = EXCLUDED.unread_count, last_sync_at = now(), updated_at = now()
RETURNING workspace_id, user_id, account_id, id, remote_name, display_name,
          delimiter, special_use, sync_enabled, uid_validity, uid_next, highest_uid,
          total_count, unread_count, last_sync_at, created_at, updated_at
`

type UpsertMailboxFolderParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
	AccountID   pgtype.UUID `json:"account_id"`
	ID          pgtype.UUID `json:"id"`
	RemoteName  string      `json:"remote_name"`
	DisplayName string      `json:"display_name"`
	Delimiter   *string     `json:"delimiter"`
	SpecialUse  *string     `json:"special_use"`
	UidValidity *int64      `json:"uid_validity"`
	UidNext     *int64      `json:"uid_next"`
	TotalCount  int32       `json:"total_count"`
	UnreadCount int32       `json:"unread_count"`
}

func (q *Queries) UpsertMailboxFolder(ctx context.Context, arg UpsertMailboxFolderParams) (MailboxFolder, error) {
	row := q.db.QueryRow(ctx, upsertMailboxFolder,
		arg.WorkspaceID,
		arg.UserID,
		arg.AccountID,
		arg.ID,
		arg.RemoteName,
		arg.DisplayName,
		arg.Delimiter,
		arg.SpecialUse,
		arg.UidValidity,
		arg.UidNext,
		arg.TotalCount,
		arg.UnreadCount,
	)
	var i MailboxFolder
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.ID,
		&i.RemoteName,
		&i.DisplayName,
		&i.Delimiter,
		&i.SpecialUse,
		&i.SyncEnabled,
		&i.UidValidity,
		&i.UidNext,
		&i.HighestUid,
		&i.TotalCount,
		&i.UnreadCount,
		&i.LastSyncAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertMailboxMessage = `-- name: UpsertMailboxMessage :one
INSERT INTO mailbox.messages (
  workspace_id, user_id, account_id, folder_id, id, uid_validity, remote_uid,
  internet_message_id, subject, sender_name, sender_address, recipients,
  sent_at, received_at, flags, size_bytes, snippet, has_attachments
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7, $8,
  $9, $10, $11, $12,
  $13, $14, $15, $16,
  $17, $18
)
ON CONFLICT (workspace_id, user_id, account_id, folder_id, uid_validity, remote_uid) DO UPDATE
SET internet_message_id = EXCLUDED.internet_message_id, subject = EXCLUDED.subject,
    sender_name = EXCLUDED.sender_name, sender_address = EXCLUDED.sender_address,
    recipients = EXCLUDED.recipients, sent_at = EXCLUDED.sent_at,
    received_at = EXCLUDED.received_at, flags = EXCLUDED.flags,
    size_bytes = EXCLUDED.size_bytes, snippet = EXCLUDED.snippet,
    has_attachments = EXCLUDED.has_attachments, updated_at = now()
RETURNING workspace_id, user_id, account_id, folder_id, id, uid_validity,
          remote_uid, internet_message_id, subject, sender_name, sender_address,
          recipients, sent_at, received_at, flags, size_bytes, snippet,
          has_attachments, body_state, created_at, updated_at
`

type UpsertMailboxMessageParams struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	UserID            pgtype.UUID        `json:"user_id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	FolderID          pgtype.UUID        `json:"folder_id"`
	ID                pgtype.UUID        `json:"id"`
	UidValidity       int64              `json:"uid_validity"`
	RemoteUid         int64              `json:"remote_uid"`
	InternetMessageID *string            `json:"internet_message_id"`
	Subject           string             `json:"subject"`
	SenderName        string             `json:"sender_name"`
	SenderAddress     string             `json:"sender_address"`
	Recipients        []byte             `json:"recipients"`
	SentAt            pgtype.Timestamptz `json:"sent_at"`
	ReceivedAt        pgtype.Timestamptz `json:"received_at"`
	Flags             []string           `json:"flags"`
	SizeBytes         int64              `json:"size_bytes"`
	Snippet           string             `json:"snippet"`
	HasAttachments    bool               `json:"has_attachments"`
}

func (q *Queries) UpsertMailboxMessage(ctx context.Context, arg UpsertMailboxMessageParams) (MailboxMessage, error) {
	row := q.db.QueryRow(ctx, upsertMailboxMessage,
		arg.WorkspaceID,
		arg.UserID,
		arg.AccountID,
		arg.FolderID,
		arg.ID,
		arg.UidValidity,
		arg.RemoteUid,
		arg.InternetMessageID,
		arg.Subject,
		arg.SenderName,
		arg.SenderAddress,
		arg.Recipients,
		arg.SentAt,
		arg.ReceivedAt,
		arg.Flags,
		arg.SizeBytes,
		arg.Snippet,
		arg.HasAttachments,
	)
	var i MailboxMessage
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.AccountID,
		&i.FolderID,
		&i.ID,
		&i.UidValidity,
		&i.RemoteUid,
		&i.InternetMessageID,
		&i.Subject,
		&i.SenderName,
		&i.SenderAddress,
		&i.Recipients,
		&i.SentAt,
		&i.ReceivedAt,
		&i.Flags,
		&i.SizeBytes,
		&i.Snippet,
		&i.HasAttachments,
		&i.BodyState,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
