// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivitiesActivity struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ID                pgtype.UUID        `json:"id"`
	ActivityType      string             `json:"activity_type"`
	Title             string             `json:"title"`
	Body              *string            `json:"body"`
	RelatedType       *string            `json:"related_type"`
	RelatedID         pgtype.UUID        `json:"related_id"`
	AssigneeUserID    pgtype.UUID        `json:"assignee_user_id"`
	Status            string             `json:"status"`
	Priority          string             `json:"priority"`
	DueAt             pgtype.Timestamptz `json:"due_at"`
	OccurredAt        pgtype.Timestamptz `json:"occurred_at"`
	RecurrenceRule    *string            `json:"recurrence_rule"`
	CompletedAt       pgtype.Timestamptz `json:"completed_at"`
	CreatedBy         pgtype.UUID        `json:"created_by"`
	Version           int64              `json:"version"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	SystemTitleKey    *string            `json:"system_title_key"`
	SystemTitleParams []byte             `json:"system_title_params"`
	EndsAt            pgtype.Timestamptz `json:"ends_at"`
	Location          *string            `json:"location"`
	VisibilityScope   string             `json:"visibility_scope"`
	ScopeDepartmentID pgtype.UUID        `json:"scope_department_id"`
	ScopeUserID       pgtype.UUID        `json:"scope_user_id"`
}

type ActivitiesActivityAssignment struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	ActivityID     pgtype.UUID        `json:"activity_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ActivitiesComment struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	ActivityID       pgtype.UUID        `json:"activity_id"`
	AuthorUserID     pgtype.UUID        `json:"author_user_id"`
	Body             string             `json:"body"`
	MentionedUserIds []pgtype.UUID      `json:"mentioned_user_ids"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          int64              `json:"version"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type ActivitiesReminder struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ID              pgtype.UUID        `json:"id"`
	ActivityID      pgtype.UUID        `json:"activity_id"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	RemindAt        pgtype.Timestamptz `json:"remind_at"`
	DeliveredAt     pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Channel         string             `json:"channel"`
	CancelledAt     pgtype.Timestamptz `json:"cancelled_at"`
	Version         int64              `json:"version"`
}

type AuditEvent struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RequestID   string             `json:"request_id"`
	Summary     []byte             `json:"summary"`
	IpAddress   *netip.Addr        `json:"ip_address"`
	UserAgent   string             `json:"user_agent"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

type AutomationActionExecution struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ExecutionID    pgtype.UUID        `json:"execution_id"`
	ActionIndex    int32              `json:"action_index"`
	ActionType     string             `json:"action_type"`
	IdempotencyKey string             `json:"idempotency_key"`
	State          string             `json:"state"`
	Result         []byte             `json:"result"`
	LastErrorCode  *string            `json:"last_error_code"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type AutomationExecution struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	RuleID        pgtype.UUID        `json:"rule_id"`
	EventID       pgtype.UUID        `json:"event_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Depth         int32              `json:"depth"`
	State         string             `json:"state"`
	Attempts      int32              `json:"attempts"`
	Result        []byte             `json:"result"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	TriggerType   string             `json:"trigger_type"`
	EventPayload  []byte             `json:"event_payload"`
	StartedAt     pgtype.Timestamptz `json:"started_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	LastErrorCode *string            `json:"last_error_code"`
}

type AutomationHourlyUsage struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RuleID      pgtype.UUID        `json:"rule_id"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	Used        int32              `json:"used"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type AutomationOverdueTaskTick struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ActivityID      pgtype.UUID        `json:"activity_id"`
	ActivityVersion int64              `json:"activity_version"`
	EventID         pgtype.UUID        `json:"event_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type AutomationRule struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	TriggerType      string             `json:"trigger_type"`
	Conditions       []byte             `json:"conditions"`
	Actions          []byte             `json:"actions"`
	Enabled          bool               `json:"enabled"`
	RateLimitPerHour int32              `json:"rate_limit_per_hour"`
	Version          int64              `json:"version"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	EntityType       string             `json:"entity_type"`
}

type AutomationScheduleTick struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	BucketStart pgtype.Timestamptz `json:"bucket_start"`
	EventID     pgtype.UUID        `json:"event_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CollaborationCall struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	RoomName       string             `json:"room_name"`
	CallKind       string             `json:"call_kind"`
	State          string             `json:"state"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	EndedAt        pgtype.Timestamptz `json:"ended_at"`
	Version        int64              `json:"version"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type CollaborationCallParticipant struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	CallID      pgtype.UUID        `json:"call_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	State       string             `json:"state"`
	InvitedAt   pgtype.Timestamptz `json:"invited_at"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	LeftAt      pgtype.Timestamptz `json:"left_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CollaborationConversation struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	ConversationType string             `json:"conversation_type"`
	Title            string             `json:"title"`
	DirectKey        *string            `json:"direct_key"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	LastMessageAt    pgtype.Timestamptz `json:"last_message_at"`
	Version          int64              `json:"version"`
	ArchivedAt       pgtype.Timestamptz `json:"archived_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CollaborationConversationMember struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	UserID         pgtype.UUID        `json:"user_id"`
	MemberRole     string             `json:"member_role"`
	Muted          bool               `json:"muted"`
	LastReadAt     pgtype.Timestamptz `json:"last_read_at"`
	JoinedAt       pgtype.Timestamptz `json:"joined_at"`
}

type CollaborationMessage struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	ConversationID   pgtype.UUID        `json:"conversation_id"`
	SenderUserID     pgtype.UUID        `json:"sender_user_id"`
	MessageKind      string             `json:"message_kind"`
	Body             string             `json:"body"`
	ReplyToMessageID pgtype.UUID        `json:"reply_to_message_id"`
	EditedAt         pgtype.Timestamptz `json:"edited_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

type CollaborationMessageReaction struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	MessageID   pgtype.UUID        `json:"message_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Emoji       string             `json:"emoji"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CollaborationPinnedMessage struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ConversationID pgtype.UUID        `json:"conversation_id"`
	MessageID      pgtype.UUID        `json:"message_id"`
	PinnedBy       pgtype.UUID        `json:"pinned_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type CustomersCompany struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Domain           *string            `json:"domain"`
	DomainNormalized *string            `json:"domain_normalized"`
	Industry         *string            `json:"industry"`
	Status           string             `json:"status"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	TeamID           pgtype.UUID        `json:"team_id"`
	Address          []byte             `json:"address"`
	CustomFields     []byte             `json:"custom_fields"`
	Version          int64              `json:"version"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy        pgtype.UUID        `json:"deleted_by"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type CustomersContact struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ID              pgtype.UUID        `json:"id"`
	FirstName       string             `json:"first_name"`
	LastName        string             `json:"last_name"`
	DisplayName     string             `json:"display_name"`
	Email           *string            `json:"email"`
	EmailNormalized *string            `json:"email_normalized"`
	Phone           *string            `json:"phone"`
	PhoneNormalized *string            `json:"phone_normalized"`
	JobTitle        *string            `json:"job_title"`
	CompanyID       pgtype.UUID        `json:"company_id"`
	OwnerUserID     pgtype.UUID        `json:"owner_user_id"`
	TeamID          pgtype.UUID        `json:"team_id"`
	Source          *string            `json:"source"`
	Status          string             `json:"status"`
	Address         []byte             `json:"address"`
	CustomFields    []byte             `json:"custom_fields"`
	LastContactedAt pgtype.Timestamptz `json:"last_contacted_at"`
	NextActivityAt  pgtype.Timestamptz `json:"next_activity_at"`
	Version         int64              `json:"version"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
	DeletedBy       pgtype.UUID        `json:"deleted_by"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type CustomersContactTag struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	TagID       pgtype.UUID        `json:"tag_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type CustomersCustomFieldDefinition struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	EntityType    string             `json:"entity_type"`
	FieldKey      string             `json:"field_key"`
	Label         string             `json:"label"`
	ValueType     string             `json:"value_type"`
	Validation    []byte             `json:"validation"`
	Options       []byte             `json:"options"`
	SchemaVersion int32              `json:"schema_version"`
	Version       int64              `json:"version"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CustomersCustomFieldValue struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	DefinitionID  pgtype.UUID        `json:"definition_id"`
	EntityType    string             `json:"entity_type"`
	EntityID      pgtype.UUID        `json:"entity_id"`
	Value         []byte             `json:"value"`
	SchemaVersion int32              `json:"schema_version"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type CustomersImportError struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ImportSessionID pgtype.UUID        `json:"import_session_id"`
	RowNumber       int32              `json:"row_number"`
	ErrorCode       string             `json:"error_code"`
	FieldKey        *string            `json:"field_key"`
	SafeValue       *string            `json:"safe_value"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type CustomersImportRow struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ImportSessionID pgtype.UUID        `json:"import_session_id"`
	RowNumber       int32              `json:"row_number"`
	SourceValues    []byte             `json:"source_values"`
	State           string             `json:"state"`
	CreatedEntityID pgtype.UUID        `json:"created_entity_id"`
	ProcessedAt     pgtype.Timestamptz `json:"processed_at"`
}

type CustomersImportSession struct {
	WorkspaceID             pgtype.UUID        `json:"workspace_id"`
	ID                      pgtype.UUID        `json:"id"`
	ActorUserID             pgtype.UUID        `json:"actor_user_id"`
	EntityType              string             `json:"entity_type"`
	Status                  string             `json:"status"`
	Mapping                 []byte             `json:"mapping"`
	TotalRows               int32              `json:"total_rows"`
	ProcessedRows           int32              `json:"processed_rows"`
	ErrorRows               int32              `json:"error_rows"`
	ErrorReportAttachmentID pgtype.UUID        `json:"error_report_attachment_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz `json:"updated_at"`
	SourceHeaders           []byte             `json:"source_headers"`
	CreatedRows             int32              `json:"created_rows"`
	StartedAt               pgtype.Timestamptz `json:"started_at"`
	CompletedAt             pgtype.Timestamptz `json:"completed_at"`
}

type CustomersRecordMerge struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	EntityType    string             `json:"entity_type"`
	SourceID      pgtype.UUID        `json:"source_id"`
	TargetID      pgtype.UUID        `json:"target_id"`
	ActorUserID   pgtype.UUID        `json:"actor_user_id"`
	SourceVersion int64              `json:"source_version"`
	TargetVersion int64              `json:"target_version"`
	MergedAt      pgtype.Timestamptz `json:"merged_at"`
}

type CustomersSavedView struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	OwnerUserID pgtype.UUID        `json:"owner_user_id"`
	EntityType  string             `json:"entity_type"`
	Name        string             `json:"name"`
	Definition  []byte             `json:"definition"`
	IsShared    bool               `json:"is_shared"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type CustomersTag struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Color       string             `json:"color"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	Version     int64              `json:"version"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type FilesAttachment struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	StorageBackend string             `json:"storage_backend"`
	StorageKey     string             `json:"storage_key"`
	DisplayName    string             `json:"display_name"`
	MediaType      string             `json:"media_type"`
	SizeBytes      int64              `json:"size_bytes"`
	ChecksumSha256 []byte             `json:"checksum_sha256"`
	ScanState      string             `json:"scan_state"`
	UploadedBy     pgtype.UUID        `json:"uploaded_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	DeletedAt      pgtype.Timestamptz `json:"deleted_at"`
}

type IdentityMfaConfiguration struct {
	UserID                  pgtype.UUID        `json:"user_id"`
	SecretCiphertext        []byte             `json:"secret_ciphertext"`
	SecretNonce             []byte             `json:"secret_nonce"`
	KeyID                   string             `json:"key_id"`
	EnabledAt               pgtype.Timestamptz `json:"enabled_at"`
	LastAcceptedStep        *int64             `json:"last_accepted_step"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	PendingSecretCiphertext []byte             `json:"pending_secret_ciphertext"`
	PendingSecretNonce      []byte             `json:"pending_secret_nonce"`
	PendingKeyID            *string            `json:"pending_key_id"`
	PendingCreatedAt        pgtype.Timestamptz `json:"pending_created_at"`
}

type IdentityMfaLoginChallenge struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	TokenHash  []byte             `json:"token_hash"`
	UserAgent  string             `json:"user_agent"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	Attempts   int32              `json:"attempts"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

type IdentityPasswordResetToken struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	TokenHash []byte             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdentityRecoveryCode struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	CodeHash  []byte             `json:"code_hash"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type IdentitySession struct {
	ID             pgtype.UUID        `json:"id"`
	UserID         pgtype.UUID        `json:"user_id"`
	TokenHash      []byte             `json:"token_hash"`
	CsrfHash       []byte             `json:"csrf_hash"`
	SessionVersion int64              `json:"session_version"`
	UserAgent      string             `json:"user_agent"`
	IpAddress      *netip.Addr        `json:"ip_address"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	LastSeenAt     pgtype.Timestamptz `json:"last_seen_at"`
	RevokedAt      pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type IdentityUser struct {
	ID                pgtype.UUID        `json:"id"`
	Email             string             `json:"email"`
	EmailNormalized   string             `json:"email_normalized"`
	DisplayName       string             `json:"display_name"`
	PasswordHash      string             `json:"password_hash"`
	PreferredLocale   string             `json:"preferred_locale"`
	Status            string             `json:"status"`
	SessionVersion    int64              `json:"session_version"`
	FailedLoginCount  int32              `json:"failed_login_count"`
	LockedUntil       pgtype.Timestamptz `json:"locked_until"`
	PasswordChangedAt pgtype.Timestamptz `json:"password_changed_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationsApiKey struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	KeyPrefix   string             `json:"key_prefix"`
	SecretHash  []byte             `json:"secret_hash"`
	Name        string             `json:"name"`
	Scopes      []string           `json:"scopes"`
	CreatedBy   pgtype.UUID        `json:"created_by"`
	LastUsedAt  pgtype.Timestamptz `json:"last_used_at"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	RevokedAt   pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type IntegrationsWebhookDelivery struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	SubscriptionID   pgtype.UUID        `json:"subscription_id"`
	EventID          pgtype.UUID        `json:"event_id"`
	Status           string             `json:"status"`
	Attempts         int32              `json:"attempts"`
	NextAttemptAt    pgtype.Timestamptz `json:"next_attempt_at"`
	ResponseStatus   *int32             `json:"response_status"`
	ResponseSummary  *string            `json:"response_summary"`
	DeliveredAt      pgtype.Timestamptz `json:"delivered_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	RequestTimestamp *int64             `json:"request_timestamp"`
	SignatureVersion int32              `json:"signature_version"`
	LastErrorCode    *string            `json:"last_error_code"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type IntegrationsWebhookSubscription struct {
	WorkspaceID              pgtype.UUID        `json:"workspace_id"`
	ID                       pgtype.UUID        `json:"id"`
	Url                      string             `json:"url"`
	EventTypes               []string           `json:"event_types"`
	SecretCiphertext         []byte             `json:"secret_ciphertext"`
	SecretNonce              []byte             `json:"secret_nonce"`
	KeyID                    string             `json:"key_id"`
	PreviousSecretCiphertext []byte             `json:"previous_secret_ciphertext"`
	PreviousSecretExpiresAt  pgtype.Timestamptz `json:"previous_secret_expires_at"`
	Enabled                  bool               `json:"enabled"`
	Version                  int64              `json:"version"`
	CreatedBy                pgtype.UUID        `json:"created_by"`
	CreatedAt                pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                pgtype.Timestamptz `json:"updated_at"`
	PreviousSecretNonce      []byte             `json:"previous_secret_nonce"`
	PreviousKeyID            *string            `json:"previous_key_id"`
	SecretVersion            int32              `json:"secret_version"`
	TimeoutSeconds           int32              `json:"timeout_seconds"`
	MaxAttempts              int32              `json:"max_attempts"`
}

type LocalizationContentResource struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	Namespace    string             `json:"namespace"`
	ResourceKey  string             `json:"resource_key"`
	SourceLocale string             `json:"source_locale"`
	SourceText   string             `json:"source_text"`
	Description  string             `json:"description"`
	Placeholders []string           `json:"placeholders"`
	Version      int64              `json:"version"`
	CreatedBy    pgtype.UUID        `json:"created_by"`
	UpdatedBy    pgtype.UUID        `json:"updated_by"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type LocalizationContentTranslation struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Namespace      string             `json:"namespace"`
	ResourceKey    string             `json:"resource_key"`
	Locale         string             `json:"locale"`
	TranslatedText string             `json:"translated_text"`
	Status         string             `json:"status"`
	Version        int64              `json:"version"`
	UpdatedBy      pgtype.UUID        `json:"updated_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type NotificationsNotification struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ID              pgtype.UUID        `json:"id"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	MessageKey      string             `json:"message_key"`
	MessageParams   []byte             `json:"message_params"`
	TemplateVersion int32              `json:"template_version"`
	EntityType      *string            `json:"entity_type"`
	EntityID        pgtype.UUID        `json:"entity_id"`
	ReadAt          pgtype.Timestamptz `json:"read_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	Version         int64              `json:"version"`
	EmailState      string             `json:"email_state"`
	EmailUpdatedAt  pgtype.Timestamptz `json:"email_updated_at"`
}

type NotificationsSseEvent struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ID              pgtype.UUID        `json:"id"`
	EventType       string             `json:"event_type"`
	Data            []byte             `json:"data"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
}

type PlatformIdempotencyKey struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	Key            string             `json:"key"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Operation      string             `json:"operation"`
	RequestHash    []byte             `json:"request_hash"`
	ResponseStatus *int32             `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type PlatformJob struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	Kind           string             `json:"kind"`
	SchemaVersion  int32              `json:"schema_version"`
	IdempotencyKey string             `json:"idempotency_key"`
	Payload        []byte             `json:"payload"`
	State          string             `json:"state"`
	Attempts       int32              `json:"attempts"`
	MaxAttempts    int32              `json:"max_attempts"`
	AvailableAt    pgtype.Timestamptz `json:"available_at"`
	LockedAt       pgtype.Timestamptz `json:"locked_at"`
	LockedUntil    pgtype.Timestamptz `json:"locked_until"`
	WorkerID       *string            `json:"worker_id"`
	FencingToken   int64              `json:"fencing_token"`
	LastErrorCode  *string            `json:"last_error_code"`
	CompletedAt    pgtype.Timestamptz `json:"completed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type PlatformOutboxEvent struct {
	WorkspaceID   pgtype.UUID        `json:"workspace_id"`
	ID            pgtype.UUID        `json:"id"`
	EventType     string             `json:"event_type"`
	SchemaVersion int32              `json:"schema_version"`
	AggregateType string             `json:"aggregate_type"`
	AggregateID   pgtype.UUID        `json:"aggregate_id"`
	CausationID   pgtype.UUID        `json:"causation_id"`
	CorrelationID pgtype.UUID        `json:"correlation_id"`
	Payload       []byte             `json:"payload"`
	AvailableAt   pgtype.Timestamptz `json:"available_at"`
	PublishedAt   pgtype.Timestamptz `json:"published_at"`
	Attempts      int32              `json:"attempts"`
	LastErrorCode *string            `json:"last_error_code"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type PlatformSeedRun struct {
	Profile     string             `json:"profile"`
	SeedVersion int32              `json:"seed_version"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DatasetHash string             `json:"dataset_hash"`
	Counts      []byte             `json:"counts"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
}

type ProjectsProject struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	PlannedStartDate pgtype.Date        `json:"planned_start_date"`
	TargetEndDate    pgtype.Date        `json:"target_end_date"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	CreatedBy        pgtype.UUID        `json:"created_by"`
	Version          int64              `json:"version"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

type ProjectsProjectAssignment struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type ReportingDashboardPreference struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	UserID      pgtype.UUID        `json:"user_id"`
	Preferences []byte             `json:"preferences"`
	Version     int64              `json:"version"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	PeriodDays  int16              `json:"period_days"`
	Timezone    *string            `json:"timezone"`
}

type ReportingDashboardSummary struct {
	WorkspaceID           pgtype.UUID        `json:"workspace_id"`
	Currency              string             `json:"currency"`
	OpenPipelineMinor     int64              `json:"open_pipeline_minor"`
	WeightedForecastMinor int64              `json:"weighted_forecast_minor"`
	WonCount              int64              `json:"won_count"`
	LostCount             int64              `json:"lost_count"`
	OverdueTasks          int64              `json:"overdue_tasks"`
	DealsByStage          []byte             `json:"deals_by_stage"`
	ComputedAt            pgtype.Timestamptz `json:"computed_at"`
	SourceVersion         int64              `json:"source_version"`
}

type SalesDeal struct {
	WorkspaceID       pgtype.UUID        `json:"workspace_id"`
	ID                pgtype.UUID        `json:"id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          int32              `json:"position"`
	Status            string             `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	CustomFields      []byte             `json:"custom_fields"`
	Version           int64              `json:"version"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	ForecastCategory  string             `json:"forecast_category"`
	WonAt             pgtype.Timestamptz `json:"won_at"`
	LostAt            pgtype.Timestamptz `json:"lost_at"`
	DeletedBy         pgtype.UUID        `json:"deleted_by"`
	PlannedStartDate  pgtype.Date        `json:"planned_start_date"`
}

type SalesDealAssignment struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	DealID         pgtype.UUID        `json:"deal_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SalesDealLineItem struct {
	WorkspaceID    pgtype.UUID    `json:"workspace_id"`
	ID             pgtype.UUID    `json:"id"`
	DealID         pgtype.UUID    `json:"deal_id"`
	Name           string         `json:"name"`
	Quantity       pgtype.Numeric `json:"quantity"`
	UnitPriceMinor int64          `json:"unit_price_minor"`
	Currency       string         `json:"currency"`
	Position       int32          `json:"position"`
	Version        int64          `json:"version"`
}

type SalesDealParticipant struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	ContactID   pgtype.UUID        `json:"contact_id"`
	Role        *string            `json:"role"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SalesDealStageHistory struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	DealID      pgtype.UUID        `json:"deal_id"`
	FromStageID pgtype.UUID        `json:"from_stage_id"`
	ToStageID   pgtype.UUID        `json:"to_stage_id"`
	ChangedBy   pgtype.UUID        `json:"changed_by"`
	ChangedAt   pgtype.Timestamptz `json:"changed_at"`
}

type SalesLead struct {
	WorkspaceID        pgtype.UUID        `json:"workspace_id"`
	ID                 pgtype.UUID        `json:"id"`
	Name               string             `json:"name"`
	Email              *string            `json:"email"`
	CompanyName        *string            `json:"company_name"`
	Source             *string            `json:"source"`
	Status             string             `json:"status"`
	OwnerUserID        pgtype.UUID        `json:"owner_user_id"`
	ConvertedContactID pgtype.UUID        `json:"converted_contact_id"`
	ConvertedCompanyID pgtype.UUID        `json:"converted_company_id"`
	ConvertedDealID    pgtype.UUID        `json:"converted_deal_id"`
	CustomFields       []byte             `json:"custom_fields"`
	Version            int64              `json:"version"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	Phone              *string            `json:"phone"`
	EmailNormalized    *string            `json:"email_normalized"`
	PhoneNormalized    *string            `json:"phone_normalized"`
	JobTitle           *string            `json:"job_title"`
	TeamID             pgtype.UUID        `json:"team_id"`
	DeletedBy          pgtype.UUID        `json:"deleted_by"`
	StageID            pgtype.UUID        `json:"stage_id"`
}

type SalesLeadAssignment struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	ID             pgtype.UUID        `json:"id"`
	LeadID         pgtype.UUID        `json:"lead_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	CreatedBy      pgtype.UUID        `json:"created_by"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type SalesLeadStage struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Category    string             `json:"category"`
	Color       string             `json:"color"`
	Position    int32              `json:"position"`
	SystemKey   *string            `json:"system_key"`
	IsDefault   bool               `json:"is_default"`
	ArchivedAt  pgtype.Timestamptz `json:"archived_at"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SalesLeadStageHistory struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	LeadID      pgtype.UUID        `json:"lead_id"`
	FromStageID pgtype.UUID        `json:"from_stage_id"`
	ToStageID   pgtype.UUID        `json:"to_stage_id"`
	ChangedBy   pgtype.UUID        `json:"changed_by"`
	ChangedAt   pgtype.Timestamptz `json:"changed_at"`
}

type SalesPipeline struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	IsDefault   bool               `json:"is_default"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SalesPipelineStage struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	PipelineID       pgtype.UUID        `json:"pipeline_id"`
	Name             string             `json:"name"`
	Probability      int16              `json:"probability"`
	ForecastCategory string             `json:"forecast_category"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Version          int64              `json:"version"`
}

type SearchDocument struct {
	WorkspaceID    pgtype.UUID        `json:"workspace_id"`
	EntityType     string             `json:"entity_type"`
	EntityID       pgtype.UUID        `json:"entity_id"`
	Title          string             `json:"title"`
	Subtitle       *string            `json:"subtitle"`
	SearchableText string             `json:"searchable_text"`
	SearchVector   interface{}        `json:"search_vector"`
	RankBoost      float32            `json:"rank_boost"`
	Version        int64              `json:"version"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TenancyInvitation struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	EmailNormalized  string             `json:"email_normalized"`
	Role             string             `json:"role"`
	TokenHash        []byte             `json:"token_hash"`
	InvitedBy        pgtype.UUID        `json:"invited_by"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
}

type TenancyMembership struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Role             string             `json:"role"`
	Status           string             `json:"status"`
	LocaleOverride   *string            `json:"locale_override"`
	TimezoneOverride *string            `json:"timezone_override"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	RoleID           pgtype.UUID        `json:"role_id"`
}

type TenancyRolePermission struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	RoleID      pgtype.UUID        `json:"role_id"`
	Permission  string             `json:"permission"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

type TenancyTeam struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	Name        string             `json:"name"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type TenancyTeamMembership struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	MembershipID pgtype.UUID        `json:"membership_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type TenancyWorkspace struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	DefaultLocale    string             `json:"default_locale"`
	Timezone         string             `json:"timezone"`
	DefaultCurrency  string             `json:"default_currency"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	SupportedLocales []string           `json:"supported_locales"`
}

type TenancyWorkspaceRole struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	ID          pgtype.UUID        `json:"id"`
	RoleKey     string             `json:"role_key"`
	Name        string             `json:"name"`
	BaseRole    string             `json:"base_role"`
	IsSystem    bool               `json:"is_system"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}
