// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform.sql

package dbgen

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeIdempotencyKey = `-- name: CompleteIdempotencyKey :exec
UPDATE platform.idempotency_keys
SET response_status = $3, response_body = $4
WHERE workspace_id = $1 AND key = $2
`

type CompleteIdempotencyKeyParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	Key            string      `json:"key"`
	ResponseStatus *int32      `json:"response_status"`
	ResponseBody   []byte      `json:"response_body"`
}

func (q *Queries) CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error {
	_, err := q.db.Exec(ctx, completeIdempotencyKey,
		arg.WorkspaceID,
		arg.Key,
		arg.ResponseStatus,
		arg.ResponseBody,
	)
	return err
}

const deleteSearchDocument = `-- name: DeleteSearchDocument :exec
DELETE FROM search.documents
WHERE workspace_id = $1 AND entity_type = $2 AND entity_id = $3
`

type DeleteSearchDocumentParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

func (q *Queries) DeleteSearchDocument(ctx context.Context, arg DeleteSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, deleteSearchDocument, arg.WorkspaceID, arg.EntityType, arg.EntityID)
	return err
}

const getDashboardSummary = `-- name: GetDashboardSummary :one
SELECT currency, open_pipeline_minor, weighted_forecast_minor, won_count,
       lost_count, overdue_tasks, deals_by_stage, computed_at, source_version
FROM reporting.dashboard_summaries
WHERE workspace_id = $1
`

type GetDashboardSummaryRow struct {
	Currency              string             `json:"currency"`
	OpenPipelineMinor     int64              `json:"open_pipeline_minor"`
	WeightedForecastMinor int64              `json:"weighted_forecast_minor"`
	WonCount              int64              `json:"won_count"`
	LostCount             int64              `json:"lost_count"`
	OverdueTasks          int64              `json:"overdue_tasks"`
	DealsByStage          []byte             `json:"deals_by_stage"`
	ComputedAt            pgtype.Timestamptz `json:"computed_at"`
	SourceVersion         int64              `json:"source_version"`
}

func (q *Queries) GetDashboardSummary(ctx context.Context, workspaceID pgtype.UUID) (GetDashboardSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDashboardSummary, workspaceID)
	var i GetDashboardSummaryRow
	err := row.Scan(
		&i.Currency,
		&i.OpenPipelineMinor,
		&i.WeightedForecastMinor,
		&i.WonCount,
		&i.LostCount,
		&i.OverdueTasks,
		&i.DealsByStage,
		&i.ComputedAt,
		&i.SourceVersion,
	)
	return i, err
}

const getIdempotencyKey = `-- name: GetIdempotencyKey :one
SELECT key, actor_id, operation, request_hash, response_status, response_body,
       expires_at, created_at
FROM platform.idempotency_keys
WHERE workspace_id = $1 AND key = $2 AND expires_at > now()
`

type GetIdempotencyKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Key         string      `json:"key"`
}

type GetIdempotencyKeyRow struct {
	Key            string             `json:"key"`
	ActorID        pgtype.UUID        `json:"actor_id"`
	Operation      string             `json:"operation"`
	RequestHash    []byte             `json:"request_hash"`
	ResponseStatus *int32             `json:"response_status"`
	ResponseBody   []byte             `json:"response_body"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyKey, arg.WorkspaceID, arg.Key)
	var i GetIdempotencyKeyRow
	err := row.Scan(
		&i.Key,
		&i.ActorID,
		&i.Operation,
		&i.RequestHash,
		&i.ResponseStatus,
		&i.ResponseBody,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getSSEEventForDispatch = `-- name: GetSSEEventForDispatch :one
SELECT id, event_type, data, recipient_user_id
FROM notifications.sse_events
WHERE workspace_id = $1
  AND id = $2
  AND expires_at > now()
`

type GetSSEEventForDispatchParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EventID     pgtype.UUID `json:"event_id"`
}

type GetSSEEventForDispatchRow struct {
	ID              pgtype.UUID `json:"id"`
	EventType       string      `json:"event_type"`
	Data            []byte      `json:"data"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
}

func (q *Queries) GetSSEEventForDispatch(ctx context.Context, arg GetSSEEventForDispatchParams) (GetSSEEventForDispatchRow, error) {
	row := q.db.QueryRow(ctx, getSSEEventForDispatch, arg.WorkspaceID, arg.EventID)
	var i GetSSEEventForDispatchRow
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.Data,
		&i.RecipientUserID,
	)
	return i, err
}

const globalSearch = `-- name: GlobalSearch :many
WITH query AS (
  SELECT websearch_to_tsquery('simple', $1::text) AS tsq
)
SELECT entity_type, entity_id, title, subtitle,
       left(searchable_text, 240) AS snippet,
       (ts_rank(search_vector, query.tsq) * rank_boost
         + similarity(searchable_text, $1))::real AS rank
FROM search.documents, query
WHERE workspace_id = $2
  AND (search_vector @@ query.tsq OR searchable_text % $1)
ORDER BY rank DESC, title, entity_id
LIMIT 50
`

type GlobalSearchParams struct {
	SearchQuery string      `json:"search_query"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GlobalSearchRow struct {
	EntityType string      `json:"entity_type"`
	EntityID   pgtype.UUID `json:"entity_id"`
	Title      string      `json:"title"`
	Subtitle   *string     `json:"subtitle"`
	Snippet    string      `json:"snippet"`
	Rank       float32     `json:"rank"`
}

func (q *Queries) GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error) {
	rows, err := q.db.Query(ctx, globalSearch, arg.SearchQuery, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GlobalSearchRow{}
	for rows.Next() {
		var i GlobalSearchRow
		if err := rows.Scan(
			&i.EntityType,
			&i.EntityID,
			&i.Title,
			&i.Subtitle,
			&i.Snippet,
			&i.Rank,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuditEvent = `-- name: InsertAuditEvent :exec
INSERT INTO audit.events (
  workspace_id, id, actor_user_id, action, entity_type, entity_id, request_id,
  summary, ip_address, user_agent
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertAuditEventParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	Action      string      `json:"action"`
	EntityType  string      `json:"entity_type"`
	EntityID    pgtype.UUID `json:"entity_id"`
	RequestID   string      `json:"request_id"`
	Summary     []byte      `json:"summary"`
	IpAddress   *netip.Addr `json:"ip_address"`
	UserAgent   string      `json:"user_agent"`
}

func (q *Queries) InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAuditEvent,
		arg.WorkspaceID,
		arg.ID,
		arg.ActorUserID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.RequestID,
		arg.Summary,
		arg.IpAddress,
		arg.UserAgent,
	)
	return err
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO platform.outbox_events (
  workspace_id, id, event_type, schema_version, aggregate_type, aggregate_id,
  causation_id, correlation_id, payload
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertOutboxEventParams struct {
	WorkspaceID   pgtype.UUID `json:"workspace_id"`
	ID            pgtype.UUID `json:"id"`
	EventType     string      `json:"event_type"`
	SchemaVersion int32       `json:"schema_version"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
	CausationID   pgtype.UUID `json:"causation_id"`
	CorrelationID pgtype.UUID `json:"correlation_id"`
	Payload       []byte      `json:"payload"`
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.WorkspaceID,
		arg.ID,
		arg.EventType,
		arg.SchemaVersion,
		arg.AggregateType,
		arg.AggregateID,
		arg.CausationID,
		arg.CorrelationID,
		arg.Payload,
	)
	return err
}

const insertSSEEvent = `-- name: InsertSSEEvent :exec
INSERT INTO notifications.sse_events (
  workspace_id, id, event_type, data, expires_at
) VALUES ($1, $2, $3, $4, now() + interval '24 hours')
`

type InsertSSEEventParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	EventType   string      `json:"event_type"`
	Data        []byte      `json:"data"`
}

func (q *Queries) InsertSSEEvent(ctx context.Context, arg InsertSSEEventParams) error {
	_, err := q.db.Exec(ctx, insertSSEEvent,
		arg.WorkspaceID,
		arg.ID,
		arg.EventType,
		arg.Data,
	)
	return err
}

const insertUserSSEEvent = `-- name: InsertUserSSEEvent :exec
INSERT INTO notifications.sse_events (
  workspace_id, id, event_type, data, recipient_user_id, expires_at
) VALUES (
  $1, $2, $3,
  $4, $5, now() + interval '24 hours'
)
`

type InsertUserSSEEventParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	EventID         pgtype.UUID `json:"event_id"`
	EventType       string      `json:"event_type"`
	Data            []byte      `json:"data"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
}

func (q *Queries) InsertUserSSEEvent(ctx context.Context, arg InsertUserSSEEventParams) error {
	_, err := q.db.Exec(ctx, insertUserSSEEvent,
		arg.WorkspaceID,
		arg.EventID,
		arg.EventType,
		arg.Data,
		arg.RecipientUserID,
	)
	return err
}

const listAuditEvents = `-- name: ListAuditEvents :many
SELECT id, actor_user_id, action, entity_type, entity_id, request_id, summary,
       occurred_at
FROM audit.events
WHERE workspace_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListAuditEventsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Limit       int32       `json:"limit"`
}

type ListAuditEventsRow struct {
	ID          pgtype.UUID        `json:"id"`
	ActorUserID pgtype.UUID        `json:"actor_user_id"`
	Action      string             `json:"action"`
	EntityType  string             `json:"entity_type"`
	EntityID    pgtype.UUID        `json:"entity_id"`
	RequestID   string             `json:"request_id"`
	Summary     []byte             `json:"summary"`
	OccurredAt  pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listAuditEvents, arg.WorkspaceID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditEventsRow{}
	for rows.Next() {
		var i ListAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorUserID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.RequestID,
			&i.Summary,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSEEventsAfter = `-- name: ListSSEEventsAfter :many
WITH anchor AS (
  SELECT anchor_event.created_at, anchor_event.id
  FROM notifications.sse_events AS anchor_event
  WHERE anchor_event.workspace_id = $1 AND anchor_event.id = $2
)
SELECT event.id, event.event_type, event.data, event.created_at
FROM notifications.sse_events event, anchor
WHERE event.workspace_id = $1
  AND (event.created_at, event.id) > (anchor.created_at, anchor.id)
  AND event.expires_at > now()
ORDER BY event.created_at, event.id
LIMIT 100
`

type ListSSEEventsAfterParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type ListSSEEventsAfterRow struct {
	ID        pgtype.UUID        `json:"id"`
	EventType string             `json:"event_type"`
	Data      []byte             `json:"data"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSSEEventsAfter(ctx context.Context, arg ListSSEEventsAfterParams) ([]ListSSEEventsAfterRow, error) {
	rows, err := q.db.Query(ctx, listSSEEventsAfter, arg.WorkspaceID, arg.ID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSEEventsAfterRow{}
	for rows.Next() {
		var i ListSSEEventsAfterRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Data,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSSEEventsAfterForRecipient = `-- name: ListSSEEventsAfterForRecipient :many
WITH anchor AS (
  SELECT anchor_event.created_at, anchor_event.id
  FROM notifications.sse_events AS anchor_event
  WHERE anchor_event.workspace_id = $1
    AND anchor_event.id = $3
    AND (anchor_event.recipient_user_id IS NULL
         OR anchor_event.recipient_user_id = $2)
)
SELECT event.id, event.event_type, event.data, event.recipient_user_id, event.created_at
FROM notifications.sse_events AS event, anchor
WHERE event.workspace_id = $1
  AND (event.created_at, event.id) > (anchor.created_at, anchor.id)
  AND event.expires_at > now()
  AND (event.recipient_user_id IS NULL
       OR event.recipient_user_id = $2)
ORDER BY event.created_at, event.id
LIMIT 100
`

type ListSSEEventsAfterForRecipientParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	RecipientUserID pgtype.UUID `json:"recipient_user_id"`
	AnchorID        pgtype.UUID `json:"anchor_id"`
}

type ListSSEEventsAfterForRecipientRow struct {
	ID              pgtype.UUID        `json:"id"`
	EventType       string             `json:"event_type"`
	Data            []byte             `json:"data"`
	RecipientUserID pgtype.UUID        `json:"recipient_user_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListSSEEventsAfterForRecipient(ctx context.Context, arg ListSSEEventsAfterForRecipientParams) ([]ListSSEEventsAfterForRecipientRow, error) {
	rows, err := q.db.Query(ctx, listSSEEventsAfterForRecipient, arg.WorkspaceID, arg.RecipientUserID, arg.AnchorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSSEEventsAfterForRecipientRow{}
	for rows.Next() {
		var i ListSSEEventsAfterForRecipientRow
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.Data,
			&i.RecipientUserID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refreshDashboardSummary = `-- name: RefreshDashboardSummary :exec
INSERT INTO reporting.dashboard_summaries (
  workspace_id, currency, open_pipeline_minor, weighted_forecast_minor,
  won_count, lost_count, overdue_tasks, deals_by_stage, computed_at, source_version
)
SELECT w.id,
       w.default_currency,
       COALESCE(sum(d.amount_minor) FILTER (WHERE d.status = 'open'), 0)::bigint,
       COALESCE(sum((d.amount_minor * s.probability) / 100) FILTER (WHERE d.status = 'open'), 0)::bigint,
       count(d.id) FILTER (WHERE d.status = 'won')::bigint,
       count(d.id) FILTER (WHERE d.status = 'lost')::bigint,
       (SELECT count(*) FROM activities.activities a
         WHERE a.workspace_id = w.id AND a.activity_type = 'task'
           AND a.status = 'open' AND a.due_at < now() AND a.deleted_at IS NULL)::bigint,
       COALESCE((
         SELECT jsonb_agg(jsonb_build_object(
           'stageId', stage_totals.stage_id,
           'stageName', stage_totals.stage_name,
           'count', stage_totals.deal_count,
           'amountMinor', stage_totals.amount_minor
         ) ORDER BY stage_totals.position)
         FROM (
           SELECT ps.id AS stage_id, ps.name AS stage_name, ps.position,
                  count(sd.id)::bigint AS deal_count,
                  COALESCE(sum(sd.amount_minor), 0)::bigint AS amount_minor
           FROM sales.pipeline_stages ps
           LEFT JOIN sales.deals sd
             ON sd.workspace_id = ps.workspace_id AND sd.stage_id = ps.id
             AND sd.status = 'open' AND sd.deleted_at IS NULL
           WHERE ps.workspace_id = w.id
           GROUP BY ps.id, ps.name, ps.position
         ) stage_totals
       ), '[]'::jsonb),
       now(),
       COALESCE((SELECT max(version) FROM sales.deals vd WHERE vd.workspace_id = w.id), 1)
FROM tenancy.workspaces w
LEFT JOIN sales.deals d ON d.workspace_id = w.id AND d.deleted_at IS NULL
LEFT JOIN sales.pipeline_stages s ON s.workspace_id = d.workspace_id AND s.id = d.stage_id
WHERE w.id = $1
GROUP BY w.id, w.default_currency
ON CONFLICT (workspace_id) DO UPDATE
SET currency = EXCLUDED.currency,
    open_pipeline_minor = EXCLUDED.open_pipeline_minor,
    weighted_forecast_minor = EXCLUDED.weighted_forecast_minor,
    won_count = EXCLUDED.won_count,
    lost_count = EXCLUDED.lost_count,
    overdue_tasks = EXCLUDED.overdue_tasks,
    deals_by_stage = EXCLUDED.deals_by_stage,
    computed_at = EXCLUDED.computed_at,
    source_version = EXCLUDED.source_version
`

func (q *Queries) RefreshDashboardSummary(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, refreshDashboardSummary, id)
	return err
}

const reserveIdempotencyKey = `-- name: ReserveIdempotencyKey :one
INSERT INTO platform.idempotency_keys (
  workspace_id, key, actor_id, operation, request_hash, expires_at
) VALUES ($1, $2, $3, $4, $5, now() + interval '24 hours')
ON CONFLICT (workspace_id, key) DO NOTHING
RETURNING key
`

type ReserveIdempotencyKeyParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	Key         string      `json:"key"`
	ActorID     pgtype.UUID `json:"actor_id"`
	Operation   string      `json:"operation"`
	RequestHash []byte      `json:"request_hash"`
}

func (q *Queries) ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (string, error) {
	row := q.db.QueryRow(ctx, reserveIdempotencyKey,
		arg.WorkspaceID,
		arg.Key,
		arg.ActorID,
		arg.Operation,
		arg.RequestHash,
	)
	var key string
	err := row.Scan(&key)
	return key, err
}

const upsertSearchDocument = `-- name: UpsertSearchDocument :exec
INSERT INTO search.documents (
  workspace_id, entity_type, entity_id, title, subtitle, searchable_text,
  rank_boost, version
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (workspace_id, entity_type, entity_id) DO UPDATE
SET title = EXCLUDED.title,
    subtitle = EXCLUDED.subtitle,
    searchable_text = EXCLUDED.searchable_text,
    rank_boost = EXCLUDED.rank_boost,
    version = EXCLUDED.version,
    updated_at = now()
`

type UpsertSearchDocumentParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	EntityType     string      `json:"entity_type"`
	EntityID       pgtype.UUID `json:"entity_id"`
	Title          string      `json:"title"`
	Subtitle       *string     `json:"subtitle"`
	SearchableText string      `json:"searchable_text"`
	RankBoost      float32     `json:"rank_boost"`
	Version        int64       `json:"version"`
}

func (q *Queries) UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error {
	_, err := q.db.Exec(ctx, upsertSearchDocument,
		arg.WorkspaceID,
		arg.EntityType,
		arg.EntityID,
		arg.Title,
		arg.Subtitle,
		arg.SearchableText,
		arg.RankBoost,
		arg.Version,
	)
	return err
}
