// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpProjectAssignmentsVersion = `-- name: BumpProjectAssignmentsVersion :one
UPDATE projects.projects
SET version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $3 AND deleted_at IS NULL
RETURNING version
`

type BumpProjectAssignmentsVersionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) BumpProjectAssignmentsVersion(ctx context.Context, arg BumpProjectAssignmentsVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpProjectAssignmentsVersion, arg.WorkspaceID, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createProject = `-- name: CreateProject :one
INSERT INTO projects.projects (
  workspace_id, id, name, description, status, visibility,
  planned_start_date, target_end_date, owner_user_id, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, name, description, status, visibility, planned_start_date,
          target_end_date, owner_user_id, version, created_at, updated_at
`

type CreateProjectParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	Status           string      `json:"status"`
	Visibility       string      `json:"visibility"`
	PlannedStartDate pgtype.Date `json:"planned_start_date"`
	TargetEndDate    pgtype.Date `json:"target_end_date"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	CreatedBy        pgtype.UUID `json:"created_by"`
}

type CreateProjectRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	PlannedStartDate pgtype.Date        `json:"planned_start_date"`
	TargetEndDate    pgtype.Date        `json:"target_end_date"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.PlannedStartDate,
		arg.TargetEndDate,
		arg.OwnerUserID,
		arg.CreatedBy,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlannedStartDate,
		&i.TargetEndDate,
		&i.OwnerUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectAssignment = `-- name: CreateProjectAssignment :one
INSERT INTO projects.project_assignments (
  workspace_id, id, project_id, assignment_kind, user_id, department_id, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, project_id, assignment_kind, user_id, department_id, created_at
`

type CreateProjectAssignmentParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ID             pgtype.UUID `json:"id"`
	ProjectID      pgtype.UUID `json:"project_id"`
	AssignmentKind string      `json:"assignment_kind"`
	UserID         pgtype.UUID `json:"user_id"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

type CreateProjectAssignmentRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProjectAssignment(ctx context.Context, arg CreateProjectAssignmentParams) (CreateProjectAssignmentRow, error) {
	row := q.db.QueryRow(ctx, createProjectAssignment,
		arg.WorkspaceID,
		arg.ID,
		arg.ProjectID,
		arg.AssignmentKind,
		arg.UserID,
		arg.DepartmentID,
		arg.CreatedBy,
	)
	var i CreateProjectAssignmentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.AssignmentKind,
		&i.UserID,
		&i.DepartmentID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProjectAssignments = `-- name: DeleteProjectAssignments :exec
DELETE FROM projects.project_assignments
WHERE workspace_id = $1 AND project_id = $2
`

type DeleteProjectAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
}

func (q *Queries) DeleteProjectAssignments(ctx context.Context, arg DeleteProjectAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteProjectAssignments, arg.WorkspaceID, arg.ProjectID)
	return err
}

const getVisibleProject = `-- name: GetVisibleProject :one
SELECT project.id, project.name, project.description, project.status, project.visibility,
       project.planned_start_date, project.target_end_date, project.owner_user_id,
       project.version, project.created_at, project.updated_at,
       ($1::text IN ('owner', 'admin')
         OR project.owner_user_id = $2
         OR EXISTS (
           SELECT 1 FROM projects.project_assignments assignment
           WHERE assignment.workspace_id = project.workspace_id
             AND assignment.project_id = project.id
             AND assignment.assignment_kind = 'responsible'
             AND (
               assignment.user_id = $2
               OR EXISTS (
                 SELECT 1 FROM tenancy.team_memberships department_member
                 WHERE department_member.workspace_id = project.workspace_id
                   AND department_member.team_id = assignment.department_id
                   AND department_member.membership_id = $3
               )
             )
         )) AS can_edit,
       ($1::text IN ('owner', 'admin')
         OR project.owner_user_id = $2) AS can_manage
FROM projects.projects project
WHERE project.workspace_id = $4
  AND project.id = $5
  AND project.deleted_at IS NULL
  AND (
    project.visibility = 'workspace'
    OR $1::text IN ('owner', 'admin')
    OR project.owner_user_id = $2
    OR EXISTS (
      SELECT 1 FROM projects.project_assignments assignment
      WHERE assignment.workspace_id = project.workspace_id
        AND assignment.project_id = project.id
        AND (
          assignment.user_id = $2
          OR EXISTS (
            SELECT 1 FROM tenancy.team_memberships department_member
            WHERE department_member.workspace_id = project.workspace_id
              AND department_member.team_id = assignment.department_id
              AND department_member.membership_id = $3
          )
        )
    )
  )
`

type GetVisibleProjectParams struct {
	ActorRole    string      `json:"actor_role"`
	ActorUserID  pgtype.UUID `json:"actor_user_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	ProjectID    pgtype.UUID `json:"project_id"`
}

type GetVisibleProjectRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	PlannedStartDate pgtype.Date        `json:"planned_start_date"`
	TargetEndDate    pgtype.Date        `json:"target_end_date"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CanEdit          *bool              `json:"can_edit"`
	CanManage        *bool              `json:"can_manage"`
}

func (q *Queries) GetVisibleProject(ctx context.Context, arg GetVisibleProjectParams) (GetVisibleProjectRow, error) {
	row := q.db.QueryRow(ctx, getVisibleProject,
		arg.ActorRole,
		arg.ActorUserID,
		arg.MembershipID,
		arg.WorkspaceID,
		arg.ProjectID,
	)
	var i GetVisibleProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlannedStartDate,
		&i.TargetEndDate,
		&i.OwnerUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CanEdit,
		&i.CanManage,
	)
	return i, err
}

const listProjectAssignments = `-- name: ListProjectAssignments :many
SELECT assignment.id, assignment.project_id, assignment.assignment_kind,
       assignment.user_id, assignment.department_id,
       user_account.display_name AS user_name,
       department.name AS department_name,
       assignment.created_at
FROM projects.project_assignments assignment
LEFT JOIN identity.users user_account ON user_account.id = assignment.user_id
LEFT JOIN tenancy.teams department
  ON department.workspace_id = assignment.workspace_id
 AND department.id = assignment.department_id
WHERE assignment.workspace_id = $1 AND assignment.project_id = $2
ORDER BY assignment.assignment_kind, COALESCE(user_account.display_name, department.name), assignment.id
`

type ListProjectAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ProjectID   pgtype.UUID `json:"project_id"`
}

type ListProjectAssignmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	ProjectID      pgtype.UUID        `json:"project_id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	UserName       *string            `json:"user_name"`
	DepartmentName *string            `json:"department_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListProjectAssignments(ctx context.Context, arg ListProjectAssignmentsParams) ([]ListProjectAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAssignments, arg.WorkspaceID, arg.ProjectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProjectAssignmentsRow{}
	for rows.Next() {
		var i ListProjectAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.AssignmentKind,
			&i.UserID,
			&i.DepartmentID,
			&i.UserName,
			&i.DepartmentName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVisibleProjects = `-- name: ListVisibleProjects :many
SELECT project.id, project.name, project.description, project.status, project.visibility,
       project.planned_start_date, project.target_end_date, project.owner_user_id,
       project.version, project.created_at, project.updated_at,
       ($1::text IN ('owner', 'admin')
         OR project.owner_user_id = $2
         OR EXISTS (
           SELECT 1 FROM projects.project_assignments assignment
           WHERE assignment.workspace_id = project.workspace_id
             AND assignment.project_id = project.id
             AND assignment.assignment_kind = 'responsible'
             AND (
               assignment.user_id = $2
               OR EXISTS (
                 SELECT 1 FROM tenancy.team_memberships department_member
                 WHERE department_member.workspace_id = project.workspace_id
                   AND department_member.team_id = assignment.department_id
                   AND department_member.membership_id = $3
               )
             )
         )) AS can_edit,
       ($1::text IN ('owner', 'admin')
         OR project.owner_user_id = $2) AS can_manage
FROM projects.projects project
WHERE project.workspace_id = $4
  AND project.deleted_at IS NULL
  AND ($5::text = '' OR project.status = $5)
  AND (project.updated_at, project.id) <
      ($6::timestamptz, $7::uuid)
  AND (
    project.visibility = 'workspace'
    OR $1::text IN ('owner', 'admin')
    OR project.owner_user_id = $2
    OR EXISTS (
      SELECT 1 FROM projects.project_assignments assignment
      WHERE assignment.workspace_id = project.workspace_id
        AND assignment.project_id = project.id
        AND (
          assignment.user_id = $2
          OR EXISTS (
            SELECT 1 FROM tenancy.team_memberships department_member
            WHERE department_member.workspace_id = project.workspace_id
              AND department_member.team_id = assignment.department_id
              AND department_member.membership_id = $3
          )
        )
    )
  )
ORDER BY project.updated_at DESC, project.id DESC
LIMIT $8
`

type ListVisibleProjectsParams struct {
	ActorRole       string             `json:"actor_role"`
	ActorUserID     pgtype.UUID        `json:"actor_user_id"`
	MembershipID    pgtype.UUID        `json:"membership_id"`
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	StatusFilter    string             `json:"status_filter"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListVisibleProjectsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	PlannedStartDate pgtype.Date        `json:"planned_start_date"`
	TargetEndDate    pgtype.Date        `json:"target_end_date"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	CanEdit          *bool              `json:"can_edit"`
	CanManage        *bool              `json:"can_manage"`
}

func (q *Queries) ListVisibleProjects(ctx context.Context, arg ListVisibleProjectsParams) ([]ListVisibleProjectsRow, error) {
	rows, err := q.db.Query(ctx, listVisibleProjects,
		arg.ActorRole,
		arg.ActorUserID,
		arg.MembershipID,
		arg.WorkspaceID,
		arg.StatusFilter,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVisibleProjectsRow{}
	for rows.Next() {
		var i ListVisibleProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Status,
			&i.Visibility,
			&i.PlannedStartDate,
			&i.TargetEndDate,
			&i.OwnerUserID,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CanEdit,
			&i.CanManage,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteProject = `-- name: SoftDeleteProject :execrows
UPDATE projects.projects
SET deleted_at = now(), version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $3 AND deleted_at IS NULL
`

type SoftDeleteProjectParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteProject, arg.WorkspaceID, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateProject = `-- name: UpdateProject :one
UPDATE projects.projects
SET name = $3, description = $4, status = $5, visibility = $6,
    planned_start_date = $7, target_end_date = $8, owner_user_id = $9,
    version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $10 AND deleted_at IS NULL
RETURNING id, name, description, status, visibility, planned_start_date,
          target_end_date, owner_user_id, version, created_at, updated_at
`

type UpdateProjectParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	Name             string      `json:"name"`
	Description      string      `json:"description"`
	Status           string      `json:"status"`
	Visibility       string      `json:"visibility"`
	PlannedStartDate pgtype.Date `json:"planned_start_date"`
	TargetEndDate    pgtype.Date `json:"target_end_date"`
	OwnerUserID      pgtype.UUID `json:"owner_user_id"`
	Version          int64       `json:"version"`
}

type UpdateProjectRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Description      string             `json:"description"`
	Status           string             `json:"status"`
	Visibility       string             `json:"visibility"`
	PlannedStartDate pgtype.Date        `json:"planned_start_date"`
	TargetEndDate    pgtype.Date        `json:"target_end_date"`
	OwnerUserID      pgtype.UUID        `json:"owner_user_id"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error) {
	row := q.db.QueryRow(ctx, updateProject,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Status,
		arg.Visibility,
		arg.PlannedStartDate,
		arg.TargetEndDate,
		arg.OwnerUserID,
		arg.Version,
	)
	var i UpdateProjectRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Status,
		&i.Visibility,
		&i.PlannedStartDate,
		&i.TargetEndDate,
		&i.OwnerUserID,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
