// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error)
	ActivateCall(ctx context.Context, arg ActivateCallParams) error
	ActiveWorkspaceUserExists(ctx context.Context, arg ActiveWorkspaceUserExistsParams) (bool, error)
	AddConversationCallParticipants(ctx context.Context, arg AddConversationCallParticipantsParams) (int64, error)
	AddConversationMember(ctx context.Context, arg AddConversationMemberParams) error
	AddDealStageHistory(ctx context.Context, arg AddDealStageHistoryParams) error
	AddMessageReaction(ctx context.Context, arg AddMessageReactionParams) error
	AddTeamMembership(ctx context.Context, arg AddTeamMembershipParams) error
	AdvanceMFATimeStep(ctx context.Context, arg AdvanceMFATimeStepParams) (int64, error)
	ApplyPipelineStagePosition(ctx context.Context, arg ApplyPipelineStagePositionParams) (ApplyPipelineStagePositionRow, error)
	AssignMembershipWorkspaceRole(ctx context.Context, arg AssignMembershipWorkspaceRoleParams) (TenancyMembership, error)
	BumpActivityAssignmentsVersion(ctx context.Context, arg BumpActivityAssignmentsVersionParams) (int64, error)
	BumpDealAssignmentsVersion(ctx context.Context, arg BumpDealAssignmentsVersionParams) (int64, error)
	BumpDealVersion(ctx context.Context, arg BumpDealVersionParams) (int64, error)
	BumpLeadAssignmentsVersion(ctx context.Context, arg BumpLeadAssignmentsVersionParams) (int64, error)
	BumpProjectAssignmentsVersion(ctx context.Context, arg BumpProjectAssignmentsVersionParams) (int64, error)
	CancelActivityReminder(ctx context.Context, arg CancelActivityReminderParams) (int64, error)
	CancelRateLimitedAutomationExecution(ctx context.Context, arg CancelRateLimitedAutomationExecutionParams) (int64, error)
	ChatMessageVisible(ctx context.Context, arg ChatMessageVisibleParams) (bool, error)
	ClaimJob(ctx context.Context, arg ClaimJobParams) (ClaimJobRow, error)
	ClaimOutboxEvents(ctx context.Context, batchSize int32) ([]ClaimOutboxEventsRow, error)
	ClearLoginFailures(ctx context.Context, id pgtype.UUID) error
	CompleteActivity(ctx context.Context, arg CompleteActivityParams) (CompleteActivityRow, error)
	CompleteAutomationAction(ctx context.Context, arg CompleteAutomationActionParams) (int64, error)
	CompleteAutomationExecution(ctx context.Context, arg CompleteAutomationExecutionParams) (int64, error)
	CompleteIdempotencyKey(ctx context.Context, arg CompleteIdempotencyKeyParams) error
	CompleteJob(ctx context.Context, arg CompleteJobParams) (string, error)
	CompleteWebhookDelivery(ctx context.Context, arg CompleteWebhookDeliveryParams) (int64, error)
	ConsumeMFAChallenge(ctx context.Context, id pgtype.UUID) (int64, error)
	ConsumePasswordResetToken(ctx context.Context, id pgtype.UUID) (int64, error)
	ConsumeRecoveryCode(ctx context.Context, arg ConsumeRecoveryCodeParams) (int64, error)
	ContentTranslationCoverage(ctx context.Context, arg ContentTranslationCoverageParams) ([]ContentTranslationCoverageRow, error)
	ConversationMemberExists(ctx context.Context, arg ConversationMemberExistsParams) (bool, error)
	CountActiveCompanies(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CountActiveContacts(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CountActiveMentionedUsers(ctx context.Context, arg CountActiveMentionedUsersParams) (int32, error)
	CountActiveOwners(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CountPipelineStages(ctx context.Context, arg CountPipelineStagesParams) (int64, error)
	CountPipelines(ctx context.Context, workspaceID pgtype.UUID) (int64, error)
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (CreateAPIKeyRow, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (CreateActivityRow, error)
	CreateActivityAssignment(ctx context.Context, arg CreateActivityAssignmentParams) error
	CreateActivityComment(ctx context.Context, arg CreateActivityCommentParams) (CreateActivityCommentRow, error)
	CreateActivityReminder(ctx context.Context, arg CreateActivityReminderParams) (CreateActivityReminderRow, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (FilesAttachment, error)
	CreateAutomationRule(ctx context.Context, arg CreateAutomationRuleParams) (CreateAutomationRuleRow, error)
	CreateCall(ctx context.Context, arg CreateCallParams) (CreateCallRow, error)
	CreateCompany(ctx context.Context, arg CreateCompanyParams) (CreateCompanyRow, error)
	CreateContact(ctx context.Context, arg CreateContactParams) (CreateContactRow, error)
	CreateContentResource(ctx context.Context, arg CreateContentResourceParams) (LocalizationContentResource, error)
	CreateContentTranslation(ctx context.Context, arg CreateContentTranslationParams) (LocalizationContentTranslation, error)
	CreateConversation(ctx context.Context, arg CreateConversationParams) (CreateConversationRow, error)
	CreateCustomerTag(ctx context.Context, arg CreateCustomerTagParams) (CreateCustomerTagRow, error)
	CreateDeal(ctx context.Context, arg CreateDealParams) (CreateDealRow, error)
	CreateDealAssignment(ctx context.Context, arg CreateDealAssignmentParams) error
	CreateDealLineItem(ctx context.Context, arg CreateDealLineItemParams) (CreateDealLineItemRow, error)
	CreateDispatchedNotification(ctx context.Context, arg CreateDispatchedNotificationParams) (pgtype.UUID, error)
	CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error)
	CreateLeadAdvanced(ctx context.Context, arg CreateLeadAdvancedParams) (CreateLeadAdvancedRow, error)
	CreateLeadAssignment(ctx context.Context, arg CreateLeadAssignmentParams) error
	CreateLeadStage(ctx context.Context, arg CreateLeadStageParams) (CreateLeadStageRow, error)
	CreateMFAChallenge(ctx context.Context, arg CreateMFAChallengeParams) error
	CreateMembership(ctx context.Context, arg CreateMembershipParams) (TenancyMembership, error)
	CreateMessage(ctx context.Context, arg CreateMessageParams) (CreateMessageRow, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreatePipeline(ctx context.Context, arg CreatePipelineParams) (CreatePipelineRow, error)
	CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) (CreatePipelineStageRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateProjectAssignment(ctx context.Context, arg CreateProjectAssignmentParams) (CreateProjectAssignmentRow, error)
	CreateRecoveryCode(ctx context.Context, arg CreateRecoveryCodeParams) error
	CreateSession(ctx context.Context, arg CreateSessionParams) error
	CreateTeam(ctx context.Context, arg CreateTeamParams) (TenancyTeam, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (IdentityUser, error)
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (CreateWebhookDeliveryRow, error)
	CreateWebhookSubscription(ctx context.Context, arg CreateWebhookSubscriptionParams) (CreateWebhookSubscriptionRow, error)
	CreateWorkspace(ctx context.Context, arg CreateWorkspaceParams) (CreateWorkspaceRow, error)
	CreateWorkspaceRole(ctx context.Context, arg CreateWorkspaceRoleParams) (CreateWorkspaceRoleRow, error)
	DeclineCallParticipant(ctx context.Context, arg DeclineCallParticipantParams) (int64, error)
	DeleteActivePasswordResetTokens(ctx context.Context, userID pgtype.UUID) error
	DeleteActivityAssignments(ctx context.Context, arg DeleteActivityAssignmentsParams) error
	DeleteContentResources(ctx context.Context, arg DeleteContentResourcesParams) error
	DeleteCustomerTag(ctx context.Context, arg DeleteCustomerTagParams) (pgtype.UUID, error)
	DeleteDealAssignments(ctx context.Context, arg DeleteDealAssignmentsParams) error
	DeleteDealLineItem(ctx context.Context, arg DeleteDealLineItemParams) (pgtype.UUID, error)
	DeleteDealParticipant(ctx context.Context, arg DeleteDealParticipantParams) (pgtype.UUID, error)
	DeleteExpiredMFAChallenges(ctx context.Context) error
	DeleteExpiredPasswordResetTokens(ctx context.Context) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteLeadAssignments(ctx context.Context, arg DeleteLeadAssignmentsParams) error
	DeleteLeadStage(ctx context.Context, arg DeleteLeadStageParams) (int64, error)
	DeletePasswordResetToken(ctx context.Context, id pgtype.UUID) error
	DeletePipelineAdvanced(ctx context.Context, arg DeletePipelineAdvancedParams) (pgtype.UUID, error)
	DeletePipelineStageAdvanced(ctx context.Context, arg DeletePipelineStageAdvancedParams) (DeletePipelineStageAdvancedRow, error)
	DeleteProjectAssignments(ctx context.Context, arg DeleteProjectAssignmentsParams) error
	DeleteRecoveryCodes(ctx context.Context, userID pgtype.UUID) error
	DeleteSearchDocument(ctx context.Context, arg DeleteSearchDocumentParams) error
	DeleteWorkspaceRole(ctx context.Context, arg DeleteWorkspaceRoleParams) (int64, error)
	DeleteWorkspaceRolePermissions(ctx context.Context, arg DeleteWorkspaceRolePermissionsParams) error
	DisableMFAConfiguration(ctx context.Context, userID pgtype.UUID) error
	EnableMFAConfiguration(ctx context.Context, arg EnableMFAConfigurationParams) (int64, error)
	EndCall(ctx context.Context, arg EndCallParams) (EndCallRow, error)
	EndCallParticipants(ctx context.Context, arg EndCallParticipantsParams) error
	EnqueueActivityReminderJob(ctx context.Context, arg EnqueueActivityReminderJobParams) error
	EnqueueAutomationExecution(ctx context.Context, arg EnqueueAutomationExecutionParams) error
	EnqueueNotificationEmailJob(ctx context.Context, arg EnqueueNotificationEmailJobParams) error
	EnqueueWebhookDelivery(ctx context.Context, arg EnqueueWebhookDeliveryParams) error
	FailAutomationAction(ctx context.Context, arg FailAutomationActionParams) (int64, error)
	FailAutomationExecution(ctx context.Context, arg FailAutomationExecutionParams) (int64, error)
	FailJob(ctx context.Context, arg FailJobParams) (FailJobRow, error)
	FailWebhookDelivery(ctx context.Context, arg FailWebhookDeliveryParams) (int64, error)
	FindDirectConversation(ctx context.Context, arg FindDirectConversationParams) (pgtype.UUID, error)
	GetAPIKeyForAuthentication(ctx context.Context, arg GetAPIKeyForAuthenticationParams) (GetAPIKeyForAuthenticationRow, error)
	GetActiveMembership(ctx context.Context, arg GetActiveMembershipParams) (TenancyMembership, error)
	GetActivity(ctx context.Context, arg GetActivityParams) (GetActivityRow, error)
	GetActivityAutomationSnapshot(ctx context.Context, arg GetActivityAutomationSnapshotParams) ([]byte, error)
	GetActivityNotificationTarget(ctx context.Context, arg GetActivityNotificationTargetParams) (GetActivityNotificationTargetRow, error)
	GetAttachment(ctx context.Context, arg GetAttachmentParams) (FilesAttachment, error)
	GetAutomationAction(ctx context.Context, arg GetAutomationActionParams) (GetAutomationActionRow, error)
	GetAutomationExecution(ctx context.Context, arg GetAutomationExecutionParams) (GetAutomationExecutionRow, error)
	GetAutomationOutboxEvent(ctx context.Context, arg GetAutomationOutboxEventParams) (GetAutomationOutboxEventRow, error)
	GetAutomationRule(ctx context.Context, arg GetAutomationRuleParams) (GetAutomationRuleRow, error)
	GetCallForParticipant(ctx context.Context, arg GetCallForParticipantParams) (GetCallForParticipantRow, error)
	GetCompany(ctx context.Context, arg GetCompanyParams) (GetCompanyRow, error)
	GetCompanyAutomationSnapshot(ctx context.Context, arg GetCompanyAutomationSnapshotParams) ([]byte, error)
	GetCompanySearchSource(ctx context.Context, arg GetCompanySearchSourceParams) (GetCompanySearchSourceRow, error)
	GetContact(ctx context.Context, arg GetContactParams) (GetContactRow, error)
	GetContactAutomationSnapshot(ctx context.Context, arg GetContactAutomationSnapshotParams) ([]byte, error)
	GetContactSearchSource(ctx context.Context, arg GetContactSearchSourceParams) (GetContactSearchSourceRow, error)
	GetContentResource(ctx context.Context, arg GetContentResourceParams) (LocalizationContentResource, error)
	GetDashboardPreferences(ctx context.Context, arg GetDashboardPreferencesParams) (GetDashboardPreferencesRow, error)
	GetDashboardSummary(ctx context.Context, workspaceID pgtype.UUID) (GetDashboardSummaryRow, error)
	GetDeal(ctx context.Context, arg GetDealParams) (GetDealRow, error)
	GetDealAdvanced(ctx context.Context, arg GetDealAdvancedParams) (GetDealAdvancedRow, error)
	GetDealAutomationSnapshot(ctx context.Context, arg GetDealAutomationSnapshotParams) ([]byte, error)
	GetDealNotificationTarget(ctx context.Context, arg GetDealNotificationTargetParams) (GetDealNotificationTargetRow, error)
	GetDealSearchSource(ctx context.Context, arg GetDealSearchSourceParams) (GetDealSearchSourceRow, error)
	GetDefaultLeadStageByCategory(ctx context.Context, arg GetDefaultLeadStageByCategoryParams) (GetDefaultLeadStageByCategoryRow, error)
	GetDeletedContact(ctx context.Context, arg GetDeletedContactParams) (GetDeletedContactRow, error)
	GetIdempotencyKey(ctx context.Context, arg GetIdempotencyKeyParams) (GetIdempotencyKeyRow, error)
	GetImportSession(ctx context.Context, arg GetImportSessionParams) (GetImportSessionRow, error)
	GetLeadAdvanced(ctx context.Context, arg GetLeadAdvancedParams) (GetLeadAdvancedRow, error)
	GetLeadAutomationSnapshot(ctx context.Context, arg GetLeadAutomationSnapshotParams) ([]byte, error)
	GetLeadSearchSource(ctx context.Context, arg GetLeadSearchSourceParams) (GetLeadSearchSourceRow, error)
	GetLeadStage(ctx context.Context, arg GetLeadStageParams) (GetLeadStageRow, error)
	GetMembershipByIDForUpdate(ctx context.Context, arg GetMembershipByIDForUpdateParams) (TenancyMembership, error)
	GetMembershipByUserID(ctx context.Context, arg GetMembershipByUserIDParams) (TenancyMembership, error)
	GetNoteSearchSource(ctx context.Context, arg GetNoteSearchSourceParams) (GetNoteSearchSourceRow, error)
	GetNotificationOutboxEvent(ctx context.Context, arg GetNotificationOutboxEventParams) (GetNotificationOutboxEventRow, error)
	GetOutboxEventForWebhook(ctx context.Context, arg GetOutboxEventForWebhookParams) (GetOutboxEventForWebhookRow, error)
	GetPeriodReportOverview(ctx context.Context, arg GetPeriodReportOverviewParams) (GetPeriodReportOverviewRow, error)
	GetPipelineAdvanced(ctx context.Context, arg GetPipelineAdvancedParams) (GetPipelineAdvancedRow, error)
	GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (GetPipelineStageRow, error)
	GetPipelineStageAdvanced(ctx context.Context, arg GetPipelineStageAdvancedParams) (GetPipelineStageAdvancedRow, error)
	GetSSEEventForDispatch(ctx context.Context, arg GetSSEEventForDispatchParams) (GetSSEEventForDispatchRow, error)
	GetSearchOutboxEvent(ctx context.Context, arg GetSearchOutboxEventParams) (GetSearchOutboxEventRow, error)
	GetSessionPrincipal(ctx context.Context, tokenHash []byte) (GetSessionPrincipalRow, error)
	GetTeam(ctx context.Context, arg GetTeamParams) (TenancyTeam, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (IdentityUser, error)
	GetUserByIDForPasswordChange(ctx context.Context, id pgtype.UUID) (GetUserByIDForPasswordChangeRow, error)
	GetUserByNormalizedEmail(ctx context.Context, emailNormalized string) (IdentityUser, error)
	GetUserConversation(ctx context.Context, arg GetUserConversationParams) (GetUserConversationRow, error)
	GetVisibleProject(ctx context.Context, arg GetVisibleProjectParams) (GetVisibleProjectRow, error)
	GetWebhookDelivery(ctx context.Context, arg GetWebhookDeliveryParams) (GetWebhookDeliveryRow, error)
	GetWebhookSubscriptionForDelivery(ctx context.Context, arg GetWebhookSubscriptionForDeliveryParams) (GetWebhookSubscriptionForDeliveryRow, error)
	GetWorkspaceLocalizationSettings(ctx context.Context, workspaceID pgtype.UUID) (GetWorkspaceLocalizationSettingsRow, error)
	GetWorkspaceRoleForUpdate(ctx context.Context, arg GetWorkspaceRoleForUpdateParams) (GetWorkspaceRoleForUpdateRow, error)
	GlobalSearch(ctx context.Context, arg GlobalSearchParams) ([]GlobalSearchRow, error)
	InsertAuditEvent(ctx context.Context, arg InsertAuditEventParams) error
	InsertFanoutJob(ctx context.Context, arg InsertFanoutJobParams) error
	InsertLeadStageHistory(ctx context.Context, arg InsertLeadStageHistoryParams) error
	InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error
	InsertSSEEvent(ctx context.Context, arg InsertSSEEventParams) error
	InsertUserSSEEvent(ctx context.Context, arg InsertUserSSEEventParams) error
	InsertWorkspaceRolePermissions(ctx context.Context, arg InsertWorkspaceRolePermissionsParams) error
	IsMFAEnabled(ctx context.Context, userID pgtype.UUID) (bool, error)
	JoinCallParticipant(ctx context.Context, arg JoinCallParticipantParams) (JoinCallParticipantRow, error)
	LeaveCallParticipant(ctx context.Context, arg LeaveCallParticipantParams) (int64, error)
	ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ListAPIKeysRow, error)
	ListActivities(ctx context.Context, arg ListActivitiesParams) ([]ListActivitiesRow, error)
	ListActivityAssignmentUserIDs(ctx context.Context, arg ListActivityAssignmentUserIDsParams) ([]pgtype.UUID, error)
	ListActivityAssignments(ctx context.Context, arg ListActivityAssignmentsParams) ([]ListActivityAssignmentsRow, error)
	ListActivityAudienceUserIDs(ctx context.Context, arg ListActivityAudienceUserIDsParams) ([]pgtype.UUID, error)
	ListActivityComments(ctx context.Context, arg ListActivityCommentsParams) ([]ListActivityCommentsRow, error)
	ListActivityFeed(ctx context.Context, arg ListActivityFeedParams) ([]ListActivityFeedRow, error)
	ListActivityReminders(ctx context.Context, arg ListActivityRemindersParams) ([]ListActivityRemindersRow, error)
	ListAssignmentDepartmentOptions(ctx context.Context, workspaceID pgtype.UUID) ([]ListAssignmentDepartmentOptionsRow, error)
	ListAssignmentUserOptions(ctx context.Context, workspaceID pgtype.UUID) ([]ListAssignmentUserOptionsRow, error)
	ListAuditEvents(ctx context.Context, arg ListAuditEventsParams) ([]ListAuditEventsRow, error)
	ListAutomationRules(ctx context.Context, arg ListAutomationRulesParams) ([]ListAutomationRulesRow, error)
	ListCalendarActivities(ctx context.Context, arg ListCalendarActivitiesParams) ([]ListCalendarActivitiesRow, error)
	ListCallParticipantUserIDs(ctx context.Context, arg ListCallParticipantUserIDsParams) ([]pgtype.UUID, error)
	ListCompanies(ctx context.Context, arg ListCompaniesParams) ([]ListCompaniesRow, error)
	ListCompaniesPage(ctx context.Context, arg ListCompaniesPageParams) ([]ListCompaniesPageRow, error)
	ListContactTags(ctx context.Context, arg ListContactTagsParams) ([]ListContactTagsRow, error)
	ListContacts(ctx context.Context, arg ListContactsParams) ([]ListContactsRow, error)
	ListContentTranslations(ctx context.Context, arg ListContentTranslationsParams) ([]ListContentTranslationsRow, error)
	ListConversationAttachments(ctx context.Context, arg ListConversationAttachmentsParams) ([]ListConversationAttachmentsRow, error)
	ListConversationMessages(ctx context.Context, arg ListConversationMessagesParams) ([]ListConversationMessagesRow, error)
	ListConversationRecipientIDs(ctx context.Context, arg ListConversationRecipientIDsParams) ([]pgtype.UUID, error)
	ListCustomFieldDefinitions(ctx context.Context, arg ListCustomFieldDefinitionsParams) ([]ListCustomFieldDefinitionsRow, error)
	// Advanced customer-domain SQL lives here even where package-local typed row
	// scanners are used for JSON-heavy payloads. Keeping the statements centralized
	// makes tenant predicates and query plans reviewable.
	ListCustomerTags(ctx context.Context, workspaceID pgtype.UUID) ([]ListCustomerTagsRow, error)
	ListDashboardRecentActivity(ctx context.Context, arg ListDashboardRecentActivityParams) ([]ListDashboardRecentActivityRow, error)
	ListDealAssignments(ctx context.Context, arg ListDealAssignmentsParams) ([]ListDealAssignmentsRow, error)
	ListDealLineItems(ctx context.Context, arg ListDealLineItemsParams) ([]ListDealLineItemsRow, error)
	ListDealParticipants(ctx context.Context, arg ListDealParticipantsParams) ([]ListDealParticipantsRow, error)
	ListDealStageHistoryAdvanced(ctx context.Context, arg ListDealStageHistoryAdvancedParams) ([]ListDealStageHistoryAdvancedRow, error)
	ListDealTrash(ctx context.Context, arg ListDealTrashParams) ([]ListDealTrashRow, error)
	ListDeals(ctx context.Context, arg ListDealsParams) ([]ListDealsRow, error)
	ListDealsAdvanced(ctx context.Context, arg ListDealsAdvancedParams) ([]ListDealsAdvancedRow, error)
	ListDeletedCompanies(ctx context.Context, arg ListDeletedCompaniesParams) ([]ListDeletedCompaniesRow, error)
	ListDeletedContacts(ctx context.Context, arg ListDeletedContactsParams) ([]ListDeletedContactsRow, error)
	ListEnabledAutomationRulesForTrigger(ctx context.Context, arg ListEnabledAutomationRulesForTriggerParams) ([]ListEnabledAutomationRulesForTriggerRow, error)
	ListEntityAttachments(ctx context.Context, arg ListEntityAttachmentsParams) ([]FilesAttachment, error)
	ListEntityTimeline(ctx context.Context, arg ListEntityTimelineParams) ([]ListEntityTimelineRow, error)
	ListKanbanStageDeals(ctx context.Context, arg ListKanbanStageDealsParams) ([]ListKanbanStageDealsRow, error)
	ListLeadAssignments(ctx context.Context, arg ListLeadAssignmentsParams) ([]ListLeadAssignmentsRow, error)
	ListLeadStages(ctx context.Context, workspaceID pgtype.UUID) ([]ListLeadStagesRow, error)
	ListLeadTrash(ctx context.Context, arg ListLeadTrashParams) ([]ListLeadTrashRow, error)
	ListLeadsAdvanced(ctx context.Context, arg ListLeadsAdvancedParams) ([]ListLeadsAdvancedRow, error)
	ListMembershipPermissions(ctx context.Context, arg ListMembershipPermissionsParams) ([]string, error)
	ListPipelineStages(ctx context.Context, arg ListPipelineStagesParams) ([]ListPipelineStagesRow, error)
	ListPipelineStagesForWorkspace(ctx context.Context, workspaceID pgtype.UUID) ([]ListPipelineStagesForWorkspaceRow, error)
	ListPipelines(ctx context.Context, workspaceID pgtype.UUID) ([]ListPipelinesRow, error)
	ListProjectAssignments(ctx context.Context, arg ListProjectAssignmentsParams) ([]ListProjectAssignmentsRow, error)
	ListSSEEventsAfter(ctx context.Context, arg ListSSEEventsAfterParams) ([]ListSSEEventsAfterRow, error)
	ListSSEEventsAfterForRecipient(ctx context.Context, arg ListSSEEventsAfterForRecipientParams) ([]ListSSEEventsAfterForRecipientRow, error)
	ListSavedViews(ctx context.Context, arg ListSavedViewsParams) ([]ListSavedViewsRow, error)
	ListTeamMemberships(ctx context.Context, arg ListTeamMembershipsParams) ([]ListTeamMembershipsRow, error)
	ListTeams(ctx context.Context, workspaceID pgtype.UUID) ([]TenancyTeam, error)
	ListUserConversations(ctx context.Context, arg ListUserConversationsParams) ([]ListUserConversationsRow, error)
	ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error)
	ListUserWorkspaces(ctx context.Context, userID pgtype.UUID) ([]ListUserWorkspacesRow, error)
	ListVisibleProjects(ctx context.Context, arg ListVisibleProjectsParams) ([]ListVisibleProjectsRow, error)
	ListWebhookDeliveries(ctx context.Context, arg ListWebhookDeliveriesParams) ([]ListWebhookDeliveriesRow, error)
	ListWebhookSubscriptions(ctx context.Context, arg ListWebhookSubscriptionsParams) ([]ListWebhookSubscriptionsRow, error)
	ListWebhookSubscriptionsForEvent(ctx context.Context, arg ListWebhookSubscriptionsForEventParams) ([]ListWebhookSubscriptionsForEventRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error)
	ListWorkspaceRoles(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceRolesRow, error)
	LockActivityReminderForDelivery(ctx context.Context, arg LockActivityReminderForDeliveryParams) (LockActivityReminderForDeliveryRow, error)
	LockInvitationByHash(ctx context.Context, arg LockInvitationByHashParams) (LockInvitationByHashRow, error)
	LockMFAChallenge(ctx context.Context, tokenHash []byte) (LockMFAChallengeRow, error)
	LockMFAConfiguration(ctx context.Context, userID pgtype.UUID) (IdentityMfaConfiguration, error)
	LockNotificationEmailDelivery(ctx context.Context, arg LockNotificationEmailDeliveryParams) (LockNotificationEmailDeliveryRow, error)
	LockPasswordResetToken(ctx context.Context, tokenHash []byte) (LockPasswordResetTokenRow, error)
	LockTaskForAssignmentUpdate(ctx context.Context, arg LockTaskForAssignmentUpdateParams) (int64, error)
	LockWorkspaceMembershipMutation(ctx context.Context, workspaceID string) error
	MarkActivityReminderDelivered(ctx context.Context, arg MarkActivityReminderDeliveredParams) (int64, error)
	MarkAllNotificationsRead(ctx context.Context, arg MarkAllNotificationsReadParams) (int64, error)
	MarkAttachmentDeleted(ctx context.Context, arg MarkAttachmentDeletedParams) (MarkAttachmentDeletedRow, error)
	MarkContentTranslationsDraft(ctx context.Context, arg MarkContentTranslationsDraftParams) error
	MarkConversationRead(ctx context.Context, arg MarkConversationReadParams) (int64, error)
	MarkExhaustedJobsDead(ctx context.Context) (int64, error)
	MarkLeadConverted(ctx context.Context, arg MarkLeadConvertedParams) (MarkLeadConvertedRow, error)
	MarkNotificationEmailFailed(ctx context.Context, arg MarkNotificationEmailFailedParams) (int64, error)
	MarkNotificationEmailSent(ctx context.Context, arg MarkNotificationEmailSentParams) (int64, error)
	MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) (MarkNotificationReadRow, error)
	MarkOutboxPublished(ctx context.Context, arg MarkOutboxPublishedParams) (int64, error)
	MoveDeal(ctx context.Context, arg MoveDealParams) (MoveDealRow, error)
	MoveLeadToStage(ctx context.Context, arg MoveLeadToStageParams) (MoveLeadToStageRow, error)
	NextDealPosition(ctx context.Context, arg NextDealPositionParams) (int32, error)
	NextLeadStagePosition(ctx context.Context, workspaceID pgtype.UUID) (int32, error)
	NextPipelineStagePositionAdvanced(ctx context.Context, arg NextPipelineStagePositionAdvancedParams) (int32, error)
	OffsetPipelineStagePositions(ctx context.Context, arg OffsetPipelineStagePositionsParams) error
	PinMessage(ctx context.Context, arg PinMessageParams) error
	PruneAutomationHourlyUsage(ctx context.Context) (int64, error)
	RecordLoginFailure(ctx context.Context, id pgtype.UUID) error
	RecordMFAChallengeFailure(ctx context.Context, id pgtype.UUID) error
	RecordOutboxFailure(ctx context.Context, arg RecordOutboxFailureParams) error
	RefreshDashboardSummary(ctx context.Context, id pgtype.UUID) error
	RemoveMessageReaction(ctx context.Context, arg RemoveMessageReactionParams) (int64, error)
	RemoveTeamMembership(ctx context.Context, arg RemoveTeamMembershipParams) (int64, error)
	ReplacePasswordAndRevokeSessions(ctx context.Context, arg ReplacePasswordAndRevokeSessionsParams) (int64, error)
	ReportActivitiesByDay(ctx context.Context, arg ReportActivitiesByDayParams) ([]ReportActivitiesByDayRow, error)
	ReportDealsByOwner(ctx context.Context, arg ReportDealsByOwnerParams) ([]ReportDealsByOwnerRow, error)
	ReportDealsByStage(ctx context.Context, arg ReportDealsByStageParams) ([]ReportDealsByStageRow, error)
	ReportLeadSources(ctx context.Context, arg ReportLeadSourcesParams) ([]ReportLeadSourcesRow, error)
	ReserveAutomationExecution(ctx context.Context, arg ReserveAutomationExecutionParams) (ReserveAutomationExecutionRow, error)
	ReserveIdempotencyKey(ctx context.Context, arg ReserveIdempotencyKeyParams) (string, error)
	ResolveAutomationEmailRecipient(ctx context.Context, arg ResolveAutomationEmailRecipientParams) (ResolveAutomationEmailRecipientRow, error)
	ResolvePublishedContent(ctx context.Context, arg ResolvePublishedContentParams) (ResolvePublishedContentRow, error)
	ResolvePublishedContents(ctx context.Context, arg ResolvePublishedContentsParams) ([]ResolvePublishedContentsRow, error)
	RestoreCompany(ctx context.Context, arg RestoreCompanyParams) (RestoreCompanyRow, error)
	RestoreContact(ctx context.Context, arg RestoreContactParams) (int64, error)
	RestoreDeal(ctx context.Context, arg RestoreDealParams) (RestoreDealRow, error)
	RestoreLead(ctx context.Context, arg RestoreLeadParams) (RestoreLeadRow, error)
	RetryWebhookDelivery(ctx context.Context, arg RetryWebhookDeliveryParams) (RetryWebhookDeliveryRow, error)
	RevokeAPIKey(ctx context.Context, arg RevokeAPIKeyParams) (int64, error)
	RevokeAllUserSessions(ctx context.Context, userID pgtype.UUID) error
	RevokeSessionByToken(ctx context.Context, tokenHash []byte) error
	RotateWebhookSecret(ctx context.Context, arg RotateWebhookSecretParams) (RotateWebhookSecretRow, error)
	SaveDashboardPreferences(ctx context.Context, arg SaveDashboardPreferencesParams) (SaveDashboardPreferencesRow, error)
	SetActorContext(ctx context.Context, setConfig string) error
	SetAutomationRuleEnabled(ctx context.Context, arg SetAutomationRuleEnabledParams) (SetAutomationRuleEnabledRow, error)
	SetDealOutcome(ctx context.Context, arg SetDealOutcomeParams) (SetDealOutcomeRow, error)
	SetTenantContext(ctx context.Context, arg SetTenantContextParams) error
	SetWebhookSubscriptionEnabled(ctx context.Context, arg SetWebhookSubscriptionEnabledParams) (SetWebhookSubscriptionEnabledRow, error)
	SoftDeleteActivity(ctx context.Context, arg SoftDeleteActivityParams) (int64, error)
	SoftDeleteActivityComment(ctx context.Context, arg SoftDeleteActivityCommentParams) (int64, error)
	SoftDeleteCompany(ctx context.Context, arg SoftDeleteCompanyParams) (int64, error)
	SoftDeleteContact(ctx context.Context, arg SoftDeleteContactParams) (int64, error)
	SoftDeleteDeal(ctx context.Context, arg SoftDeleteDealParams) (int64, error)
	SoftDeleteLead(ctx context.Context, arg SoftDeleteLeadParams) (int64, error)
	SoftDeleteProject(ctx context.Context, arg SoftDeleteProjectParams) (int64, error)
	StartAutomationAction(ctx context.Context, arg StartAutomationActionParams) (StartAutomationActionRow, error)
	StartAutomationExecution(ctx context.Context, arg StartAutomationExecutionParams) (int64, error)
	StartWebhookDelivery(ctx context.Context, arg StartWebhookDeliveryParams) (int64, error)
	TouchAPIKeyLastUsed(ctx context.Context, arg TouchAPIKeyLastUsedParams) error
	TouchSession(ctx context.Context, id pgtype.UUID) error
	TryConsumeAutomationRateLimit(ctx context.Context, arg TryConsumeAutomationRateLimitParams) (int32, error)
	UnpinMessage(ctx context.Context, arg UnpinMessageParams) (int64, error)
	UnsetPipelineDefaults(ctx context.Context, arg UnsetPipelineDefaultsParams) error
	UpdateActivity(ctx context.Context, arg UpdateActivityParams) (UpdateActivityRow, error)
	UpdateActivityComment(ctx context.Context, arg UpdateActivityCommentParams) (UpdateActivityCommentRow, error)
	UpdateActivityReminder(ctx context.Context, arg UpdateActivityReminderParams) (UpdateActivityReminderRow, error)
	UpdateAttachmentScanState(ctx context.Context, arg UpdateAttachmentScanStateParams) (int64, error)
	UpdateAutomationRule(ctx context.Context, arg UpdateAutomationRuleParams) (UpdateAutomationRuleRow, error)
	UpdateCompany(ctx context.Context, arg UpdateCompanyParams) (UpdateCompanyRow, error)
	UpdateContact(ctx context.Context, arg UpdateContactParams) (UpdateContactRow, error)
	UpdateContentResourceSource(ctx context.Context, arg UpdateContentResourceSourceParams) (LocalizationContentResource, error)
	UpdateContentTranslation(ctx context.Context, arg UpdateContentTranslationParams) (LocalizationContentTranslation, error)
	UpdateCustomerTag(ctx context.Context, arg UpdateCustomerTagParams) (UpdateCustomerTagRow, error)
	UpdateDealAdvanced(ctx context.Context, arg UpdateDealAdvancedParams) (UpdateDealAdvancedRow, error)
	UpdateDealLineItem(ctx context.Context, arg UpdateDealLineItemParams) (UpdateDealLineItemRow, error)
	UpdateLeadAdvanced(ctx context.Context, arg UpdateLeadAdvancedParams) (UpdateLeadAdvancedRow, error)
	UpdateLeadStage(ctx context.Context, arg UpdateLeadStageParams) (UpdateLeadStageRow, error)
	UpdateMembershipLocaleOverride(ctx context.Context, arg UpdateMembershipLocaleOverrideParams) (TenancyMembership, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (TenancyMembership, error)
	UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (TenancyMembership, error)
	UpdatePipelineAdvanced(ctx context.Context, arg UpdatePipelineAdvancedParams) (UpdatePipelineAdvancedRow, error)
	UpdatePipelineStageAdvanced(ctx context.Context, arg UpdatePipelineStageAdvancedParams) (UpdatePipelineStageAdvancedRow, error)
	UpdateProject(ctx context.Context, arg UpdateProjectParams) (UpdateProjectRow, error)
	UpdateUserLocale(ctx context.Context, arg UpdateUserLocaleParams) (UpdateUserLocaleRow, error)
	UpdateWorkspaceDefaults(ctx context.Context, arg UpdateWorkspaceDefaultsParams) (UpdateWorkspaceDefaultsRow, error)
	UpdateWorkspaceLocales(ctx context.Context, arg UpdateWorkspaceLocalesParams) (UpdateWorkspaceLocalesRow, error)
	UpdateWorkspaceRole(ctx context.Context, arg UpdateWorkspaceRoleParams) (UpdateWorkspaceRoleRow, error)
	UpsertDealParticipant(ctx context.Context, arg UpsertDealParticipantParams) (UpsertDealParticipantRow, error)
	UpsertPendingMFAConfiguration(ctx context.Context, arg UpsertPendingMFAConfigurationParams) error
	UpsertSearchDocument(ctx context.Context, arg UpsertSearchDocumentParams) error
}

var _ Querier = (*Queries)(nil)
