// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: record_assignments.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpActivityAssignmentsVersion = `-- name: BumpActivityAssignmentsVersion :one
UPDATE activities.activities activity
SET assignee_user_id = (
      SELECT assignment.user_id FROM activities.activity_assignments assignment
      WHERE assignment.workspace_id = activity.workspace_id AND assignment.activity_id = activity.id
        AND assignment.assignment_kind = 'responsible' AND assignment.user_id IS NOT NULL
      ORDER BY assignment.is_primary DESC, assignment.created_at, assignment.id LIMIT 1
    ),
    version = activity.version + 1, updated_at = now()
WHERE activity.workspace_id = $1 AND activity.id = $2 AND activity.version = $3
  AND activity.deleted_at IS NULL AND activity.activity_type = 'task'
RETURNING activity.version
`

type BumpActivityAssignmentsVersionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) BumpActivityAssignmentsVersion(ctx context.Context, arg BumpActivityAssignmentsVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpActivityAssignmentsVersion, arg.WorkspaceID, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const bumpDealAssignmentsVersion = `-- name: BumpDealAssignmentsVersion :one
UPDATE sales.deals deal
SET owner_user_id = (
      SELECT assignment.user_id FROM sales.deal_assignments assignment
      WHERE assignment.workspace_id = deal.workspace_id AND assignment.deal_id = deal.id
        AND assignment.assignment_kind = 'responsible' AND assignment.user_id IS NOT NULL
      ORDER BY assignment.is_primary DESC, assignment.created_at, assignment.id LIMIT 1
    ),
    version = deal.version + 1, updated_at = now()
WHERE deal.workspace_id = $1 AND deal.id = $2 AND deal.version = $3 AND deal.deleted_at IS NULL
RETURNING deal.version
`

type BumpDealAssignmentsVersionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) BumpDealAssignmentsVersion(ctx context.Context, arg BumpDealAssignmentsVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpDealAssignmentsVersion, arg.WorkspaceID, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const bumpLeadAssignmentsVersion = `-- name: BumpLeadAssignmentsVersion :one
UPDATE sales.leads lead
SET owner_user_id = (
      SELECT assignment.user_id FROM sales.lead_assignments assignment
      WHERE assignment.workspace_id = lead.workspace_id AND assignment.lead_id = lead.id
        AND assignment.assignment_kind = 'responsible' AND assignment.user_id IS NOT NULL
      ORDER BY assignment.is_primary DESC, assignment.created_at, assignment.id LIMIT 1
    ),
    team_id = (
      SELECT assignment.department_id FROM sales.lead_assignments assignment
      WHERE assignment.workspace_id = lead.workspace_id AND assignment.lead_id = lead.id
        AND assignment.assignment_kind = 'responsible' AND assignment.department_id IS NOT NULL
      ORDER BY assignment.is_primary DESC, assignment.created_at, assignment.id LIMIT 1
    ),
    version = lead.version + 1, updated_at = now()
WHERE lead.workspace_id = $1 AND lead.id = $2 AND lead.version = $3 AND lead.deleted_at IS NULL
RETURNING lead.version
`

type BumpLeadAssignmentsVersionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) BumpLeadAssignmentsVersion(ctx context.Context, arg BumpLeadAssignmentsVersionParams) (int64, error) {
	row := q.db.QueryRow(ctx, bumpLeadAssignmentsVersion, arg.WorkspaceID, arg.ID, arg.Version)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const createActivityAssignment = `-- name: CreateActivityAssignment :exec
INSERT INTO activities.activity_assignments (
  workspace_id, id, activity_id, assignment_kind, user_id, department_id, is_primary, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateActivityAssignmentParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ID             pgtype.UUID `json:"id"`
	ActivityID     pgtype.UUID `json:"activity_id"`
	AssignmentKind string      `json:"assignment_kind"`
	UserID         pgtype.UUID `json:"user_id"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	IsPrimary      bool        `json:"is_primary"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateActivityAssignment(ctx context.Context, arg CreateActivityAssignmentParams) error {
	_, err := q.db.Exec(ctx, createActivityAssignment,
		arg.WorkspaceID,
		arg.ID,
		arg.ActivityID,
		arg.AssignmentKind,
		arg.UserID,
		arg.DepartmentID,
		arg.IsPrimary,
		arg.CreatedBy,
	)
	return err
}

const createDealAssignment = `-- name: CreateDealAssignment :exec
INSERT INTO sales.deal_assignments (
  workspace_id, id, deal_id, assignment_kind, user_id, department_id, is_primary, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateDealAssignmentParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ID             pgtype.UUID `json:"id"`
	DealID         pgtype.UUID `json:"deal_id"`
	AssignmentKind string      `json:"assignment_kind"`
	UserID         pgtype.UUID `json:"user_id"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	IsPrimary      bool        `json:"is_primary"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateDealAssignment(ctx context.Context, arg CreateDealAssignmentParams) error {
	_, err := q.db.Exec(ctx, createDealAssignment,
		arg.WorkspaceID,
		arg.ID,
		arg.DealID,
		arg.AssignmentKind,
		arg.UserID,
		arg.DepartmentID,
		arg.IsPrimary,
		arg.CreatedBy,
	)
	return err
}

const createLeadAssignment = `-- name: CreateLeadAssignment :exec
INSERT INTO sales.lead_assignments (
  workspace_id, id, lead_id, assignment_kind, user_id, department_id, is_primary, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateLeadAssignmentParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	ID             pgtype.UUID `json:"id"`
	LeadID         pgtype.UUID `json:"lead_id"`
	AssignmentKind string      `json:"assignment_kind"`
	UserID         pgtype.UUID `json:"user_id"`
	DepartmentID   pgtype.UUID `json:"department_id"`
	IsPrimary      bool        `json:"is_primary"`
	CreatedBy      pgtype.UUID `json:"created_by"`
}

func (q *Queries) CreateLeadAssignment(ctx context.Context, arg CreateLeadAssignmentParams) error {
	_, err := q.db.Exec(ctx, createLeadAssignment,
		arg.WorkspaceID,
		arg.ID,
		arg.LeadID,
		arg.AssignmentKind,
		arg.UserID,
		arg.DepartmentID,
		arg.IsPrimary,
		arg.CreatedBy,
	)
	return err
}

const deleteActivityAssignments = `-- name: DeleteActivityAssignments :exec
DELETE FROM activities.activity_assignments WHERE workspace_id = $1 AND activity_id = $2
`

type DeleteActivityAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActivityID  pgtype.UUID `json:"activity_id"`
}

func (q *Queries) DeleteActivityAssignments(ctx context.Context, arg DeleteActivityAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteActivityAssignments, arg.WorkspaceID, arg.ActivityID)
	return err
}

const deleteDealAssignments = `-- name: DeleteDealAssignments :exec
DELETE FROM sales.deal_assignments WHERE workspace_id = $1 AND deal_id = $2
`

type DeleteDealAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DealID      pgtype.UUID `json:"deal_id"`
}

func (q *Queries) DeleteDealAssignments(ctx context.Context, arg DeleteDealAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteDealAssignments, arg.WorkspaceID, arg.DealID)
	return err
}

const deleteLeadAssignments = `-- name: DeleteLeadAssignments :exec
DELETE FROM sales.lead_assignments WHERE workspace_id = $1 AND lead_id = $2
`

type DeleteLeadAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LeadID      pgtype.UUID `json:"lead_id"`
}

func (q *Queries) DeleteLeadAssignments(ctx context.Context, arg DeleteLeadAssignmentsParams) error {
	_, err := q.db.Exec(ctx, deleteLeadAssignments, arg.WorkspaceID, arg.LeadID)
	return err
}

const listActivityAssignmentUserIDs = `-- name: ListActivityAssignmentUserIDs :many
SELECT DISTINCT membership.user_id
FROM tenancy.memberships membership
WHERE membership.workspace_id = $1
  AND membership.status = 'active'
  AND EXISTS (
    SELECT 1 FROM activities.activity_assignments assignment
    WHERE assignment.workspace_id = membership.workspace_id
      AND assignment.activity_id = $2
      AND (
        assignment.user_id = membership.user_id
        OR EXISTS (
          SELECT 1 FROM tenancy.team_memberships department_member
          WHERE department_member.workspace_id = membership.workspace_id
            AND department_member.membership_id = membership.id
            AND department_member.team_id = assignment.department_id
        )
      )
  )
ORDER BY membership.user_id
`

type ListActivityAssignmentUserIDsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActivityID  pgtype.UUID `json:"activity_id"`
}

func (q *Queries) ListActivityAssignmentUserIDs(ctx context.Context, arg ListActivityAssignmentUserIDsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, listActivityAssignmentUserIDs, arg.WorkspaceID, arg.ActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.UUID{}
	for rows.Next() {
		var user_id pgtype.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActivityAssignments = `-- name: ListActivityAssignments :many
SELECT assignment.id, assignment.assignment_kind, assignment.user_id,
       assignment.department_id, assignment.is_primary,
       user_account.display_name AS user_name,
       department.name AS department_name, assignment.created_at
FROM activities.activity_assignments assignment
LEFT JOIN identity.users user_account ON user_account.id = assignment.user_id
LEFT JOIN tenancy.teams department
  ON department.workspace_id = assignment.workspace_id AND department.id = assignment.department_id
WHERE assignment.workspace_id = $1 AND assignment.activity_id = $2
ORDER BY assignment.assignment_kind, assignment.is_primary DESC,
         COALESCE(user_account.display_name, department.name), assignment.id
`

type ListActivityAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActivityID  pgtype.UUID `json:"activity_id"`
}

type ListActivityAssignmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	UserName       *string            `json:"user_name"`
	DepartmentName *string            `json:"department_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListActivityAssignments(ctx context.Context, arg ListActivityAssignmentsParams) ([]ListActivityAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listActivityAssignments, arg.WorkspaceID, arg.ActivityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActivityAssignmentsRow{}
	for rows.Next() {
		var i ListActivityAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentKind,
			&i.UserID,
			&i.DepartmentID,
			&i.IsPrimary,
			&i.UserName,
			&i.DepartmentName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentDepartmentOptions = `-- name: ListAssignmentDepartmentOptions :many
SELECT department.id, department.name
FROM tenancy.teams department
WHERE department.workspace_id = $1
ORDER BY department.name, department.id
LIMIT 500
`

type ListAssignmentDepartmentOptionsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListAssignmentDepartmentOptions(ctx context.Context, workspaceID pgtype.UUID) ([]ListAssignmentDepartmentOptionsRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentDepartmentOptions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentDepartmentOptionsRow{}
	for rows.Next() {
		var i ListAssignmentDepartmentOptionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAssignmentUserOptions = `-- name: ListAssignmentUserOptions :many
SELECT membership.user_id AS id, user_account.display_name AS name
FROM tenancy.memberships membership
JOIN identity.users user_account ON user_account.id = membership.user_id
WHERE membership.workspace_id = $1 AND membership.status = 'active'
ORDER BY user_account.display_name, membership.user_id
LIMIT 500
`

type ListAssignmentUserOptionsRow struct {
	ID   pgtype.UUID `json:"id"`
	Name string      `json:"name"`
}

func (q *Queries) ListAssignmentUserOptions(ctx context.Context, workspaceID pgtype.UUID) ([]ListAssignmentUserOptionsRow, error) {
	rows, err := q.db.Query(ctx, listAssignmentUserOptions, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAssignmentUserOptionsRow{}
	for rows.Next() {
		var i ListAssignmentUserOptionsRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDealAssignments = `-- name: ListDealAssignments :many
SELECT assignment.id, assignment.assignment_kind, assignment.user_id,
       assignment.department_id, assignment.is_primary,
       user_account.display_name AS user_name,
       department.name AS department_name, assignment.created_at
FROM sales.deal_assignments assignment
LEFT JOIN identity.users user_account ON user_account.id = assignment.user_id
LEFT JOIN tenancy.teams department
  ON department.workspace_id = assignment.workspace_id AND department.id = assignment.department_id
WHERE assignment.workspace_id = $1 AND assignment.deal_id = $2
ORDER BY assignment.assignment_kind, assignment.is_primary DESC,
         COALESCE(user_account.display_name, department.name), assignment.id
`

type ListDealAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	DealID      pgtype.UUID `json:"deal_id"`
}

type ListDealAssignmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	UserName       *string            `json:"user_name"`
	DepartmentName *string            `json:"department_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListDealAssignments(ctx context.Context, arg ListDealAssignmentsParams) ([]ListDealAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listDealAssignments, arg.WorkspaceID, arg.DealID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealAssignmentsRow{}
	for rows.Next() {
		var i ListDealAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentKind,
			&i.UserID,
			&i.DepartmentID,
			&i.IsPrimary,
			&i.UserName,
			&i.DepartmentName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLeadAssignments = `-- name: ListLeadAssignments :many
SELECT assignment.id, assignment.assignment_kind, assignment.user_id,
       assignment.department_id, assignment.is_primary,
       user_account.display_name AS user_name,
       department.name AS department_name, assignment.created_at
FROM sales.lead_assignments assignment
LEFT JOIN identity.users user_account ON user_account.id = assignment.user_id
LEFT JOIN tenancy.teams department
  ON department.workspace_id = assignment.workspace_id AND department.id = assignment.department_id
WHERE assignment.workspace_id = $1 AND assignment.lead_id = $2
ORDER BY assignment.assignment_kind, assignment.is_primary DESC,
         COALESCE(user_account.display_name, department.name), assignment.id
`

type ListLeadAssignmentsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	LeadID      pgtype.UUID `json:"lead_id"`
}

type ListLeadAssignmentsRow struct {
	ID             pgtype.UUID        `json:"id"`
	AssignmentKind string             `json:"assignment_kind"`
	UserID         pgtype.UUID        `json:"user_id"`
	DepartmentID   pgtype.UUID        `json:"department_id"`
	IsPrimary      bool               `json:"is_primary"`
	UserName       *string            `json:"user_name"`
	DepartmentName *string            `json:"department_name"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListLeadAssignments(ctx context.Context, arg ListLeadAssignmentsParams) ([]ListLeadAssignmentsRow, error) {
	rows, err := q.db.Query(ctx, listLeadAssignments, arg.WorkspaceID, arg.LeadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadAssignmentsRow{}
	for rows.Next() {
		var i ListLeadAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.AssignmentKind,
			&i.UserID,
			&i.DepartmentID,
			&i.IsPrimary,
			&i.UserName,
			&i.DepartmentName,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockTaskForAssignmentUpdate = `-- name: LockTaskForAssignmentUpdate :one
SELECT activity.version
FROM activities.activities activity
WHERE activity.workspace_id = $1
  AND activity.id = $2
  AND activity.activity_type = 'task'
  AND activity.deleted_at IS NULL
  AND (
    activity.created_by = $3
    OR activity.assignee_user_id = $3
    OR security.activity_responsible_allows(activity.workspace_id, activity.id, $3)
    OR $4::text IN ('owner', 'admin')
  )
FOR UPDATE
`

type LockTaskForAssignmentUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ActivityID  pgtype.UUID `json:"activity_id"`
	ActorUserID pgtype.UUID `json:"actor_user_id"`
	ActorRole   string      `json:"actor_role"`
}

func (q *Queries) LockTaskForAssignmentUpdate(ctx context.Context, arg LockTaskForAssignmentUpdateParams) (int64, error) {
	row := q.db.QueryRow(ctx, lockTaskForAssignmentUpdate,
		arg.WorkspaceID,
		arg.ActivityID,
		arg.ActorUserID,
		arg.ActorRole,
	)
	var version int64
	err := row.Scan(&version)
	return version, err
}
