// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reporting_advanced.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDashboardPreferences = `-- name: GetDashboardPreferences :one
SELECT preference.preferences, preference.period_days, preference.timezone,
       preference.version, preference.updated_at,
       workspace.timezone AS workspace_timezone
FROM tenancy.workspaces workspace
LEFT JOIN reporting.dashboard_preferences preference
  ON preference.workspace_id = workspace.id
 AND preference.user_id = $1
WHERE workspace.id = $2
`

type GetDashboardPreferencesParams struct {
	UserID      pgtype.UUID `json:"user_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

type GetDashboardPreferencesRow struct {
	Preferences       []byte             `json:"preferences"`
	PeriodDays        *int16             `json:"period_days"`
	Timezone          *string            `json:"timezone"`
	Version           *int64             `json:"version"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	WorkspaceTimezone string             `json:"workspace_timezone"`
}

func (q *Queries) GetDashboardPreferences(ctx context.Context, arg GetDashboardPreferencesParams) (GetDashboardPreferencesRow, error) {
	row := q.db.QueryRow(ctx, getDashboardPreferences, arg.UserID, arg.WorkspaceID)
	var i GetDashboardPreferencesRow
	err := row.Scan(
		&i.Preferences,
		&i.PeriodDays,
		&i.Timezone,
		&i.Version,
		&i.UpdatedAt,
		&i.WorkspaceTimezone,
	)
	return i, err
}

const getPeriodReportOverview = `-- name: GetPeriodReportOverview :one
SELECT
  (SELECT count(*)::bigint
   FROM sales.deals deal
   WHERE deal.workspace_id = $1
     AND deal.deleted_at IS NULL
     AND deal.updated_at >= $2::timestamptz
     AND deal.updated_at < $3::timestamptz
     AND deal.status = 'won') AS won_count,
  (SELECT count(*)::bigint
   FROM sales.deals deal
   WHERE deal.workspace_id = $1
     AND deal.deleted_at IS NULL
     AND deal.updated_at >= $2::timestamptz
     AND deal.updated_at < $3::timestamptz
     AND deal.status = 'lost') AS lost_count,
  (SELECT COALESCE(sum(deal.amount_minor), 0)::bigint
   FROM sales.deals deal
   WHERE deal.workspace_id = $1
     AND deal.deleted_at IS NULL
     AND deal.updated_at >= $2::timestamptz
     AND deal.updated_at < $3::timestamptz
     AND deal.status = 'won') AS won_value_minor,
  (SELECT count(*)::bigint
   FROM sales.leads lead
   WHERE lead.workspace_id = $1
     AND lead.deleted_at IS NULL
     AND lead.created_at >= $2::timestamptz
     AND lead.created_at < $3::timestamptz) AS lead_count,
  (SELECT count(*)::bigint
   FROM sales.leads lead
   WHERE lead.workspace_id = $1
     AND lead.deleted_at IS NULL
     AND lead.created_at >= $2::timestamptz
     AND lead.created_at < $3::timestamptz
     AND lead.status = 'converted') AS converted_lead_count,
  (SELECT count(*)::bigint
   FROM activities.activities activity
   WHERE activity.workspace_id = $1
     AND activity.deleted_at IS NULL
     AND activity.occurred_at >= $2::timestamptz
     AND activity.occurred_at < $3::timestamptz) AS activity_count
`

type GetPeriodReportOverviewParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type GetPeriodReportOverviewRow struct {
	WonCount           int64 `json:"won_count"`
	LostCount          int64 `json:"lost_count"`
	WonValueMinor      int64 `json:"won_value_minor"`
	LeadCount          int64 `json:"lead_count"`
	ConvertedLeadCount int64 `json:"converted_lead_count"`
	ActivityCount      int64 `json:"activity_count"`
}

func (q *Queries) GetPeriodReportOverview(ctx context.Context, arg GetPeriodReportOverviewParams) (GetPeriodReportOverviewRow, error) {
	row := q.db.QueryRow(ctx, getPeriodReportOverview, arg.WorkspaceID, arg.PeriodStart, arg.PeriodEnd)
	var i GetPeriodReportOverviewRow
	err := row.Scan(
		&i.WonCount,
		&i.LostCount,
		&i.WonValueMinor,
		&i.LeadCount,
		&i.ConvertedLeadCount,
		&i.ActivityCount,
	)
	return i, err
}

const listDashboardRecentActivity = `-- name: ListDashboardRecentActivity :many
SELECT id, activity_type, title, related_type, related_id, status, priority,
       occurred_at, due_at, assignee_user_id
FROM activities.activities
WHERE workspace_id = $1
  AND deleted_at IS NULL
  AND occurred_at >= $2::timestamptz
  AND occurred_at < $3::timestamptz
ORDER BY occurred_at DESC, id DESC
LIMIT $4
`

type ListDashboardRecentActivityParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	ResultLimit int32              `json:"result_limit"`
}

type ListDashboardRecentActivityRow struct {
	ID             pgtype.UUID        `json:"id"`
	ActivityType   string             `json:"activity_type"`
	Title          string             `json:"title"`
	RelatedType    *string            `json:"related_type"`
	RelatedID      pgtype.UUID        `json:"related_id"`
	Status         string             `json:"status"`
	Priority       string             `json:"priority"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	DueAt          pgtype.Timestamptz `json:"due_at"`
	AssigneeUserID pgtype.UUID        `json:"assignee_user_id"`
}

func (q *Queries) ListDashboardRecentActivity(ctx context.Context, arg ListDashboardRecentActivityParams) ([]ListDashboardRecentActivityRow, error) {
	rows, err := q.db.Query(ctx, listDashboardRecentActivity,
		arg.WorkspaceID,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.ResultLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDashboardRecentActivityRow{}
	for rows.Next() {
		var i ListDashboardRecentActivityRow
		if err := rows.Scan(
			&i.ID,
			&i.ActivityType,
			&i.Title,
			&i.RelatedType,
			&i.RelatedID,
			&i.Status,
			&i.Priority,
			&i.OccurredAt,
			&i.DueAt,
			&i.AssigneeUserID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportActivitiesByDay = `-- name: ReportActivitiesByDay :many
SELECT (date_trunc(
          'day', activity.occurred_at AT TIME ZONE $1::text
       ))::date AS activity_date,
       count(*)::bigint AS activity_count,
       count(*) FILTER (WHERE activity.activity_type = 'task')::bigint AS task_count,
       count(*) FILTER (WHERE activity.activity_type = 'call')::bigint AS call_count,
       count(*) FILTER (WHERE activity.activity_type = 'meeting')::bigint AS meeting_count,
       count(*) FILTER (WHERE activity.activity_type = 'note')::bigint AS note_count
FROM activities.activities activity
WHERE activity.workspace_id = $2
  AND activity.deleted_at IS NULL
  AND activity.occurred_at >= $3::timestamptz
  AND activity.occurred_at < $4::timestamptz
GROUP BY activity_date
ORDER BY activity_date
LIMIT 366
`

type ReportActivitiesByDayParams struct {
	Timezone    string             `json:"timezone"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ReportActivitiesByDayRow struct {
	ActivityDate  pgtype.Date `json:"activity_date"`
	ActivityCount int64       `json:"activity_count"`
	TaskCount     int64       `json:"task_count"`
	CallCount     int64       `json:"call_count"`
	MeetingCount  int64       `json:"meeting_count"`
	NoteCount     int64       `json:"note_count"`
}

func (q *Queries) ReportActivitiesByDay(ctx context.Context, arg ReportActivitiesByDayParams) ([]ReportActivitiesByDayRow, error) {
	rows, err := q.db.Query(ctx, reportActivitiesByDay,
		arg.Timezone,
		arg.WorkspaceID,
		arg.PeriodStart,
		arg.PeriodEnd,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportActivitiesByDayRow{}
	for rows.Next() {
		var i ReportActivitiesByDayRow
		if err := rows.Scan(
			&i.ActivityDate,
			&i.ActivityCount,
			&i.TaskCount,
			&i.CallCount,
			&i.MeetingCount,
			&i.NoteCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDealsByOwner = `-- name: ReportDealsByOwner :many
SELECT deal.owner_user_id,
       COALESCE(users.display_name, '') AS owner_name,
       count(deal.id)::bigint AS deal_count,
       count(deal.id) FILTER (WHERE deal.status = 'won')::bigint AS won_count,
       count(deal.id) FILTER (WHERE deal.status = 'lost')::bigint AS lost_count,
       COALESCE(sum(deal.amount_minor), 0)::bigint AS amount_minor
FROM sales.deals deal
LEFT JOIN identity.users users ON users.id = deal.owner_user_id
WHERE deal.workspace_id = $1
  AND deal.deleted_at IS NULL
  AND deal.updated_at >= $2::timestamptz
  AND deal.updated_at < $3::timestamptz
GROUP BY deal.owner_user_id, users.display_name
ORDER BY amount_minor DESC, owner_name, deal.owner_user_id
LIMIT 500
`

type ReportDealsByOwnerParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ReportDealsByOwnerRow struct {
	OwnerUserID pgtype.UUID `json:"owner_user_id"`
	OwnerName   string      `json:"owner_name"`
	DealCount   int64       `json:"deal_count"`
	WonCount    int64       `json:"won_count"`
	LostCount   int64       `json:"lost_count"`
	AmountMinor int64       `json:"amount_minor"`
}

func (q *Queries) ReportDealsByOwner(ctx context.Context, arg ReportDealsByOwnerParams) ([]ReportDealsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, reportDealsByOwner, arg.WorkspaceID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDealsByOwnerRow{}
	for rows.Next() {
		var i ReportDealsByOwnerRow
		if err := rows.Scan(
			&i.OwnerUserID,
			&i.OwnerName,
			&i.DealCount,
			&i.WonCount,
			&i.LostCount,
			&i.AmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportDealsByStage = `-- name: ReportDealsByStage :many
SELECT stage.id AS stage_id, stage.name AS stage_name, stage.position,
       count(deal.id)::bigint AS deal_count,
       COALESCE(sum(deal.amount_minor), 0)::bigint AS amount_minor,
       COALESCE(sum((deal.amount_minor * stage.probability) / 100), 0)::bigint
         AS weighted_amount_minor
FROM sales.pipeline_stages stage
LEFT JOIN sales.deals deal
  ON deal.workspace_id = stage.workspace_id
 AND deal.stage_id = stage.id
 AND deal.deleted_at IS NULL
 AND deal.updated_at >= $1::timestamptz
 AND deal.updated_at < $2::timestamptz
WHERE stage.workspace_id = $3
GROUP BY stage.id, stage.name, stage.position
ORDER BY stage.position, stage.id
LIMIT 200
`

type ReportDealsByStageParams struct {
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
}

type ReportDealsByStageRow struct {
	StageID             pgtype.UUID `json:"stage_id"`
	StageName           string      `json:"stage_name"`
	Position            int32       `json:"position"`
	DealCount           int64       `json:"deal_count"`
	AmountMinor         int64       `json:"amount_minor"`
	WeightedAmountMinor int64       `json:"weighted_amount_minor"`
}

func (q *Queries) ReportDealsByStage(ctx context.Context, arg ReportDealsByStageParams) ([]ReportDealsByStageRow, error) {
	rows, err := q.db.Query(ctx, reportDealsByStage, arg.PeriodStart, arg.PeriodEnd, arg.WorkspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportDealsByStageRow{}
	for rows.Next() {
		var i ReportDealsByStageRow
		if err := rows.Scan(
			&i.StageID,
			&i.StageName,
			&i.Position,
			&i.DealCount,
			&i.AmountMinor,
			&i.WeightedAmountMinor,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const reportLeadSources = `-- name: ReportLeadSources :many
SELECT COALESCE(NULLIF(trim(lead.source), ''), 'unspecified')::text AS source,
       count(*)::bigint AS lead_count,
       count(*) FILTER (WHERE lead.status = 'converted')::bigint AS converted_count
FROM sales.leads lead
WHERE lead.workspace_id = $1
  AND lead.deleted_at IS NULL
  AND lead.created_at >= $2::timestamptz
  AND lead.created_at < $3::timestamptz
GROUP BY COALESCE(NULLIF(trim(lead.source), ''), 'unspecified')
ORDER BY lead_count DESC, source
LIMIT 100
`

type ReportLeadSourcesParams struct {
	WorkspaceID pgtype.UUID        `json:"workspace_id"`
	PeriodStart pgtype.Timestamptz `json:"period_start"`
	PeriodEnd   pgtype.Timestamptz `json:"period_end"`
}

type ReportLeadSourcesRow struct {
	Source         string `json:"source"`
	LeadCount      int64  `json:"lead_count"`
	ConvertedCount int64  `json:"converted_count"`
}

func (q *Queries) ReportLeadSources(ctx context.Context, arg ReportLeadSourcesParams) ([]ReportLeadSourcesRow, error) {
	rows, err := q.db.Query(ctx, reportLeadSources, arg.WorkspaceID, arg.PeriodStart, arg.PeriodEnd)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ReportLeadSourcesRow{}
	for rows.Next() {
		var i ReportLeadSourcesRow
		if err := rows.Scan(&i.Source, &i.LeadCount, &i.ConvertedCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const saveDashboardPreferences = `-- name: SaveDashboardPreferences :one
INSERT INTO reporting.dashboard_preferences (
  workspace_id, user_id, preferences, period_days, timezone
) VALUES (
  $1, $2, $3,
  $4, $5
)
ON CONFLICT (workspace_id, user_id) DO UPDATE
SET preferences = EXCLUDED.preferences,
    period_days = EXCLUDED.period_days,
    timezone = EXCLUDED.timezone,
    version = reporting.dashboard_preferences.version + 1,
    updated_at = now()
WHERE reporting.dashboard_preferences.version = $6
RETURNING preferences, period_days, timezone, version, updated_at
`

type SaveDashboardPreferencesParams struct {
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	UserID          pgtype.UUID `json:"user_id"`
	Preferences     []byte      `json:"preferences"`
	PeriodDays      int16       `json:"period_days"`
	Timezone        *string     `json:"timezone"`
	ExpectedVersion int64       `json:"expected_version"`
}

type SaveDashboardPreferencesRow struct {
	Preferences []byte             `json:"preferences"`
	PeriodDays  int16              `json:"period_days"`
	Timezone    *string            `json:"timezone"`
	Version     int64              `json:"version"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) SaveDashboardPreferences(ctx context.Context, arg SaveDashboardPreferencesParams) (SaveDashboardPreferencesRow, error) {
	row := q.db.QueryRow(ctx, saveDashboardPreferences,
		arg.WorkspaceID,
		arg.UserID,
		arg.Preferences,
		arg.PeriodDays,
		arg.Timezone,
		arg.ExpectedVersion,
	)
	var i SaveDashboardPreferencesRow
	err := row.Scan(
		&i.Preferences,
		&i.PeriodDays,
		&i.Timezone,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}
