// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: roles.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const assignMembershipWorkspaceRole = `-- name: AssignMembershipWorkspaceRole :one
UPDATE tenancy.memberships membership
SET role_id = role.id, role = role.base_role, updated_at = now()
FROM tenancy.workspace_roles role
WHERE membership.workspace_id = $1
  AND membership.id = $2
  AND role.workspace_id = membership.workspace_id
  AND role.id = $3
  AND membership.role <> 'owner'
  AND role.base_role <> 'owner'
RETURNING membership.workspace_id, membership.id, membership.user_id, membership.role,
          membership.status, membership.locale_override, membership.timezone_override,
          membership.created_at, membership.updated_at, membership.role_id
`

type AssignMembershipWorkspaceRoleParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
	RoleID       pgtype.UUID `json:"role_id"`
}

func (q *Queries) AssignMembershipWorkspaceRole(ctx context.Context, arg AssignMembershipWorkspaceRoleParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, assignMembershipWorkspaceRole, arg.WorkspaceID, arg.MembershipID, arg.RoleID)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const createWorkspaceRole = `-- name: CreateWorkspaceRole :one
INSERT INTO tenancy.workspace_roles (
  workspace_id, id, role_key, name, base_role, is_system
) VALUES ($1, $2, $3, $4, $5, false)
RETURNING id, role_key, name, base_role, is_system, version, created_at, updated_at
`

type CreateWorkspaceRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	RoleKey     string      `json:"role_key"`
	Name        string      `json:"name"`
	BaseRole    string      `json:"base_role"`
}

type CreateWorkspaceRoleRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoleKey   string             `json:"role_key"`
	Name      string             `json:"name"`
	BaseRole  string             `json:"base_role"`
	IsSystem  bool               `json:"is_system"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateWorkspaceRole(ctx context.Context, arg CreateWorkspaceRoleParams) (CreateWorkspaceRoleRow, error) {
	row := q.db.QueryRow(ctx, createWorkspaceRole,
		arg.WorkspaceID,
		arg.ID,
		arg.RoleKey,
		arg.Name,
		arg.BaseRole,
	)
	var i CreateWorkspaceRoleRow
	err := row.Scan(
		&i.ID,
		&i.RoleKey,
		&i.Name,
		&i.BaseRole,
		&i.IsSystem,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteWorkspaceRole = `-- name: DeleteWorkspaceRole :execrows
DELETE FROM tenancy.workspace_roles
WHERE workspace_id = $1 AND id = $2 AND version = $3 AND NOT is_system
`

type DeleteWorkspaceRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Version     int64       `json:"version"`
}

func (q *Queries) DeleteWorkspaceRole(ctx context.Context, arg DeleteWorkspaceRoleParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteWorkspaceRole, arg.WorkspaceID, arg.ID, arg.Version)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteWorkspaceRolePermissions = `-- name: DeleteWorkspaceRolePermissions :exec
DELETE FROM tenancy.role_permissions
WHERE workspace_id = $1 AND role_id = $2
`

type DeleteWorkspaceRolePermissionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RoleID      pgtype.UUID `json:"role_id"`
}

func (q *Queries) DeleteWorkspaceRolePermissions(ctx context.Context, arg DeleteWorkspaceRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, deleteWorkspaceRolePermissions, arg.WorkspaceID, arg.RoleID)
	return err
}

const getWorkspaceRoleForUpdate = `-- name: GetWorkspaceRoleForUpdate :one
SELECT id, role_key, name, base_role, is_system, version, created_at, updated_at
FROM tenancy.workspace_roles
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type GetWorkspaceRoleForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetWorkspaceRoleForUpdateRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoleKey   string             `json:"role_key"`
	Name      string             `json:"name"`
	BaseRole  string             `json:"base_role"`
	IsSystem  bool               `json:"is_system"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetWorkspaceRoleForUpdate(ctx context.Context, arg GetWorkspaceRoleForUpdateParams) (GetWorkspaceRoleForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceRoleForUpdate, arg.WorkspaceID, arg.ID)
	var i GetWorkspaceRoleForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.RoleKey,
		&i.Name,
		&i.BaseRole,
		&i.IsSystem,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertWorkspaceRolePermissions = `-- name: InsertWorkspaceRolePermissions :exec
INSERT INTO tenancy.role_permissions (workspace_id, role_id, permission)
SELECT $1, $2, permission
FROM unnest($3::text[]) AS permission
`

type InsertWorkspaceRolePermissionsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	RoleID      pgtype.UUID `json:"role_id"`
	Permissions []string    `json:"permissions"`
}

func (q *Queries) InsertWorkspaceRolePermissions(ctx context.Context, arg InsertWorkspaceRolePermissionsParams) error {
	_, err := q.db.Exec(ctx, insertWorkspaceRolePermissions, arg.WorkspaceID, arg.RoleID, arg.Permissions)
	return err
}

const listMembershipPermissions = `-- name: ListMembershipPermissions :many
SELECT permission.permission
FROM tenancy.memberships membership
JOIN tenancy.role_permissions permission
  ON permission.workspace_id = membership.workspace_id
 AND permission.role_id = membership.role_id
WHERE membership.workspace_id = $1
  AND membership.id = $2
  AND membership.status = 'active'
ORDER BY permission.permission
`

type ListMembershipPermissionsParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

func (q *Queries) ListMembershipPermissions(ctx context.Context, arg ListMembershipPermissionsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listMembershipPermissions, arg.WorkspaceID, arg.MembershipID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var permission string
		if err := rows.Scan(&permission); err != nil {
			return nil, err
		}
		items = append(items, permission)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceRoles = `-- name: ListWorkspaceRoles :many
SELECT role.id, role.role_key, role.name, role.base_role, role.is_system, role.version,
       role.created_at, role.updated_at,
       COALESCE(array_agg(permission.permission ORDER BY permission.permission)
         FILTER (WHERE permission.permission IS NOT NULL), ARRAY[]::text[])::text[] AS permissions
FROM tenancy.workspace_roles role
LEFT JOIN tenancy.role_permissions permission
  ON permission.workspace_id = role.workspace_id AND permission.role_id = role.id
WHERE role.workspace_id = $1
GROUP BY role.workspace_id, role.id
ORDER BY role.is_system DESC, role.name, role.id
`

type ListWorkspaceRolesRow struct {
	ID          pgtype.UUID        `json:"id"`
	RoleKey     string             `json:"role_key"`
	Name        string             `json:"name"`
	BaseRole    string             `json:"base_role"`
	IsSystem    bool               `json:"is_system"`
	Version     int64              `json:"version"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	Permissions []string           `json:"permissions"`
}

func (q *Queries) ListWorkspaceRoles(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceRolesRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceRoles, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceRolesRow{}
	for rows.Next() {
		var i ListWorkspaceRolesRow
		if err := rows.Scan(
			&i.ID,
			&i.RoleKey,
			&i.Name,
			&i.BaseRole,
			&i.IsSystem,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Permissions,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWorkspaceRole = `-- name: UpdateWorkspaceRole :one
UPDATE tenancy.workspace_roles
SET name = $3, base_role = $4, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $5 AND NOT is_system
RETURNING id, role_key, name, base_role, is_system, version, created_at, updated_at
`

type UpdateWorkspaceRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	BaseRole    string      `json:"base_role"`
	Version     int64       `json:"version"`
}

type UpdateWorkspaceRoleRow struct {
	ID        pgtype.UUID        `json:"id"`
	RoleKey   string             `json:"role_key"`
	Name      string             `json:"name"`
	BaseRole  string             `json:"base_role"`
	IsSystem  bool               `json:"is_system"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWorkspaceRole(ctx context.Context, arg UpdateWorkspaceRoleParams) (UpdateWorkspaceRoleRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceRole,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.BaseRole,
		arg.Version,
	)
	var i UpdateWorkspaceRoleRow
	err := row.Scan(
		&i.ID,
		&i.RoleKey,
		&i.Name,
		&i.BaseRole,
		&i.IsSystem,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
