// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addDealStageHistory = `-- name: AddDealStageHistory :exec
INSERT INTO sales.deal_stage_history (
  workspace_id, id, deal_id, from_stage_id, to_stage_id, changed_by
) VALUES ($1, $2, $3, $4, $5, $6)
`

type AddDealStageHistoryParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	DealID      pgtype.UUID `json:"deal_id"`
	FromStageID pgtype.UUID `json:"from_stage_id"`
	ToStageID   pgtype.UUID `json:"to_stage_id"`
	ChangedBy   pgtype.UUID `json:"changed_by"`
}

func (q *Queries) AddDealStageHistory(ctx context.Context, arg AddDealStageHistoryParams) error {
	_, err := q.db.Exec(ctx, addDealStageHistory,
		arg.WorkspaceID,
		arg.ID,
		arg.DealID,
		arg.FromStageID,
		arg.ToStageID,
		arg.ChangedBy,
	)
	return err
}

const createDeal = `-- name: CreateDeal :one
INSERT INTO sales.deals (
  workspace_id, id, pipeline_id, stage_id, name, contact_id, company_id,
  owner_user_id, amount_minor, currency, planned_start_date, expected_close_date, position
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
RETURNING id, pipeline_id, stage_id, name, contact_id, company_id, owner_user_id,
          amount_minor, currency, planned_start_date, expected_close_date, position, status,
          lost_reason, version, created_at, updated_at
`

type CreateDealParams struct {
	WorkspaceID       pgtype.UUID `json:"workspace_id"`
	ID                pgtype.UUID `json:"id"`
	PipelineID        pgtype.UUID `json:"pipeline_id"`
	StageID           pgtype.UUID `json:"stage_id"`
	Name              string      `json:"name"`
	ContactID         pgtype.UUID `json:"contact_id"`
	CompanyID         pgtype.UUID `json:"company_id"`
	OwnerUserID       pgtype.UUID `json:"owner_user_id"`
	AmountMinor       int64       `json:"amount_minor"`
	Currency          string      `json:"currency"`
	PlannedStartDate  pgtype.Date `json:"planned_start_date"`
	ExpectedCloseDate pgtype.Date `json:"expected_close_date"`
	Position          int32       `json:"position"`
}

type CreateDealRow struct {
	ID                pgtype.UUID        `json:"id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	PlannedStartDate  pgtype.Date        `json:"planned_start_date"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          int32              `json:"position"`
	Status            string             `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreateDeal(ctx context.Context, arg CreateDealParams) (CreateDealRow, error) {
	row := q.db.QueryRow(ctx, createDeal,
		arg.WorkspaceID,
		arg.ID,
		arg.PipelineID,
		arg.StageID,
		arg.Name,
		arg.ContactID,
		arg.CompanyID,
		arg.OwnerUserID,
		arg.AmountMinor,
		arg.Currency,
		arg.PlannedStartDate,
		arg.ExpectedCloseDate,
		arg.Position,
	)
	var i CreateDealRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.PlannedStartDate,
		&i.ExpectedCloseDate,
		&i.Position,
		&i.Status,
		&i.LostReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipeline = `-- name: CreatePipeline :one
INSERT INTO sales.pipelines (workspace_id, id, name, is_default)
VALUES ($1, $2, $3, $4)
RETURNING id, name, is_default, version, created_at, updated_at
`

type CreatePipelineParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
	IsDefault   bool        `json:"is_default"`
}

type CreatePipelineRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePipeline(ctx context.Context, arg CreatePipelineParams) (CreatePipelineRow, error) {
	row := q.db.QueryRow(ctx, createPipeline,
		arg.WorkspaceID,
		arg.ID,
		arg.Name,
		arg.IsDefault,
	)
	var i CreatePipelineRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsDefault,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPipelineStage = `-- name: CreatePipelineStage :one
INSERT INTO sales.pipeline_stages (
  workspace_id, id, pipeline_id, name, probability, forecast_category, position
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, pipeline_id, name, probability, forecast_category, position,
          created_at, updated_at
`

type CreatePipelineStageParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	PipelineID       pgtype.UUID `json:"pipeline_id"`
	Name             string      `json:"name"`
	Probability      int16       `json:"probability"`
	ForecastCategory string      `json:"forecast_category"`
	Position         int32       `json:"position"`
}

type CreatePipelineStageRow struct {
	ID               pgtype.UUID        `json:"id"`
	PipelineID       pgtype.UUID        `json:"pipeline_id"`
	Name             string             `json:"name"`
	Probability      int16              `json:"probability"`
	ForecastCategory string             `json:"forecast_category"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) CreatePipelineStage(ctx context.Context, arg CreatePipelineStageParams) (CreatePipelineStageRow, error) {
	row := q.db.QueryRow(ctx, createPipelineStage,
		arg.WorkspaceID,
		arg.ID,
		arg.PipelineID,
		arg.Name,
		arg.Probability,
		arg.ForecastCategory,
		arg.Position,
	)
	var i CreatePipelineStageRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Probability,
		&i.ForecastCategory,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeal = `-- name: GetDeal :one
SELECT id, pipeline_id, stage_id, name, contact_id, company_id, owner_user_id,
       amount_minor, currency, planned_start_date, expected_close_date, position, status, lost_reason,
       custom_fields, version, created_at, updated_at
FROM sales.deals deal
WHERE deal.workspace_id = $1 AND deal.id = $2 AND deal.deleted_at IS NULL
  AND sales.pipeline_stage_access_allowed(deal.workspace_id, deal.stage_id, 'view')
`

type GetDealParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetDealRow struct {
	ID                pgtype.UUID        `json:"id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	PlannedStartDate  pgtype.Date        `json:"planned_start_date"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          int32              `json:"position"`
	Status            string             `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	CustomFields      []byte             `json:"custom_fields"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetDeal(ctx context.Context, arg GetDealParams) (GetDealRow, error) {
	row := q.db.QueryRow(ctx, getDeal, arg.WorkspaceID, arg.ID)
	var i GetDealRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.PlannedStartDate,
		&i.ExpectedCloseDate,
		&i.Position,
		&i.Status,
		&i.LostReason,
		&i.CustomFields,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPipelineStage = `-- name: GetPipelineStage :one
SELECT id, pipeline_id, name, probability, forecast_category, position,
       created_at, updated_at
FROM sales.pipeline_stages
WHERE workspace_id = $1 AND pipeline_id = $2 AND id = $3
`

type GetPipelineStageParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PipelineID  pgtype.UUID `json:"pipeline_id"`
	ID          pgtype.UUID `json:"id"`
}

type GetPipelineStageRow struct {
	ID               pgtype.UUID        `json:"id"`
	PipelineID       pgtype.UUID        `json:"pipeline_id"`
	Name             string             `json:"name"`
	Probability      int16              `json:"probability"`
	ForecastCategory string             `json:"forecast_category"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetPipelineStage(ctx context.Context, arg GetPipelineStageParams) (GetPipelineStageRow, error) {
	row := q.db.QueryRow(ctx, getPipelineStage, arg.WorkspaceID, arg.PipelineID, arg.ID)
	var i GetPipelineStageRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.Name,
		&i.Probability,
		&i.ForecastCategory,
		&i.Position,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listDeals = `-- name: ListDeals :many
SELECT id, pipeline_id, stage_id, name, contact_id, company_id, owner_user_id,
       amount_minor, currency, planned_start_date, expected_close_date, position, status, lost_reason,
       version, created_at, updated_at
FROM sales.deals deal
WHERE deal.workspace_id = $1
  AND deal.deleted_at IS NULL
  AND sales.pipeline_stage_access_allowed(deal.workspace_id, deal.stage_id, 'view')
  AND ($2::uuid IS NULL OR deal.pipeline_id = $2)
  AND ($3::uuid IS NULL OR deal.stage_id = $3)
  AND (deal.updated_at, deal.id) < ($4::timestamptz, $5::uuid)
ORDER BY deal.updated_at DESC, deal.id DESC
LIMIT $6
`

type ListDealsParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	PipelineID      pgtype.UUID        `json:"pipeline_id"`
	StageID         pgtype.UUID        `json:"stage_id"`
	CursorUpdatedAt pgtype.Timestamptz `json:"cursor_updated_at"`
	CursorID        pgtype.UUID        `json:"cursor_id"`
	PageLimit       int32              `json:"page_limit"`
}

type ListDealsRow struct {
	ID                pgtype.UUID        `json:"id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	PlannedStartDate  pgtype.Date        `json:"planned_start_date"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          int32              `json:"position"`
	Status            string             `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListDeals(ctx context.Context, arg ListDealsParams) ([]ListDealsRow, error) {
	rows, err := q.db.Query(ctx, listDeals,
		arg.WorkspaceID,
		arg.PipelineID,
		arg.StageID,
		arg.CursorUpdatedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDealsRow{}
	for rows.Next() {
		var i ListDealsRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.StageID,
			&i.Name,
			&i.ContactID,
			&i.CompanyID,
			&i.OwnerUserID,
			&i.AmountMinor,
			&i.Currency,
			&i.PlannedStartDate,
			&i.ExpectedCloseDate,
			&i.Position,
			&i.Status,
			&i.LostReason,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineStages = `-- name: ListPipelineStages :many
SELECT id, pipeline_id, name, probability, forecast_category, position,
       created_at, updated_at
FROM sales.pipeline_stages stage
WHERE stage.workspace_id = $1 AND stage.pipeline_id = $2
  AND sales.pipeline_stage_access_allowed(stage.workspace_id, stage.id, 'view')
ORDER BY position, id
`

type ListPipelineStagesParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PipelineID  pgtype.UUID `json:"pipeline_id"`
}

type ListPipelineStagesRow struct {
	ID               pgtype.UUID        `json:"id"`
	PipelineID       pgtype.UUID        `json:"pipeline_id"`
	Name             string             `json:"name"`
	Probability      int16              `json:"probability"`
	ForecastCategory string             `json:"forecast_category"`
	Position         int32              `json:"position"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPipelineStages(ctx context.Context, arg ListPipelineStagesParams) ([]ListPipelineStagesRow, error) {
	rows, err := q.db.Query(ctx, listPipelineStages, arg.WorkspaceID, arg.PipelineID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelineStagesRow{}
	for rows.Next() {
		var i ListPipelineStagesRow
		if err := rows.Scan(
			&i.ID,
			&i.PipelineID,
			&i.Name,
			&i.Probability,
			&i.ForecastCategory,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelines = `-- name: ListPipelines :many
SELECT id, name, is_default, version, created_at, updated_at
FROM sales.pipelines
WHERE workspace_id = $1
ORDER BY is_default DESC, name, id
`

type ListPipelinesRow struct {
	ID        pgtype.UUID        `json:"id"`
	Name      string             `json:"name"`
	IsDefault bool               `json:"is_default"`
	Version   int64              `json:"version"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPipelines(ctx context.Context, workspaceID pgtype.UUID) ([]ListPipelinesRow, error) {
	rows, err := q.db.Query(ctx, listPipelines, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelinesRow{}
	for rows.Next() {
		var i ListPipelinesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsDefault,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const moveDeal = `-- name: MoveDeal :one
UPDATE sales.deals
SET stage_id = $3, position = $4, version = version + 1, updated_at = now()
WHERE workspace_id = $1 AND id = $2 AND version = $5 AND deleted_at IS NULL
RETURNING id, pipeline_id, stage_id, name, contact_id, company_id, owner_user_id,
          amount_minor, currency, planned_start_date, expected_close_date, position, status,
          lost_reason, version, created_at, updated_at
`

type MoveDealParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	StageID     pgtype.UUID `json:"stage_id"`
	Position    int32       `json:"position"`
	Version     int64       `json:"version"`
}

type MoveDealRow struct {
	ID                pgtype.UUID        `json:"id"`
	PipelineID        pgtype.UUID        `json:"pipeline_id"`
	StageID           pgtype.UUID        `json:"stage_id"`
	Name              string             `json:"name"`
	ContactID         pgtype.UUID        `json:"contact_id"`
	CompanyID         pgtype.UUID        `json:"company_id"`
	OwnerUserID       pgtype.UUID        `json:"owner_user_id"`
	AmountMinor       int64              `json:"amount_minor"`
	Currency          string             `json:"currency"`
	PlannedStartDate  pgtype.Date        `json:"planned_start_date"`
	ExpectedCloseDate pgtype.Date        `json:"expected_close_date"`
	Position          int32              `json:"position"`
	Status            string             `json:"status"`
	LostReason        *string            `json:"lost_reason"`
	Version           int64              `json:"version"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) MoveDeal(ctx context.Context, arg MoveDealParams) (MoveDealRow, error) {
	row := q.db.QueryRow(ctx, moveDeal,
		arg.WorkspaceID,
		arg.ID,
		arg.StageID,
		arg.Position,
		arg.Version,
	)
	var i MoveDealRow
	err := row.Scan(
		&i.ID,
		&i.PipelineID,
		&i.StageID,
		&i.Name,
		&i.ContactID,
		&i.CompanyID,
		&i.OwnerUserID,
		&i.AmountMinor,
		&i.Currency,
		&i.PlannedStartDate,
		&i.ExpectedCloseDate,
		&i.Position,
		&i.Status,
		&i.LostReason,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const nextDealPosition = `-- name: NextDealPosition :one
SELECT COALESCE(max(position), -1)::integer + 1
FROM sales.deals
WHERE workspace_id = $1 AND pipeline_id = $2 AND stage_id = $3
  AND status = 'open' AND deleted_at IS NULL
`

type NextDealPositionParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	PipelineID  pgtype.UUID `json:"pipeline_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) NextDealPosition(ctx context.Context, arg NextDealPositionParams) (int32, error) {
	row := q.db.QueryRow(ctx, nextDealPosition, arg.WorkspaceID, arg.PipelineID, arg.StageID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}
