// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: search_worker.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCompanySearchSource = `-- name: GetCompanySearchSource :one
SELECT name AS title, domain AS subtitle,
       concat_ws(' ', name, domain, industry) AS searchable_text,
       version
FROM customers.companies
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetCompanySearchSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

type GetCompanySearchSourceRow struct {
	Title          string  `json:"title"`
	Subtitle       *string `json:"subtitle"`
	SearchableText string  `json:"searchable_text"`
	Version        int64   `json:"version"`
}

func (q *Queries) GetCompanySearchSource(ctx context.Context, arg GetCompanySearchSourceParams) (GetCompanySearchSourceRow, error) {
	row := q.db.QueryRow(ctx, getCompanySearchSource, arg.WorkspaceID, arg.EntityID)
	var i GetCompanySearchSourceRow
	err := row.Scan(
		&i.Title,
		&i.Subtitle,
		&i.SearchableText,
		&i.Version,
	)
	return i, err
}

const getContactSearchSource = `-- name: GetContactSearchSource :one
SELECT display_name AS title, email AS subtitle,
       concat_ws(' ', display_name, email, phone) AS searchable_text,
       version
FROM customers.contacts
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetContactSearchSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

type GetContactSearchSourceRow struct {
	Title          string  `json:"title"`
	Subtitle       *string `json:"subtitle"`
	SearchableText string  `json:"searchable_text"`
	Version        int64   `json:"version"`
}

func (q *Queries) GetContactSearchSource(ctx context.Context, arg GetContactSearchSourceParams) (GetContactSearchSourceRow, error) {
	row := q.db.QueryRow(ctx, getContactSearchSource, arg.WorkspaceID, arg.EntityID)
	var i GetContactSearchSourceRow
	err := row.Scan(
		&i.Title,
		&i.Subtitle,
		&i.SearchableText,
		&i.Version,
	)
	return i, err
}

const getDealSearchSource = `-- name: GetDealSearchSource :one
SELECT name AS title, NULL::text AS subtitle, name AS searchable_text, version
FROM sales.deals
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetDealSearchSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

type GetDealSearchSourceRow struct {
	Title          string  `json:"title"`
	Subtitle       *string `json:"subtitle"`
	SearchableText string  `json:"searchable_text"`
	Version        int64   `json:"version"`
}

func (q *Queries) GetDealSearchSource(ctx context.Context, arg GetDealSearchSourceParams) (GetDealSearchSourceRow, error) {
	row := q.db.QueryRow(ctx, getDealSearchSource, arg.WorkspaceID, arg.EntityID)
	var i GetDealSearchSourceRow
	err := row.Scan(
		&i.Title,
		&i.Subtitle,
		&i.SearchableText,
		&i.Version,
	)
	return i, err
}

const getLeadSearchSource = `-- name: GetLeadSearchSource :one
SELECT name AS title, company_name AS subtitle,
       concat_ws(' ', name, email, company_name) AS searchable_text,
       version
FROM sales.leads
WHERE workspace_id = $1
  AND id = $2
  AND deleted_at IS NULL
`

type GetLeadSearchSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

type GetLeadSearchSourceRow struct {
	Title          string  `json:"title"`
	Subtitle       *string `json:"subtitle"`
	SearchableText string  `json:"searchable_text"`
	Version        int64   `json:"version"`
}

func (q *Queries) GetLeadSearchSource(ctx context.Context, arg GetLeadSearchSourceParams) (GetLeadSearchSourceRow, error) {
	row := q.db.QueryRow(ctx, getLeadSearchSource, arg.WorkspaceID, arg.EntityID)
	var i GetLeadSearchSourceRow
	err := row.Scan(
		&i.Title,
		&i.Subtitle,
		&i.SearchableText,
		&i.Version,
	)
	return i, err
}

const getNoteSearchSource = `-- name: GetNoteSearchSource :one
SELECT title, related_type AS subtitle,
       concat_ws(' ', title, body) AS searchable_text,
       version
FROM activities.activities
WHERE workspace_id = $1
  AND id = $2
  AND activity_type = 'note'
  AND deleted_at IS NULL
`

type GetNoteSearchSourceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EntityID    pgtype.UUID `json:"entity_id"`
}

type GetNoteSearchSourceRow struct {
	Title          string  `json:"title"`
	Subtitle       *string `json:"subtitle"`
	SearchableText string  `json:"searchable_text"`
	Version        int64   `json:"version"`
}

func (q *Queries) GetNoteSearchSource(ctx context.Context, arg GetNoteSearchSourceParams) (GetNoteSearchSourceRow, error) {
	row := q.db.QueryRow(ctx, getNoteSearchSource, arg.WorkspaceID, arg.EntityID)
	var i GetNoteSearchSourceRow
	err := row.Scan(
		&i.Title,
		&i.Subtitle,
		&i.SearchableText,
		&i.Version,
	)
	return i, err
}

const getSearchOutboxEvent = `-- name: GetSearchOutboxEvent :one
SELECT schema_version, aggregate_type, aggregate_id
FROM platform.outbox_events
WHERE workspace_id = $1
  AND id = $2
`

type GetSearchOutboxEventParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	EventID     pgtype.UUID `json:"event_id"`
}

type GetSearchOutboxEventRow struct {
	SchemaVersion int32       `json:"schema_version"`
	AggregateType string      `json:"aggregate_type"`
	AggregateID   pgtype.UUID `json:"aggregate_id"`
}

func (q *Queries) GetSearchOutboxEvent(ctx context.Context, arg GetSearchOutboxEventParams) (GetSearchOutboxEventRow, error) {
	row := q.db.QueryRow(ctx, getSearchOutboxEvent, arg.WorkspaceID, arg.EventID)
	var i GetSearchOutboxEventRow
	err := row.Scan(&i.SchemaVersion, &i.AggregateType, &i.AggregateID)
	return i, err
}
