// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stage_access.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLeadStageRoleAccess = `-- name: CreateLeadStageRoleAccess :exec
INSERT INTO sales.lead_stage_role_access (
  workspace_id, stage_id, role_id, can_view, can_enter, can_leave
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
`

type CreateLeadStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
	RoleID      pgtype.UUID `json:"role_id"`
	CanView     bool        `json:"can_view"`
	CanEnter    bool        `json:"can_enter"`
	CanLeave    bool        `json:"can_leave"`
}

func (q *Queries) CreateLeadStageRoleAccess(ctx context.Context, arg CreateLeadStageRoleAccessParams) error {
	_, err := q.db.Exec(ctx, createLeadStageRoleAccess,
		arg.WorkspaceID,
		arg.StageID,
		arg.RoleID,
		arg.CanView,
		arg.CanEnter,
		arg.CanLeave,
	)
	return err
}

const createPipelineStageRoleAccess = `-- name: CreatePipelineStageRoleAccess :exec
INSERT INTO sales.pipeline_stage_role_access (
  workspace_id, stage_id, role_id, can_view, can_enter, can_leave
) VALUES (
  $1, $2, $3,
  $4, $5, $6
)
`

type CreatePipelineStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
	RoleID      pgtype.UUID `json:"role_id"`
	CanView     bool        `json:"can_view"`
	CanEnter    bool        `json:"can_enter"`
	CanLeave    bool        `json:"can_leave"`
}

func (q *Queries) CreatePipelineStageRoleAccess(ctx context.Context, arg CreatePipelineStageRoleAccessParams) error {
	_, err := q.db.Exec(ctx, createPipelineStageRoleAccess,
		arg.WorkspaceID,
		arg.StageID,
		arg.RoleID,
		arg.CanView,
		arg.CanEnter,
		arg.CanLeave,
	)
	return err
}

const deleteLeadStageRoleAccess = `-- name: DeleteLeadStageRoleAccess :exec
DELETE FROM sales.lead_stage_role_access
WHERE workspace_id = $1 AND stage_id = $2
`

type DeleteLeadStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) DeleteLeadStageRoleAccess(ctx context.Context, arg DeleteLeadStageRoleAccessParams) error {
	_, err := q.db.Exec(ctx, deleteLeadStageRoleAccess, arg.WorkspaceID, arg.StageID)
	return err
}

const deletePipelineStageRoleAccess = `-- name: DeletePipelineStageRoleAccess :exec
DELETE FROM sales.pipeline_stage_role_access
WHERE workspace_id = $1 AND stage_id = $2
`

type DeletePipelineStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) DeletePipelineStageRoleAccess(ctx context.Context, arg DeletePipelineStageRoleAccessParams) error {
	_, err := q.db.Exec(ctx, deletePipelineStageRoleAccess, arg.WorkspaceID, arg.StageID)
	return err
}

const getLeadStageForAccessConfig = `-- name: GetLeadStageForAccessConfig :one
SELECT id
FROM sales.lead_stages
WHERE workspace_id = $1 AND id = $2 AND archived_at IS NULL
`

type GetLeadStageForAccessConfigParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) GetLeadStageForAccessConfig(ctx context.Context, arg GetLeadStageForAccessConfigParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLeadStageForAccessConfig, arg.WorkspaceID, arg.StageID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getPipelineStageForAccessConfig = `-- name: GetPipelineStageForAccessConfig :one
SELECT id
FROM sales.pipeline_stages
WHERE workspace_id = $1 AND id = $2
`

type GetPipelineStageForAccessConfigParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) GetPipelineStageForAccessConfig(ctx context.Context, arg GetPipelineStageForAccessConfigParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPipelineStageForAccessConfig, arg.WorkspaceID, arg.StageID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const leadStageAccessAllowed = `-- name: LeadStageAccessAllowed :one
SELECT sales.lead_stage_access_allowed(
  $1, $2, $3::text
) AS allowed
`

type LeadStageAccessAllowedParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	StageID      pgtype.UUID `json:"stage_id"`
	AccessAction string      `json:"access_action"`
}

func (q *Queries) LeadStageAccessAllowed(ctx context.Context, arg LeadStageAccessAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, leadStageAccessAllowed, arg.WorkspaceID, arg.StageID, arg.AccessAction)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const leadStageTransitionAllowed = `-- name: LeadStageTransitionAllowed :one
SELECT (CASE
  WHEN $1::uuid = $2::uuid
    THEN sales.lead_stage_access_allowed(
      $3, $1, 'view'
    )
  ELSE sales.lead_stage_access_allowed(
      $3, $1, 'leave'
    ) AND sales.lead_stage_access_allowed(
      $3, $2, 'enter'
    )
END)::boolean AS allowed
`

type LeadStageTransitionAllowedParams struct {
	FromStageID pgtype.UUID `json:"from_stage_id"`
	ToStageID   pgtype.UUID `json:"to_stage_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) LeadStageTransitionAllowed(ctx context.Context, arg LeadStageTransitionAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, leadStageTransitionAllowed, arg.FromStageID, arg.ToStageID, arg.WorkspaceID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const listLeadStageRoleAccess = `-- name: ListLeadStageRoleAccess :many
SELECT access.role_id, role.role_key, role.name AS role_name, role.base_role,
       access.can_view, access.can_enter, access.can_leave,
       access.created_at, access.updated_at
FROM sales.lead_stage_role_access access
JOIN tenancy.workspace_roles role
  ON role.workspace_id = access.workspace_id AND role.id = access.role_id
WHERE access.workspace_id = $1
  AND access.stage_id = $2
ORDER BY role.is_system DESC, role.name, role.id
LIMIT $3
`

type ListLeadStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
	ResultLimit int32       `json:"result_limit"`
}

type ListLeadStageRoleAccessRow struct {
	RoleID    pgtype.UUID        `json:"role_id"`
	RoleKey   string             `json:"role_key"`
	RoleName  string             `json:"role_name"`
	BaseRole  string             `json:"base_role"`
	CanView   bool               `json:"can_view"`
	CanEnter  bool               `json:"can_enter"`
	CanLeave  bool               `json:"can_leave"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListLeadStageRoleAccess(ctx context.Context, arg ListLeadStageRoleAccessParams) ([]ListLeadStageRoleAccessRow, error) {
	rows, err := q.db.Query(ctx, listLeadStageRoleAccess, arg.WorkspaceID, arg.StageID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLeadStageRoleAccessRow{}
	for rows.Next() {
		var i ListLeadStageRoleAccessRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleKey,
			&i.RoleName,
			&i.BaseRole,
			&i.CanView,
			&i.CanEnter,
			&i.CanLeave,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPipelineStageRoleAccess = `-- name: ListPipelineStageRoleAccess :many
SELECT access.role_id, role.role_key, role.name AS role_name, role.base_role,
       access.can_view, access.can_enter, access.can_leave,
       access.created_at, access.updated_at
FROM sales.pipeline_stage_role_access access
JOIN tenancy.workspace_roles role
  ON role.workspace_id = access.workspace_id AND role.id = access.role_id
WHERE access.workspace_id = $1
  AND access.stage_id = $2
ORDER BY role.is_system DESC, role.name, role.id
LIMIT $3
`

type ListPipelineStageRoleAccessParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
	ResultLimit int32       `json:"result_limit"`
}

type ListPipelineStageRoleAccessRow struct {
	RoleID    pgtype.UUID        `json:"role_id"`
	RoleKey   string             `json:"role_key"`
	RoleName  string             `json:"role_name"`
	BaseRole  string             `json:"base_role"`
	CanView   bool               `json:"can_view"`
	CanEnter  bool               `json:"can_enter"`
	CanLeave  bool               `json:"can_leave"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPipelineStageRoleAccess(ctx context.Context, arg ListPipelineStageRoleAccessParams) ([]ListPipelineStageRoleAccessRow, error) {
	rows, err := q.db.Query(ctx, listPipelineStageRoleAccess, arg.WorkspaceID, arg.StageID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPipelineStageRoleAccessRow{}
	for rows.Next() {
		var i ListPipelineStageRoleAccessRow
		if err := rows.Scan(
			&i.RoleID,
			&i.RoleKey,
			&i.RoleName,
			&i.BaseRole,
			&i.CanView,
			&i.CanEnter,
			&i.CanLeave,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockLeadStageForAccessReplace = `-- name: LockLeadStageForAccessReplace :one
SELECT id
FROM sales.lead_stages
WHERE workspace_id = $1 AND id = $2 AND archived_at IS NULL
FOR UPDATE
`

type LockLeadStageForAccessReplaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) LockLeadStageForAccessReplace(ctx context.Context, arg LockLeadStageForAccessReplaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockLeadStageForAccessReplace, arg.WorkspaceID, arg.StageID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockPipelineStageForAccessReplace = `-- name: LockPipelineStageForAccessReplace :one
SELECT id
FROM sales.pipeline_stages
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type LockPipelineStageForAccessReplaceParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	StageID     pgtype.UUID `json:"stage_id"`
}

func (q *Queries) LockPipelineStageForAccessReplace(ctx context.Context, arg LockPipelineStageForAccessReplaceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, lockPipelineStageForAccessReplace, arg.WorkspaceID, arg.StageID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const pipelineStageAccessAllowed = `-- name: PipelineStageAccessAllowed :one
SELECT sales.pipeline_stage_access_allowed(
  $1, $2, $3::text
) AS allowed
`

type PipelineStageAccessAllowedParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	StageID      pgtype.UUID `json:"stage_id"`
	AccessAction string      `json:"access_action"`
}

func (q *Queries) PipelineStageAccessAllowed(ctx context.Context, arg PipelineStageAccessAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, pipelineStageAccessAllowed, arg.WorkspaceID, arg.StageID, arg.AccessAction)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const pipelineStageTransitionAllowed = `-- name: PipelineStageTransitionAllowed :one
SELECT (CASE
  WHEN $1::uuid = $2::uuid
    THEN sales.pipeline_stage_access_allowed(
      $3, $1, 'view'
    )
  ELSE sales.pipeline_stage_access_allowed(
      $3, $1, 'leave'
    ) AND sales.pipeline_stage_access_allowed(
      $3, $2, 'enter'
    )
END)::boolean AS allowed
`

type PipelineStageTransitionAllowedParams struct {
	FromStageID pgtype.UUID `json:"from_stage_id"`
	ToStageID   pgtype.UUID `json:"to_stage_id"`
	WorkspaceID pgtype.UUID `json:"workspace_id"`
}

func (q *Queries) PipelineStageTransitionAllowed(ctx context.Context, arg PipelineStageTransitionAllowedParams) (bool, error) {
	row := q.db.QueryRow(ctx, pipelineStageTransitionAllowed, arg.FromStageID, arg.ToStageID, arg.WorkspaceID)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}
