// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tenancy_advanced.sql

package dbgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :execrows
UPDATE tenancy.invitations
SET accepted_at = now(), accepted_by_user_id = $3
WHERE workspace_id = $1 AND id = $2 AND accepted_at IS NULL
`

type AcceptInvitationParams struct {
	WorkspaceID      pgtype.UUID `json:"workspace_id"`
	ID               pgtype.UUID `json:"id"`
	AcceptedByUserID pgtype.UUID `json:"accepted_by_user_id"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptInvitation, arg.WorkspaceID, arg.ID, arg.AcceptedByUserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const addTeamMembership = `-- name: AddTeamMembership :exec
INSERT INTO tenancy.team_memberships (workspace_id, team_id, membership_id)
VALUES ($1, $2, $3)
ON CONFLICT DO NOTHING
`

type AddTeamMembershipParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	TeamID       pgtype.UUID `json:"team_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

func (q *Queries) AddTeamMembership(ctx context.Context, arg AddTeamMembershipParams) error {
	_, err := q.db.Exec(ctx, addTeamMembership, arg.WorkspaceID, arg.TeamID, arg.MembershipID)
	return err
}

const createInvitation = `-- name: CreateInvitation :one
INSERT INTO tenancy.invitations (
  workspace_id, id, email_normalized, role, token_hash, invited_by, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING workspace_id, id, email_normalized, role, token_hash, invited_by,
          expires_at, accepted_at, accepted_by_user_id, created_at
`

type CreateInvitationParams struct {
	WorkspaceID     pgtype.UUID        `json:"workspace_id"`
	ID              pgtype.UUID        `json:"id"`
	EmailNormalized string             `json:"email_normalized"`
	Role            string             `json:"role"`
	TokenHash       []byte             `json:"token_hash"`
	InvitedBy       pgtype.UUID        `json:"invited_by"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
}

type CreateInvitationRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	EmailNormalized  string             `json:"email_normalized"`
	Role             string             `json:"role"`
	TokenHash        []byte             `json:"token_hash"`
	InvitedBy        pgtype.UUID        `json:"invited_by"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateInvitation(ctx context.Context, arg CreateInvitationParams) (CreateInvitationRow, error) {
	row := q.db.QueryRow(ctx, createInvitation,
		arg.WorkspaceID,
		arg.ID,
		arg.EmailNormalized,
		arg.Role,
		arg.TokenHash,
		arg.InvitedBy,
		arg.ExpiresAt,
	)
	var i CreateInvitationRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.EmailNormalized,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const createTeam = `-- name: CreateTeam :one
INSERT INTO tenancy.teams (workspace_id, id, name)
VALUES ($1, $2, $3)
RETURNING workspace_id, id, name, version, created_at, updated_at
`

type CreateTeamParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Name        string      `json:"name"`
}

func (q *Queries) CreateTeam(ctx context.Context, arg CreateTeamParams) (TenancyTeam, error) {
	row := q.db.QueryRow(ctx, createTeam, arg.WorkspaceID, arg.ID, arg.Name)
	var i TenancyTeam
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMembershipByIDForUpdate = `-- name: GetMembershipByIDForUpdate :one
SELECT workspace_id, id, user_id, role, status, locale_override,
       timezone_override, created_at, updated_at, role_id
FROM tenancy.memberships
WHERE workspace_id = $1 AND id = $2
FOR UPDATE
`

type GetMembershipByIDForUpdateParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetMembershipByIDForUpdate(ctx context.Context, arg GetMembershipByIDForUpdateParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByIDForUpdate, arg.WorkspaceID, arg.ID)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getMembershipByUserID = `-- name: GetMembershipByUserID :one
SELECT workspace_id, id, user_id, role, status, locale_override,
       timezone_override, created_at, updated_at, role_id
FROM tenancy.memberships
WHERE workspace_id = $1 AND user_id = $2
`

type GetMembershipByUserIDParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	UserID      pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetMembershipByUserID(ctx context.Context, arg GetMembershipByUserIDParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, getMembershipByUserID, arg.WorkspaceID, arg.UserID)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const getTeam = `-- name: GetTeam :one
SELECT workspace_id, id, name, version, created_at, updated_at
FROM tenancy.teams
WHERE workspace_id = $1 AND id = $2
`

type GetTeamParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) GetTeam(ctx context.Context, arg GetTeamParams) (TenancyTeam, error) {
	row := q.db.QueryRow(ctx, getTeam, arg.WorkspaceID, arg.ID)
	var i TenancyTeam
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.Name,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTeamMemberships = `-- name: ListTeamMemberships :many
SELECT tm.workspace_id, tm.team_id, tm.membership_id, tm.created_at,
       u.id AS user_id, u.email, u.display_name
FROM tenancy.team_memberships tm
JOIN tenancy.memberships m
  ON m.workspace_id = tm.workspace_id AND m.id = tm.membership_id
JOIN identity.users u ON u.id = m.user_id
WHERE tm.workspace_id = $1 AND tm.team_id = $2
ORDER BY u.display_name, u.id
`

type ListTeamMembershipsParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	TeamID      pgtype.UUID `json:"team_id"`
}

type ListTeamMembershipsRow struct {
	WorkspaceID  pgtype.UUID        `json:"workspace_id"`
	TeamID       pgtype.UUID        `json:"team_id"`
	MembershipID pgtype.UUID        `json:"membership_id"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UserID       pgtype.UUID        `json:"user_id"`
	Email        string             `json:"email"`
	DisplayName  string             `json:"display_name"`
}

func (q *Queries) ListTeamMemberships(ctx context.Context, arg ListTeamMembershipsParams) ([]ListTeamMembershipsRow, error) {
	rows, err := q.db.Query(ctx, listTeamMemberships, arg.WorkspaceID, arg.TeamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTeamMembershipsRow{}
	for rows.Next() {
		var i ListTeamMembershipsRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.TeamID,
			&i.MembershipID,
			&i.CreatedAt,
			&i.UserID,
			&i.Email,
			&i.DisplayName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeams = `-- name: ListTeams :many
SELECT workspace_id, id, name, version, created_at, updated_at
FROM tenancy.teams
WHERE workspace_id = $1
ORDER BY name, id
`

func (q *Queries) ListTeams(ctx context.Context, workspaceID pgtype.UUID) ([]TenancyTeam, error) {
	rows, err := q.db.Query(ctx, listTeams, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TenancyTeam{}
	for rows.Next() {
		var i TenancyTeam
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.Name,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT m.workspace_id, m.id, m.user_id, m.role, m.role_id, role.name AS role_name,
       m.status, m.locale_override,
       m.timezone_override, m.created_at, m.updated_at,
       u.email, u.display_name, u.preferred_locale
FROM tenancy.memberships m
JOIN identity.users u ON u.id = m.user_id
JOIN tenancy.workspace_roles role ON role.workspace_id = m.workspace_id AND role.id = m.role_id
WHERE m.workspace_id = $1
ORDER BY u.display_name, u.id
`

type ListWorkspaceMembersRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	UserID           pgtype.UUID        `json:"user_id"`
	Role             string             `json:"role"`
	RoleID           pgtype.UUID        `json:"role_id"`
	RoleName         string             `json:"role_name"`
	Status           string             `json:"status"`
	LocaleOverride   *string            `json:"locale_override"`
	TimezoneOverride *string            `json:"timezone_override"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	Email            string             `json:"email"`
	DisplayName      string             `json:"display_name"`
	PreferredLocale  string             `json:"preferred_locale"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID pgtype.UUID) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWorkspaceMembersRow{}
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.WorkspaceID,
			&i.ID,
			&i.UserID,
			&i.Role,
			&i.RoleID,
			&i.RoleName,
			&i.Status,
			&i.LocaleOverride,
			&i.TimezoneOverride,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Email,
			&i.DisplayName,
			&i.PreferredLocale,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockInvitationByHash = `-- name: LockInvitationByHash :one
SELECT workspace_id, id, email_normalized, role, token_hash, invited_by,
       expires_at, accepted_at, accepted_by_user_id, created_at
FROM tenancy.invitations
WHERE workspace_id = $1 AND token_hash = $2
  AND accepted_at IS NULL AND expires_at > now()
FOR UPDATE
`

type LockInvitationByHashParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	TokenHash   []byte      `json:"token_hash"`
}

type LockInvitationByHashRow struct {
	WorkspaceID      pgtype.UUID        `json:"workspace_id"`
	ID               pgtype.UUID        `json:"id"`
	EmailNormalized  string             `json:"email_normalized"`
	Role             string             `json:"role"`
	TokenHash        []byte             `json:"token_hash"`
	InvitedBy        pgtype.UUID        `json:"invited_by"`
	ExpiresAt        pgtype.Timestamptz `json:"expires_at"`
	AcceptedAt       pgtype.Timestamptz `json:"accepted_at"`
	AcceptedByUserID pgtype.UUID        `json:"accepted_by_user_id"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) LockInvitationByHash(ctx context.Context, arg LockInvitationByHashParams) (LockInvitationByHashRow, error) {
	row := q.db.QueryRow(ctx, lockInvitationByHash, arg.WorkspaceID, arg.TokenHash)
	var i LockInvitationByHashRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.EmailNormalized,
		&i.Role,
		&i.TokenHash,
		&i.InvitedBy,
		&i.ExpiresAt,
		&i.AcceptedAt,
		&i.AcceptedByUserID,
		&i.CreatedAt,
	)
	return i, err
}

const lockWorkspaceMembershipMutation = `-- name: LockWorkspaceMembershipMutation :exec
SELECT pg_advisory_xact_lock(hashtextextended($1::text, 0))
`

func (q *Queries) LockWorkspaceMembershipMutation(ctx context.Context, workspaceID string) error {
	_, err := q.db.Exec(ctx, lockWorkspaceMembershipMutation, workspaceID)
	return err
}

const removeTeamMembership = `-- name: RemoveTeamMembership :execrows
DELETE FROM tenancy.team_memberships
WHERE workspace_id = $1 AND team_id = $2 AND membership_id = $3
`

type RemoveTeamMembershipParams struct {
	WorkspaceID  pgtype.UUID `json:"workspace_id"`
	TeamID       pgtype.UUID `json:"team_id"`
	MembershipID pgtype.UUID `json:"membership_id"`
}

func (q *Queries) RemoveTeamMembership(ctx context.Context, arg RemoveTeamMembershipParams) (int64, error) {
	result, err := q.db.Exec(ctx, removeTeamMembership, arg.WorkspaceID, arg.TeamID, arg.MembershipID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMembershipLocaleOverride = `-- name: UpdateMembershipLocaleOverride :one
UPDATE tenancy.memberships
SET locale_override = $3, updated_at = now()
WHERE workspace_id = $1 AND user_id = $2
RETURNING workspace_id, id, user_id, role, status, locale_override,
          timezone_override, created_at, updated_at, role_id
`

type UpdateMembershipLocaleOverrideParams struct {
	WorkspaceID    pgtype.UUID `json:"workspace_id"`
	UserID         pgtype.UUID `json:"user_id"`
	LocaleOverride *string     `json:"locale_override"`
}

func (q *Queries) UpdateMembershipLocaleOverride(ctx context.Context, arg UpdateMembershipLocaleOverrideParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipLocaleOverride, arg.WorkspaceID, arg.UserID, arg.LocaleOverride)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const updateMembershipRole = `-- name: UpdateMembershipRole :one
UPDATE tenancy.memberships membership
SET role = role.base_role, role_id = role.id, updated_at = now()
FROM tenancy.workspace_roles role
WHERE membership.workspace_id = $1 AND membership.id = $2
  AND role.workspace_id = membership.workspace_id AND role.role_key = $3 AND role.is_system
RETURNING membership.workspace_id, membership.id, membership.user_id, membership.role,
          membership.status, membership.locale_override, membership.timezone_override,
          membership.created_at, membership.updated_at, membership.role_id
`

type UpdateMembershipRoleParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	RoleKey     string      `json:"role_key"`
}

func (q *Queries) UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipRole, arg.WorkspaceID, arg.ID, arg.RoleKey)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const updateMembershipStatus = `-- name: UpdateMembershipStatus :one
UPDATE tenancy.memberships
SET status = $3, updated_at = now()
WHERE workspace_id = $1 AND id = $2
RETURNING workspace_id, id, user_id, role, status, locale_override,
          timezone_override, created_at, updated_at, role_id
`

type UpdateMembershipStatusParams struct {
	WorkspaceID pgtype.UUID `json:"workspace_id"`
	ID          pgtype.UUID `json:"id"`
	Status      string      `json:"status"`
}

func (q *Queries) UpdateMembershipStatus(ctx context.Context, arg UpdateMembershipStatusParams) (TenancyMembership, error) {
	row := q.db.QueryRow(ctx, updateMembershipStatus, arg.WorkspaceID, arg.ID, arg.Status)
	var i TenancyMembership
	err := row.Scan(
		&i.WorkspaceID,
		&i.ID,
		&i.UserID,
		&i.Role,
		&i.Status,
		&i.LocaleOverride,
		&i.TimezoneOverride,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.RoleID,
	)
	return i, err
}

const updateWorkspaceDefaults = `-- name: UpdateWorkspaceDefaults :one
UPDATE tenancy.workspaces
SET default_locale = $1,
    timezone = $2,
    default_currency = $3,
    version = version + 1,
    updated_at = now()
WHERE id = $4 AND version = $5
RETURNING id, name, slug, default_locale, timezone, default_currency,
          supported_locales, version, created_at, updated_at
`

type UpdateWorkspaceDefaultsParams struct {
	DefaultLocale   string      `json:"default_locale"`
	Timezone        string      `json:"timezone"`
	DefaultCurrency string      `json:"default_currency"`
	WorkspaceID     pgtype.UUID `json:"workspace_id"`
	ExpectedVersion int64       `json:"expected_version"`
}

type UpdateWorkspaceDefaultsRow struct {
	ID               pgtype.UUID        `json:"id"`
	Name             string             `json:"name"`
	Slug             string             `json:"slug"`
	DefaultLocale    string             `json:"default_locale"`
	Timezone         string             `json:"timezone"`
	DefaultCurrency  string             `json:"default_currency"`
	SupportedLocales []string           `json:"supported_locales"`
	Version          int64              `json:"version"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpdateWorkspaceDefaults(ctx context.Context, arg UpdateWorkspaceDefaultsParams) (UpdateWorkspaceDefaultsRow, error) {
	row := q.db.QueryRow(ctx, updateWorkspaceDefaults,
		arg.DefaultLocale,
		arg.Timezone,
		arg.DefaultCurrency,
		arg.WorkspaceID,
		arg.ExpectedVersion,
	)
	var i UpdateWorkspaceDefaultsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.DefaultLocale,
		&i.Timezone,
		&i.DefaultCurrency,
		&i.SupportedLocales,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
