DROP SCHEMA IF EXISTS reporting CASCADE;
DROP SCHEMA IF EXISTS files CASCADE;
DROP SCHEMA IF EXISTS integrations CASCADE;
DROP SCHEMA IF EXISTS automation CASCADE;
DROP SCHEMA IF EXISTS notifications CASCADE;
DROP SCHEMA IF EXISTS search CASCADE;
DROP SCHEMA IF EXISTS audit CASCADE;
DROP SCHEMA IF EXISTS activities CASCADE;
DROP SCHEMA IF EXISTS sales CASCADE;
DROP SCHEMA IF EXISTS customers CASCADE;
DROP SCHEMA IF EXISTS tenancy CASCADE;
DROP SCHEMA IF EXISTS identity CASCADE;
DROP SCHEMA IF EXISTS platform CASCADE;
DROP SCHEMA IF EXISTS security CASCADE;

