import { createHash } from "node:crypto";
import { execFileSync } from "node:child_process";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { dirname, join, relative, resolve } from "node:path";
import process from "node:process";

const root = resolve(import.meta.dirname, "..");
const sourceRoot = join(root, "packages", "i18n", "source", "en");
const localeRoot = join(root, "packages", "i18n", "locales");
const manifest = JSON.parse(
  await readFile(
    join(root, "packages", "i18n", "locale-manifest.json"),
    "utf8",
  ),
);
const checkOnly = process.argv.includes("--check");

const files = (await readdir(sourceRoot))
  .filter((name) => name.endsWith(".json"))
  .sort();
const sourceCatalogs = new Map();
const allKeys = [];
const errors = [];

function placeholders(value) {
  return [...value.matchAll(/\{([A-Za-z][A-Za-z0-9_]*)\}/g)]
    .map((match) => match[1])
    .sort();
}

function sameArray(left, right) {
  return (
    left.length === right.length &&
    left.every((item, index) => item === right[index])
  );
}

for (const file of files) {
  const source = JSON.parse(await readFile(join(sourceRoot, file), "utf8"));
  sourceCatalogs.set(file, source);
  for (const key of Object.keys(source).sort())
    allKeys.push(`${file.slice(0, -5)}.${key}`);

  for (const locale of manifest.locales) {
    if (locale.tag === "en") continue;
    const targetPath = join(localeRoot, locale.tag, file);
    let target;
    try {
      target = JSON.parse(await readFile(targetPath, "utf8"));
    } catch (error) {
      errors.push(
        `${locale.tag}/${file}: missing or invalid catalog (${error.message})`,
      );
      continue;
    }
    const sourceKeys = Object.keys(source).sort();
    const targetKeys = Object.keys(target).sort();
    if (!sameArray(sourceKeys, targetKeys)) {
      const missing = sourceKeys.filter((key) => !(key in target));
      const extra = targetKeys.filter((key) => !(key in source));
      if (missing.length)
        errors.push(
          `${locale.tag}/${file}: missing keys ${missing.join(", ")}`,
        );
      if (extra.length)
        errors.push(`${locale.tag}/${file}: extra keys ${extra.join(", ")}`);
    }
    for (const key of sourceKeys) {
      if (typeof source[key] !== "string" || typeof target[key] !== "string") {
        errors.push(`${locale.tag}/${file}:${key}: message must be a string`);
        continue;
      }
      const sourceParams = placeholders(source[key]);
      const targetParams = placeholders(target[key]);
      if (target[key].startsWith("⟦TODO⟧")) {
        errors.push(`${locale.tag}/${file}:${key}: translation is still TODO`);
      }
      if (!sameArray(sourceParams, targetParams)) {
        errors.push(
          `${locale.tag}/${file}:${key}: placeholders differ (${sourceParams} vs ${targetParams})`,
        );
      }
    }
  }
}

if (errors.length) {
  process.stderr.write(`${errors.join("\n")}\n`);
  process.exit(1);
}

const tsKeys = allKeys.map((key) => `  | '${key}'`).join("\n");
const tsOutput = `// Code generated by scripts/generate-i18n.mjs. DO NOT EDIT.\nexport type MessageKey =\n${tsKeys};\n\nexport type MessageParams = Readonly<Record<string, string | number | boolean>>;\n`;

const localeCatalogs = {};
for (const locale of manifest.locales) {
  localeCatalogs[locale.tag] = {};
  for (const file of files) {
    const source = sourceCatalogs.get(file);
    const catalog =
      locale.tag === "en"
        ? source
        : JSON.parse(
            await readFile(join(localeRoot, locale.tag, file), "utf8"),
          );
    localeCatalogs[locale.tag][file] = catalog;
  }
}

const goMap = Object.entries(localeCatalogs)
  .map(([locale, catalogs]) => {
    const entries = [];
    for (const [file, messages] of Object.entries(catalogs)) {
      const namespace = file.slice(0, -5);
      for (const [key, value] of Object.entries(messages)) {
        entries.push(
          `\t\t${JSON.stringify(`${namespace}.${key}`)}: ${JSON.stringify(value)},`,
        );
      }
    }
    return `\t${JSON.stringify(locale)}: {\n${entries.join("\n")}\n\t},`;
  })
  .join("\n");
const goOutput = execFileSync("gofmt", [], {
  encoding: "utf8",
  input: `// Code generated by scripts/generate-i18n.mjs. DO NOT EDIT.\npackage localization\n\nvar catalogs = map[string]map[string]string{\n${goMap}\n}\n`,
});

const outputs = new Map([
  [
    join(
      root,
      "apps",
      "web",
      "src",
      "app",
      "core",
      "i18n",
      "message-key.generated.ts",
    ),
    tsOutput,
  ],
  [
    join(root, "apps", "api", "internal", "localization", "catalogs_gen.go"),
    goOutput,
  ],
]);

for (const [locale, catalogs] of Object.entries(localeCatalogs)) {
  for (const [file, messages] of Object.entries(catalogs)) {
    outputs.set(
      join(root, "apps", "web", "public", "i18n", locale, file),
      `${JSON.stringify(messages)}\n`,
    );
  }
}

for (const [path, content] of outputs) {
  if (checkOnly) {
    let current = "";
    try {
      current = await readFile(path, "utf8");
    } catch {}
    if (current !== content) {
      errors.push(`${relative(root, path)} is stale; run pnpm generate:i18n`);
    }
  } else {
    await mkdir(dirname(path), { recursive: true });
    await writeFile(path, content);
  }
}

if (errors.length) {
  process.stderr.write(`${errors.join("\n")}\n`);
  process.exit(1);
}

const digest = createHash("sha256")
  .update([...outputs.values()].join("\0"))
  .digest("hex")
  .slice(0, 16);
process.stdout.write(
  `i18n catalogs valid (${allKeys.length} source keys, ${manifest.locales.length} locales, ${digest})\n`,
);
